### ISSUE TITLE
How do I delete a folder with the same name as the zip file?

### ISSUE THREAD

**Issue by lakxtxue** [srikanth-lingala/zip4j#101]
Hello
Sorry, English is not good. Zip4j is really great! I noticed the zip file I created. After unzipping, I have a root folder with the same name as the zip file. When creating a zip file, can I configure not to have a root folder?

**Comment by srikanth-lingala** [comment]
Yes, you can do it with `ZipParameters.setIncludeRootFolder(false)`

**Comment by lakxtxue** [comment]
I did try this, but it didn't work. I am using the v2.2.4 version.

**Comment by srikanth-lingala** [comment]
Can you post the code you used?

**Comment by lakxtxue** [comment]
Please see this is my test code. I found that `zipParameters.setIncludeRootFolder(false)` is valid if it is just a single file. If it is to compress multiple files, this parameter seems to be ignored.

`@Test
    public void compressFiles() throws IOException {
        ZipFile zipFile = new ZipFile("/Desktop/ias.zip");
        zipFile.setCharset(Charset.forName("UTF-8"));

        ZipParameters zipParameter = new ZipParameters();
        zipParameter.setIncludeRootFolder(false);
        zipFile.addFile(new File("/Desktop/ias.app"), zipParameter);

        ZipParameters zipParameter1 = new ZipParameters();
        zipParameter1.setIncludeRootFolder(false);
        zipParameter1.setFileNameInZip("shadowsocks.txt");
        zipFile.addStream(new FileInputStream(new File("/Users/lakxtxue/Desktop/shadowsocks.txt")),zipParameter1);
    }

    @Test
    public void createEncryptedZip() throws IOException {
        ZipFile zipFile = new ZipFile("/Desktop/ias.zip","hello".toCharArray());
        zipFile.setCharset(Charset.forName("UTF-8"));

        ZipParameters zipParameters = new ZipParameters();
        zipParameters.setCompressionLevel(CompressionLevel.MAXIMUM);
        zipParameters.setEncryptFiles(true);
        zipParameters.setEncryptionMethod(EncryptionMethod.ZIP_STANDARD);
        zipParameters.setIncludeRootFolder(false);
        zipFile.addFile(new File("/Desktop/ias.app"), zipParameters);

        ZipParameters zipParameter1 = new ZipParameters();
        zipParameters1.setCompressionLevel(CompressionLevel.MAXIMUM);
        zipParameters1.setEncryptFiles(true);
        zipParameters1.setEncryptionMethod(EncryptionMethod.ZIP_STANDARD);
        zipParameters1.setIncludeRootFolder(false);
        zipFile.addFile(new File("/Desktop/shadowsocks.txt"),zipParameter1);
    }`

**Comment by srikanth-lingala** [comment]
`zipParameters.setIncludeRootFolder` is only applicable when you add a folder to a zip i.e, `ZipFile.addFolder()`. When you add files, only the file name is added as the name of the file in zip.

Your issue has nothing to do when adding the files. It has to do with the tool with which you are extracting the zip file. That tool is creating the directory with the same name as the zip file.

**Comment by lakxtxue** [comment]
我关闭了问题，你是对的，谢谢你解决了我的问题。
