### ISSUE TITLE
Extracting 7z file throwing an error

### ISSUE THREAD

**Issue by kartikj07** [srikanth-lingala/zip4j#104]
Hi, I am using this library to unzip a .7z file I found required for my code and this library doesn't seem to extract the 7z file properly. Every time I try to unzip the file, it throws me this error

`net.lingala.zip4j.exception.ZipException: zip headers not found. probably not a zip file`

So does this mean I cannot unzip a 7z file using this library?

**Comment by srikanth-lingala** [comment]
Zip4j, as the title in readme suggests, only works with zip files and not 7z.

**Comment by kartikj07** [comment]
Thanks for the quick reply. I started using zip file for the process and your library is very helpful and fits in the size constraint of the application. 
Thank you for this awesome library, sir.

**Comment by asthagarg2428** [comment]
@srikanth-lingala Does this library still not support 7z?
