### ISSUE TITLE
miss file when i unzip in Android 4.4

### ISSUE THREAD

**Issue by xiao-mao-lv** [srikanth-lingala/zip4j#105]
i get 202 files when i unzip on my Mac Computer, 
but i get 59 files when i unzip by code extractAll，miss a lots of files

the version i use 2.2.4

Here is the zip and password
"password":"f06be35461cb4b25821448373499471b",      "url":"http://hipanda.hf.openstorage.cn/manager/zip/06b5bb815ad5476b88a2c32273b0c48a.zip"

**Comment by xiao-mao-lv** [comment]
`        Log.e(TAG, "unzip: start" );
        String archive = Environment.getExternalStorageDirectory().getAbsolutePath()+"/zip/06b5bb815ad5476b88a2c32273b0c48a.zip";
        String decompressDir = Environment.getExternalStorageDirectory().getAbsolutePath()+"/zip/unzip";
        String password = "f06be35461cb4b25821448373499471b";


        Log.e(TAG, "unzip: "+archive );
        Log.e(TAG, "unzip: "+decompressDir );

        ZipFile zipFile;
        zipFile = new ZipFile(archive);
        if (!zipFile.isValidZipFile()) {
            Log.e(TAG, "unzip: isValidZipFile");
            return;
        }

        try {
            if(zipFile.isEncrypted()) {
                zipFile.setPassword(password.toCharArray());
            }
        } catch (ZipException e) {
            Log.e(TAG, "unzip: "+ e.getMessage());
        }

        File destDir = new File(decompressDir);
        if (destDir.isDirectory() && !destDir.exists()) {
            if(!destDir.mkdir()) {
            }
        }

        zipFile.setRunInThread(true);

        try {
            zipFile.extractAll(decompressDir);
        } catch (ZipException e) {
            Log.e(TAG, "unzip: "+e.getMessage() );
        }`

**Comment by srikanth-lingala** [comment]
I guess what you are missing is to wait until the extraction process is done. When you set `runInThread` to true, zip4j extracts in a background thread than the _main_ thread. Therefore you will have to wait until the background thread is complete. Example below shows how to do that.

```
import net.lingala.zip4j.progress.ProgressMonitor;
import org.junit.Test;

import java.io.File;
import java.io.IOException;

public class ZipTest {

  @Test
  public void testExtract() throws IOException, InterruptedException {
    String basePath = "/Users/srikanth/Downloads/test/";
    String path = basePath + "06b5bb815ad5476b88a2c32273b0c48a.zip";

    ZipFile zipFile = new ZipFile(new File(path), "f06be35461cb4b25821448373499471b".toCharArray());
    zipFile.setRunInThread(true);
    zipFile.extractAll(basePath + "extracted/");

    // This is how you wait until the extraction process is complete
    ProgressMonitor progressMonitor = zipFile.getProgressMonitor();
    while (progressMonitor.getState() == ProgressMonitor.State.BUSY) {
      System.out.println("Percentage complete: " + progressMonitor.getPercentDone());
      Thread.sleep(100);
    }
  }
}
```

**Comment by hhdsyxwei** [comment]
I also encounter problem like this.

**Comment by srikanth-lingala** [comment]
@hhdsyxwei Please try with waiting until the process is done as suggested in my post above.

**Comment by hhdsyxwei** [comment]
I already did it as your suggesstion: 
File destDir = new File(decompressDir);
        if (destDir.isDirectory() && !destDir.exists()) {
            if(!destDir.mkdir()) {
                publishProgress(appCtx,bookId,-1);
                return ResultCode.RESULT_IO_EXCEPTION;
            }
        }
        //zipFile.setRunInThread();
        zipFile.setRunInThread(true);
        ProgressMonitor pm = zipFile.getProgressMonitor();

        try {
            zipFile.extractAll(decompressDir);
        } catch (ZipException e) {
            publishProgress(appCtx,bookId,-1);
            return ResultCode.RESULT_IO_EXCEPTION;
        }

        Log.d(TAG,"unZipFile: state = " + pm.getState());

        int percentDone = 0;
        while (ProgressMonitor.State.BUSY == pm.getState() &&
                !isCancelled()) {
            percentDone = pm.getPercentDone();
            publishProgress(appCtx,bookId, percentDone);
            try {
                Thread.sleep(1000);
            } catch (InterruptedException e) {

            }
        }

**Comment by hhdsyxwei** [comment]
I step into source code encountering EOFException and message:Unexpected end of ZLIB input stream.

  private void fill() throws IOException {
    len = super.read(buff, 0, buff.length);
    if (len == -1) {
      throw new EOFException("Unexpected end of ZLIB input stream");
    }
    inflater.setInput(buff, 0, len);
  }

**Comment by xiao-mao-lv** [comment]
@srikanth-lingala  I copy your code and try。but percentage only to 19, and to end, not go to 100%
wait a while, I check the amount of files , found over 39, miss a lot of files

11-14 16:55:11.081 5973-6010/com.toycloud.zipdemo D/dalvikvm: VFY: replacing opcode 0x6e at 0x0000
11-14 16:55:11.131 5973-6009/com.toycloud.zipdemo E/MainActivity: Percentage complete: 0
11-14 16:55:11.231 5973-6009/com.toycloud.zipdemo E/MainActivity: Percentage complete: 2
11-14 16:55:11.271 5973-6010/com.toycloud.zipdemo D/dalvikvm: GC_FOR_ALLOC freed 330K, 17% free 2535K/3048K, paused 6ms, total 6ms
11-14 16:55:11.331 5973-6009/com.toycloud.zipdemo E/MainActivity: Percentage complete: 4
11-14 16:55:11.431 5973-6009/com.toycloud.zipdemo E/MainActivity: Percentage complete: 7
11-14 16:55:11.531 5973-6009/com.toycloud.zipdemo E/MainActivity: Percentage complete: 10
11-14 16:55:11.631 5973-6009/com.toycloud.zipdemo E/MainActivity: Percentage complete: 13
11-14 16:55:11.731 5973-6009/com.toycloud.zipdemo E/MainActivity: Percentage complete: 16
11-14 16:55:11.831 5973-6009/com.toycloud.zipdemo E/MainActivity: Percentage complete: 19
11-14 16:55:11.931 5973-6009/com.toycloud.zipdemo E/MainActivity: end: 

```

                    Log.e(TAG, "unzip: start" );
                    String archive = Environment.getExternalStorageDirectory().getAbsolutePath()+"/zip/06b5bb815ad5476b88a2c32273b0c48a.zip";
                    String decompressDir = Environment.getExternalStorageDirectory().getAbsolutePath()+"/zip/unzip";
                    String password = "f06be35461cb4b25821448373499471b";

                    ZipFile zipFile = new ZipFile(new File(archive), password.toCharArray());
                    zipFile.setRunInThread(true);
                    zipFile.extractAll(decompressDir);

                    // This is how you wait until the extraction process is complete
                    ProgressMonitor progressMonitor = zipFile.getProgressMonitor();
                    while (progressMonitor.getState() == ProgressMonitor.State.BUSY) {
                        Log.e(TAG, "Percentage complete: " + progressMonitor.getPercentDone());
                        Thread.sleep(1000);
                    }
                    Log.e(TAG, "end: " );
```

**Comment by srikanth-lingala** [comment]
@xiao-mao-lv I tried my example on my laptop and it works perfectly fine. You have to debug your application and see what exactly is stopping the process. From my side, I can only say that zip4j is working fine in this case.

**Comment by srikanth-lingala** [comment]
@hhdsyxwei Can you post your zip file here?

**Comment by hhdsyxwei** [comment]
I used the same zip file(with the same password) as @xiao-mao-lv

**Comment by xiao-mao-lv** [comment]
@srikanth-lingala 

I unzip this zip file on mac. I get 202 files

- 200 files like words_2266179.mp3
- 1 file json.txt
- 1 file album_142371.jpg

but unzip this zip file by code，only get 39 files

can you unzip 202 files by code ?

**Comment by hhdsyxwei** [comment]
root case stack is as follow:
11-14 17:33:13.030 D/bcm     ( 9158): unzipFile: readLength = 4096, fileHeader = words_2268219.mp3,comment = null,compressSize = 16763, uncompsize = 31808,method = DEFLATE

11-14 17:33:13.030 D/bcm     ( 9158): unzipFile: readLength = 4096, fileHeader = words_2268219.mp3,comment = null,compressSize = 16763, uncompsize = 31808,method = DEFLATE

11-14 17:33:13.030 D/bcm     ( 9158): readFully: currentReadLength = -1, offset = 0, numberOfBytesRead = 0, length = 512

11-14 17:33:13.030 D/bcm     ( 9158): AbstractExtractFileTask.unzipFile: e = java.io.EOFException: Unexpected end of ZLIB input stream

11-14 17:33:13.040 D/bcm     ( 9158): AbstractExtractFileTask.unzipFile: stack = java.io.EOFException: Unexpected end of ZLIB input stream

11-14 17:33:13.040 D/bcm     ( 9158): 	at net.lingala.zip4j.io.inputstream.InflaterInputStream.fill(InflaterInputStream.java:68)

11-14 17:33:13.040 D/bcm     ( 9158): 	at net.lingala.zip4j.io.inputstream.InflaterInputStream.read(InflaterInputStream.java:47)

11-14 17:33:13.040 D/bcm     ( 9158): 	at net.lingala.zip4j.io.inputstream.ZipInputStream.read(ZipInputStream.java:155)

11-14 17:33:13.040 D/bcm     ( 9158): 	at net.lingala.zip4j.io.inputstream.ZipInputStream.read(ZipInputStream.java:127)

11-14 17:33:13.040 D/bcm     ( 9158): 	at net.lingala.zip4j.tasks.AbstractExtractFileTask.unzipFile(AbstractExtractFileTask.java:70)

11-14 17:33:13.040 D/bcm     ( 9158): 	at net.lingala.zip4j.tasks.AbstractExtractFileTask.extractFile(AbstractExtractFileTask.java:62)

11-14 17:33:13.040 D/bcm     ( 9158): 	at net.lingala.zip4j.tasks.ExtractAllFilesTask.executeTask(ExtractAllFilesTask.java:36)

11-14 17:33:13.040 D/bcm     ( 9158): 	at net.lingala.zip4j.tasks.ExtractAllFilesTask.executeTask(ExtractAllFilesTask.java:13)

11-14 17:33:13.040 D/bcm     ( 9158): 	at net.lingala.zip4j.tasks.AsyncZipTask.performTaskWithErrorHandling(AsyncZipTask.java:53)

11-14 17:33:13.040 D/bcm     ( 9158): 	at net.lingala.zip4j.tasks.AsyncZipTask.access$100(AsyncZipTask.java:9)

11-14 17:33:13.040 D/bcm     ( 9158): 	at net.lingala.zip4j.tasks.AsyncZipTask$1.run(AsyncZipTask.java:32)

11-14 17:33:13.040 D/bcm     ( 9158): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)

11-14 17:33:13.040 D/bcm     ( 9158): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)

11-14 17:33:13.040 D/bcm     ( 9158): 	at java.lang.Thread.run(Thread.java:841)

11-14 17:33:13.310 D/bcm     ( 9158): unZipFile: percentDone = 14,isCancelled=false

11-14 17:33:13.310 D/bcm     ( 9158): onBookContentDownloadResult. resultCode = RESULT_SUCCESS, notifyItemChanged = 5

**Comment by hhdsyxwei** [comment]
The root case stack is as follow: 
unzipFile: readLength = 4096, fileHeader = words_2268219.mp3,comment = null,compressSize = 16763, 
unzipFile: readLength = 4096, fileHeader = words_2268219.mp3,comment = null,compressSize = 16763, 
readFully: currentReadLength = -1, offset = 0, numberOfBytesRead = 0, length = 512

              
AbstractExtractFileTask.unzipFile: e = java.io.EOFException: Unexpected end of ZLIB input stream

AbstractExtractFileTask.unzipFile: stack = java.io.EOFException: Unexpected end of ZLIB input stre
	at net.lingala.zip4j.io.inputstream.InflaterInputStream.fill(InflaterInputStream.java:68)
	at net.lingala.zip4j.io.inputstream.InflaterInputStream.read(InflaterInputStream.java:47)
	at net.lingala.zip4j.io.inputstream.ZipInputStream.read(ZipInputStream.java:155)
	at net.lingala.zip4j.io.inputstream.ZipInputStream.read(ZipInputStream.java:127)
	at net.lingala.zip4j.tasks.AbstractExtractFileTask.unzipFile(AbstractExtractFileTask.java:70)
	at net.lingala.zip4j.tasks.AbstractExtractFileTask.extractFile(AbstractExtractFileTask.java:62)
	at net.lingala.zip4j.tasks.ExtractAllFilesTask.executeTask(ExtractAllFilesTask.java:36)
	at net.lingala.zip4j.tasks.ExtractAllFilesTask.executeTask(ExtractAllFilesTask.java:13)
	at net.lingala.zip4j.tasks.AsyncZipTask.performTaskWithErrorHandling(AsyncZipTask.java:53)
	at net.lingala.zip4j.tasks.AsyncZipTask.access$100(AsyncZipTask.java:9)
	at net.lingala.zip4j.tasks.AsyncZipTask$1.run(AsyncZipTask.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)
unZipFile: percentDone = 14,isCancelled=false
onBookContentDownloadResult. resultCode = RESULT_SUCCESS, notifyItemChanged = 5
onBindViewHolder: (4)gradePlusVolume = 上,downloadStatus=STATUS_MISSION_COMPLETE,progress=100,b

**Comment by xiao-mao-lv** [comment]
Today I found some law of this question .
if I run your code in Java Project,  no  problem 
if I run your code in Android Project，Android 8.1,  no  problem 
but if I run your code in Android Project，and Android 4.4 API 19，you will find some files miss，follow is my code and error log

- my code
```
                try {
                    Log.e(TAG, "unzip: start" );
                    String zipFilePath = Environment.getExternalStorageDirectory().getAbsolutePath()+"/06b5bb815ad5476b88a2c32273b0c48a.zip";
                    String destDir = Environment.getExternalStorageDirectory().getAbsolutePath()+"/unzip";
                    String password = "f06be35461cb4b25821448373499471b";

                    ZipFile zipFile = new ZipFile(zipFilePath);
                    if (!zipFile.isValidZipFile()) {
                        Log.e(TAG, "run: 111" );
                    }
                    zipFile.setFileNameCharset("UTF-8");
                    File destDirFile = new File(destDir);
                    if (!destDirFile.exists() && !destDirFile.mkdirs()) {
                        Log.e(TAG, "run: 2222" );
                    }
                    if (zipFile.isEncrypted()) {
                        zipFile.setPassword(password);
                    }
                    //设置在主线程中解压文件
                    zipFile.setRunInThread(false);
                    zipFile.extractAll(destDir);
                    if (false) {
                        new File(zipFilePath).delete();
                    }
                    Log.e(TAG, "run: end" );
                } catch (ZipException e) {
                    e.printStackTrace();
                    Log.e(TAG, "run: 333" );
                }
```

- error log

```
11-15 16:35:39.771 2519-2616/com.toycloud.zipdemo W/System.err: net.lingala.zip4j.exception.ZipException: net.lingala.zip4j.exception.ZipException: invalid CRC for file: words_2268219.mp3 - Wrong Password?
11-15 16:35:39.771 2519-2616/com.toycloud.zipdemo W/System.err:     at net.lingala.zip4j.unzip.Unzip.initExtractFile(Unzip.java:163)
11-15 16:35:39.781 2519-2616/com.toycloud.zipdemo W/System.err:     at net.lingala.zip4j.unzip.Unzip.initExtractAll(Unzip.java:83)
11-15 16:35:39.781 2519-2616/com.toycloud.zipdemo W/System.err:     at net.lingala.zip4j.unzip.Unzip.extractAll(Unzip.java:73)
11-15 16:35:39.781 2519-2616/com.toycloud.zipdemo W/System.err:     at net.lingala.zip4j.core.ZipFile.extractAll(ZipFile.java:488)
11-15 16:35:39.781 2519-2616/com.toycloud.zipdemo W/System.err:     at net.lingala.zip4j.core.ZipFile.extractAll(ZipFile.java:451)
11-15 16:35:39.781 2519-2616/com.toycloud.zipdemo W/System.err:     at com.toycloud.zipdemo.MainActivity$1.run(MainActivity.java:74)
11-15 16:35:39.781 2519-2616/com.toycloud.zipdemo W/System.err:     at java.lang.Thread.run(Thread.java:841)
11-15 16:35:39.781 2519-2616/com.toycloud.zipdemo W/System.err: Caused by: net.lingala.zip4j.exception.ZipException: invalid CRC for file: words_2268219.mp3 - Wrong Password?
11-15 16:35:39.781 2519-2616/com.toycloud.zipdemo W/System.err:     at net.lingala.zip4j.unzip.UnzipEngine.closeStreams(UnzipEngine.java:481)
11-15 16:35:39.781 2519-2616/com.toycloud.zipdemo W/System.err:     at net.lingala.zip4j.unzip.UnzipEngine.unzipFile(UnzipEngine.java:100)
11-15 16:35:39.781 2519-2616/com.toycloud.zipdemo W/System.err:     at net.lingala.zip4j.unzip.Unzip.initExtractFile(Unzip.java:160)
11-15 16:35:39.781 2519-2616/com.toycloud.zipdemo W/System.err: 	... 6 more
```

**Comment by srikanth-lingala** [comment]
Can you try with zip4j version 2.2.2 (and not the latest v 2.2.4) and see if you still have this issue? There was a fix done in 2.2.3 which may have an impact on this. I doubt that there will be a different behaviour but just to see if that leads us somewhere. I have the feeling that this particular version of android is returning EOF in some cases. If that is the case there is nothing much zip4j can do. But would be interesting to know if 2.2.2 has a different behaviour.

**Comment by xiao-mao-lv** [comment]
2.2.2 have the same problem。
Our groups find some problem in Android 4.4 java.util.zip.Inflater.inflateBytes()，try to update it from Android 7.1.
Anyway, thank for your help

**Comment by xiao-mao-lv** [comment]
My Colleague replace Inflater.java in java.util.zip.Inflater，and solve this problem。
```
package net.lingala.zip4j.io.inputstream;

import java.io.EOFException;
import java.io.IOException;
import java.io.PushbackInputStream;
import java.util.zip.DataFormatException;
//import java.util.zip.Inflater;
import com.toycloud.zlib.Inflater;

public class InflaterInputStream extends DecompressedInputStream {
...
}
```

**Comment by xiao-mao-lv** [comment]
```
import java.util.zip.DataFormatException;

public class Inflater {
    private final ZStreamRef zsRef;
    private byte[] buf;
    private int off;
    private int len;
    private boolean finished;
    private boolean needDict;
    private long bytesRead;
    private long bytesWritten;
    private static final byte[] defaultBuf = new byte[0];

    public static native long init(boolean var0);

    public static native void setDictionary(long var0, byte[] var2, int var3, int var4);

    public native int inflateBytes(long var1, byte[] var3, int var4, int var5) throws DataFormatException;

    public static native int getAdler(long var0);

    public static native void reset(long var0);

    public static native void end(long var0);

    public Inflater(boolean nowrap) {
        this.buf = defaultBuf;
        this.zsRef = new ZStreamRef(init(nowrap));
    }

    public Inflater() {
        this(false);
    }

    public void setInput(byte[] b, int off, int len) {
        if (b == null) {
            throw new NullPointerException();
        } else if (off >= 0 && len >= 0 && off <= b.length - len) {
            synchronized(this.zsRef) {
                this.buf = b;
                this.off = off;
                this.len = len;
            }
        } else {
            throw new ArrayIndexOutOfBoundsException();
        }
    }

    public void setInput(byte[] b) {
        this.setInput(b, 0, b.length);
    }

    public void setDictionary(byte[] b, int off, int len) {
        if (b == null) {
            throw new NullPointerException();
        } else if (off >= 0 && len >= 0 && off <= b.length - len) {
            synchronized(this.zsRef) {
                this.ensureOpen();
                setDictionary(this.zsRef.address(), b, off, len);
                this.needDict = false;
            }
        } else {
            throw new ArrayIndexOutOfBoundsException();
        }
    }

    public void setDictionary(byte[] b) {
        this.setDictionary(b, 0, b.length);
    }

    public int getRemaining() {
        synchronized(this.zsRef) {
            return this.len;
        }
    }

    public boolean needsInput() {
        synchronized(this.zsRef) {
            return this.len <= 0;
        }
    }

    public boolean needsDictionary() {
        synchronized(this.zsRef) {
            return this.needDict;
        }
    }

    public boolean finished() {
        synchronized(this.zsRef) {
            return this.finished;
        }
    }

    public int inflate(byte[] b, int off, int len) throws DataFormatException {
        if (b == null) {
            throw new NullPointerException();
        } else if (off >= 0 && len >= 0 && off <= b.length - len) {
            synchronized(this.zsRef) {
                this.ensureOpen();
                int thisLen = this.len;
                int n = this.inflateBytes(this.zsRef.address(), b, off, len);
                this.bytesWritten += (long)n;
                this.bytesRead += (long)(thisLen - this.len);
                return n;
            }
        } else {
            throw new ArrayIndexOutOfBoundsException();
        }
    }

    public int inflate(byte[] b) throws DataFormatException {
        return this.inflate(b, 0, b.length);
    }

    public int getAdler() {
        synchronized(this.zsRef) {
            this.ensureOpen();
            return getAdler(this.zsRef.address());
        }
    }

    public int getTotalIn() {
        return (int)this.getBytesRead();
    }

    public long getBytesRead() {
        synchronized(this.zsRef) {
            this.ensureOpen();
            return this.bytesRead;
        }
    }

    public int getTotalOut() {
        return (int)this.getBytesWritten();
    }

    public long getBytesWritten() {
        synchronized(this.zsRef) {
            this.ensureOpen();
            return this.bytesWritten;
        }
    }

    public void reset() {
        synchronized(this.zsRef) {
            this.ensureOpen();
            reset(this.zsRef.address());
            this.buf = defaultBuf;
            this.finished = false;
            this.needDict = false;
            this.off = this.len = 0;
            this.bytesRead = this.bytesWritten = 0L;
        }
    }

    public void end() {
        synchronized(this.zsRef) {
            long addr = this.zsRef.address();
            this.zsRef.clear();
            if (addr != 0L) {
                end(addr);
                this.buf = null;
            }

        }
    }

    protected void finalize() {
        this.end();
    }

    private void ensureOpen() {
        assert Thread.holdsLock(this.zsRef);

        if (this.zsRef.address() == 0L) {
            throw new IllegalStateException("Inflater has been closed");
        }
    }

    boolean ended() {
        synchronized(this.zsRef) {
            return this.zsRef.address() == 0L;
        }
    }

    static {
        System.loadLibrary("tczip");
    }
}
```

**Comment by bengele** [comment]
> ```
> import java.util.zip.DataFormatException;
> 
> public class Inflater {
>     private final ZStreamRef zsRef;
>     private byte[] buf;
>     private int off;
>     private int len;
>     private boolean finished;
>     private boolean needDict;
>     private long bytesRead;
>     private long bytesWritten;
>     private static final byte[] defaultBuf = new byte[0];
> 
>     public static native long init(boolean var0);
> 
>     public static native void setDictionary(long var0, byte[] var2, int var3, int var4);
> 
>     public native int inflateBytes(long var1, byte[] var3, int var4, int var5) throws DataFormatException;
> 
>     public static native int getAdler(long var0);
> 
>     public static native void reset(long var0);
> 
>     public static native void end(long var0);
> 
>     public Inflater(boolean nowrap) {
>         this.buf = defaultBuf;
>         this.zsRef = new ZStreamRef(init(nowrap));
>     }
> 
>     public Inflater() {
>         this(false);
>     }
> 
>     public void setInput(byte[] b, int off, int len) {
>         if (b == null) {
>             throw new NullPointerException();
>         } else if (off >= 0 && len >= 0 && off <= b.length - len) {
>             synchronized(this.zsRef) {
>                 this.buf = b;
>                 this.off = off;
>                 this.len = len;
>             }
>         } else {
>             throw new ArrayIndexOutOfBoundsException();
>         }
>     }
> 
>     public void setInput(byte[] b) {
>         this.setInput(b, 0, b.length);
>     }
> 
>     public void setDictionary(byte[] b, int off, int len) {
>         if (b == null) {
>             throw new NullPointerException();
>         } else if (off >= 0 && len >= 0 && off <= b.length - len) {
>             synchronized(this.zsRef) {
>                 this.ensureOpen();
>                 setDictionary(this.zsRef.address(), b, off, len);
>                 this.needDict = false;
>             }
>         } else {
>             throw new ArrayIndexOutOfBoundsException();
>         }
>     }
> 
>     public void setDictionary(byte[] b) {
>         this.setDictionary(b, 0, b.length);
>     }
> 
>     public int getRemaining() {
>         synchronized(this.zsRef) {
>             return this.len;
>         }
>     }
> 
>     public boolean needsInput() {
>         synchronized(this.zsRef) {
>             return this.len <= 0;
>         }
>     }
> 
>     public boolean needsDictionary() {
>         synchronized(this.zsRef) {
>             return this.needDict;
>         }
>     }
> 
>     public boolean finished() {
>         synchronized(this.zsRef) {
>             return this.finished;
>         }
>     }
> 
>     public int inflate(byte[] b, int off, int len) throws DataFormatException {
>         if (b == null) {
>             throw new NullPointerException();
>         } else if (off >= 0 && len >= 0 && off <= b.length - len) {
>             synchronized(this.zsRef) {
>                 this.ensureOpen();
>                 int thisLen = this.len;
>                 int n = this.inflateBytes(this.zsRef.address(), b, off, len);
>                 this.bytesWritten += (long)n;
>                 this.bytesRead += (long)(thisLen - this.len);
>                 return n;
>             }
>         } else {
>             throw new ArrayIndexOutOfBoundsException();
>         }
>     }
> 
>     public int inflate(byte[] b) throws DataFormatException {
>         return this.inflate(b, 0, b.length);
>     }
> 
>     public int getAdler() {
>         synchronized(this.zsRef) {
>             this.ensureOpen();
>             return getAdler(this.zsRef.address());
>         }
>     }
> 
>     public int getTotalIn() {
>         return (int)this.getBytesRead();
>     }
> 
>     public long getBytesRead() {
>         synchronized(this.zsRef) {
>             this.ensureOpen();
>             return this.bytesRead;
>         }
>     }
> 
>     public int getTotalOut() {
>         return (int)this.getBytesWritten();
>     }
> 
>     public long getBytesWritten() {
>         synchronized(this.zsRef) {
>             this.ensureOpen();
>             return this.bytesWritten;
>         }
>     }
> 
>     public void reset() {
>         synchronized(this.zsRef) {
>             this.ensureOpen();
>             reset(this.zsRef.address());
>             this.buf = defaultBuf;
>             this.finished = false;
>             this.needDict = false;
>             this.off = this.len = 0;
>             this.bytesRead = this.bytesWritten = 0L;
>         }
>     }
> 
>     public void end() {
>         synchronized(this.zsRef) {
>             long addr = this.zsRef.address();
>             this.zsRef.clear();
>             if (addr != 0L) {
>                 end(addr);
>                 this.buf = null;
>             }
> 
>         }
>     }
> 
>     protected void finalize() {
>         this.end();
>     }
> 
>     private void ensureOpen() {
>         assert Thread.holdsLock(this.zsRef);
> 
>         if (this.zsRef.address() == 0L) {
>             throw new IllegalStateException("Inflater has been closed");
>         }
>     }
> 
>     boolean ended() {
>         synchronized(this.zsRef) {
>             return this.zsRef.address() == 0L;
>         }
>     }
> 
>     static {
>         System.loadLibrary("tczip");
>     }
> }
> ```

System.loadLibrary("tczip");这个库哪里有？
