### ISSUE TITLE
zip4j can't work on android 4.4

### ISSUE THREAD

**Issue by hhdsyxwei** [srikanth-lingala/zip4j#106]
In the process of inflating, zlib(java.util.zip) needs more data, but file has no more data.
When the zip4j calls fill, eof exception is thrown out.

  @Override
  public int read(byte[] b, int off, int len) throws IOException {
    try {
      int n;
      while ((n = inflater.inflate(b, off, len)) == 0) {
        if (inflater.finished() || inflater.needsDictionary()) {
          return -1;
        }
        if (inflater.needsInput()) {
          fill();// program crashed here
        }
      }
      return n;
    } catch (DataFormatException e) {
      throw new IOException(e);
    }
  }

**Comment by srikanth-lingala** [comment]
There is nothing much zip4j can do, if the underlying stream is returning -1 (EOF) when trying to read.  I am not an Android expert, you have to look into why the underlying stream is returning -1 when trying to read on this version of Android. Zip4j works perfectly fine on other versions of Android. Maybe there is an issue with this specific version of Android. As I said, as long as the stream returns -1, there is nothing much zip4j can do than to throw an exception.
