### ISSUE TITLE
java.io.EOFException: Unexpected end of ZLIB input stream

### ISSUE THREAD

**Issue by nbabaka** [srikanth-lingala/zip4j#108]
Hi there 

Got this exception with ZIP files created in macos. Successful unzip it in android shell without any errors.

```
W/System.err: net.lingala.zip4j.exception.ZipException: java.io.EOFException: Unexpected end of ZLIB input stream
W/System.err: Caused by: java.io.EOFException: Unexpected end of ZLIB input stream
W/System.err:     at 
W/System.err:     at net.lingala.zip4j.tasks.AsyncZipTask.execute(AsyncZipTask.java:36)
W/System.err:     at net.lingala.zip4j.ZipFile.extractAll(ZipFile.java:437)
```

**Comment by srikanth-lingala** [comment]
Do you get this issue on an Android? If yes, can you specify which version you of Android you see this issue on? There were some previous issues reported on Android version 4.4, which had something to do with an issue on that version of Android.

**Comment by nbabaka** [comment]
Yes, Android 6.0
I created used old method for unzip it and it works -

`    @Throws(IOException::class)
    fun unzip(zipFile: File, targetDirectory: File) {
        val zis = ZipInputStream(BufferedInputStream(FileInputStream(zipFile)))
        try {
            var ze: ZipEntry?
            var count: Int
            val buffer = ByteArray(8192)
            while (true) {
                ze = zis.nextEntry
                if (ze == null) break

                val file = File(targetDirectory, ze.name)
                val dir = if (ze.isDirectory) file else file.parentFile
                if (!dir.isDirectory && !dir.mkdirs())
                    throw FileNotFoundException("Failed to ensure directory: " + dir.absolutePath)
                if (ze.isDirectory)
                    continue
                val fout = FileOutputStream(file)
                fout.use { fout ->
                    while (true) {
                        count = zis.read(buffer)
                        if (count == -1) break
                        fout.write(buffer, 0, count)
                    }
                }
            }
        } finally {
            zis.close()
        }
    }`

**Comment by srikanth-lingala** [comment]
Can you send me a sample zip file?

**Comment by srikanth-lingala** [comment]
Also please post the code you used. I am not an Android guy, I hope I can figure out a way to reproduce the, especially that you say that it works fine in Android shell.

**Comment by srikanth-lingala** [comment]
Can you try with the latest v2.2.6? There is a bug fix done which might be related to this issue.

**Comment by srikanth-lingala** [comment]
Closing issue as there is no further feedback on this.
