### ISSUE TITLE
Zip reading performance issue

### ISSUE THREAD

**Issue by osterwiese** [srikanth-lingala/zip4j#112]
Hello Srikanth,

I switched from version 1.3.2 to 2.2.4 and have a noticeable slowdown in performance.
The test was with a rather big zip-file of 985MB (not encrypted). 
An operation that is reading lots of files of this zip was taking ~3 minutes with version 1.3.2.
With Version 2.2.4 the same operation takes ~330 minutes.
Thats over 100 times slower than before and machtes with the reading speed I noticed with Windows resource monitor:
1.3.2 : ~525.000 B/s
2.2.4 : ~1.900 B/s

Did you already regognize this and/or are there possibilities to speed up again? 
Otherwise I have to revert back to 1.3.x
Thanks and regards, Peter

**Comment by srikanth-lingala** [comment]
Hi Peter, 

This definitely sounds quite strange. There should be not have been a performance impact compared to the old version. If anything it should have gotten better. I will investigate and update the thread. When you say `lots of files of this zip`, how many files are approximately in the zip file?

**Comment by osterwiese** [comment]
Hi Srikanth,
thanks again for your quick reply. 
The zip file contains 28479 files in two folders.
Regards, Peter

**Comment by srikanth-lingala** [comment]
And what was the total size of the zip file?

**Comment by osterwiese** [comment]
985 MB

**Comment by srikanth-lingala** [comment]
To reproduce this issue, I tested with this scenario: 

~ 900MB zip file (unencrypted) containing 28479 files all in a single folder, and each file of uncompressed (before zipping) size ~ 35kb.

I tested on a mac. To extract the file, it took ~ 27 seconds with v2.2.6 and took ~ 19 seconds with v1.3.2. Although it is not a 10x difference that you have seen, it is still a considerable difference, and I presume the difference between your and my results are because of hardware configuration, and probably also the OS. 

I think I know the reason for this behaviour. I did a fix. After that v2.2.7-SNAPSHOT takes ~ 20 seconds, which is pretty much close to the v1.3.2. Can you please try with v2.2.7-SNAPSHOT? I would like to see the results from your side as well before I do further investigations.

If you have trouble accessing this snapshot version with your default maven settings, add the following to your `distributionManagement`:

```
<distributionManagement>
    <snapshotRepository>
        <id>ossrh</id>
        <url>https://oss.sonatype.org/content/repositories/snapshots</url>
    </snapshotRepository>
</distributionManagement>
```

**Comment by osterwiese** [comment]
Hi Srikanth,
sounds good, but unfortunately I cannot acces v2.2.7-SNAPSHOT, even with the settings in the distributionManagement. Did you push? I can't see any commit the last days.
Regards, Peter

**Comment by srikanth-lingala** [comment]
Hi Peter,

That is strange. You can see the [snapshot here](https://oss.sonatype.org/content/repositories/snapshots/net/lingala/zip4j/zip4j/2.2.7-SNAPSHOT/). I pushed it from my local machine and not from github. I did the same process in the past and users were able to get it (with other versions though). Where did you configure that `snapshotRepository`? In your pom or in your maven settings?

**Comment by srikanth-lingala** [comment]
BTW, it is probably obvious, but just to be clear, the version is `2.2.7-SNAPSHOT` and not with the "v" in front.

**Comment by osterwiese** [comment]
Hi, yes I did not use the "v" 😉. I had a conflict due to my configuration in settings.xml, not I was able to build the application with your snapshot. I'll do a test sonn and keep you informed. Thanks a lot, Peter

**Comment by osterwiese** [comment]
Hi Srikanth,
sorry for the late reply, but the tests took a while.
2.2.7-SNAPSHOT is faster, but still far awar from 1.3.2.
The time is now down from 330 minutes to ~229 minutes.

I enriched the code with log messages and attached both logs, 1.3.2 and 2.2.7. 
Obviously "getFileHeader" needs a lot more time:
File: {89863fc2-3306-11dd-bd11-0800200c9a66}.json (size: 148KB)
getFileHeader 1.3.2:        3 ms 
getFileHeader 2.2.7:  1168 ms

Thanks and regards, Peter
[zip4j-1.3.2.zip](https://github.com/srikanth-lingala/zip4j/files/3909958/zip4j-1.3.2.zip)
[zip4j-2.2.7.zip](https://github.com/srikanth-lingala/zip4j/files/3909959/zip4j-2.2.7.zip)

**Comment by srikanth-lingala** [comment]
Thanks for the info Peter. I will have a look into it and update the thread.

**Comment by srikanth-lingala** [comment]
Hi Peter,

Thanks again for the logs. This has greatly helped me in my investigation. I was looking at the wrong place all the while, but the logs helped me find the issue. I think this version should have much better performance. Can you please try with `2.2.7.1-SNAPSHOT` and let me know the results?

Thanks
Srikanth

**Comment by osterwiese** [comment]
Hi Srikanth,
great job, it is incredibly fast again, as fast as 1.3.2!
But...  
AES-256 decryption does not work any more with 2.2.7.1-SNAPSHOT, with 2.2.7-SNAPSHOT ist worked. 😉 

Thanks, Peter

**Comment by markgbrown** [comment]
Not sure if this is related or not, but we found a large performance boost by slightly modifying ZipFile.extractFile() methods. We changed the code to do a conditional around readZipInfo() as follows:

`if (zipModel == null) {
  readZipInfo();
}`

Hope this helps the investigation.

**Comment by srikanth-lingala** [comment]
@markgbrown Yes, that was the fix I did in the snapshot which worked. And also, I increased the buffer size from 512 bytes to 4kb, which will result in less i/o ops.

**Comment by srikanth-lingala** [comment]
@osterwiese Aes encryption works perfectly fine for me. Can you please post the code you used? Here is the code I tested with:

```
@Test
public void testAesEncryptedZipFile() throws IOException {
  ZipParameters zipParameters = new ZipParameters();
  zipParameters.setEncryptFiles(true);
  zipParameters.setEncryptionMethod(EncryptionMethod.AES);
  zipParameters.setAesKeyStrength(AesKeyStrength.KEY_STRENGTH_256);

  ZipFile zipFile = new ZipFile(BASE_DIR + "aes.zip", "password".toCharArray());
  zipFile.addFile(BASE_DIR + "TEST_FILE_9999.txt", zipParameters);

  File extractDir = new File(BASE_DIR + "extracted/");
  if (!extractDir.exists()) {
    extractDir.mkdirs();
  }

  zipFile = new ZipFile(BASE_DIR + "aes.zip", "password".toCharArray());
  zipFile.extractAll(extractDir.getPath());
}
```

Please note that windows zip tool has trouble extracting aes encrypted zip files. A brief explanation of this is described in the issue [here][1]. If you have used Windows zip tool to test it, please test it with some other tool. I tested the zip file generated with zip4j, with several other tools (including extracting with zip4j) and it worked fine each time.

[1]: https://github.com/srikanth-lingala/zip4j/issues/113#issuecomment-560584399

**Comment by osterwiese** [comment]
Hi Srikanth,  thanks again. 
Well, I believe that i can decrypt a AES zip file that I encrypted with zip4j before. I think the problem is (as you mentioned before) the compatibility. I have a Windows based application (Delphi code) that encrypts and my java application has to decrypt. This worked fine with 2.2.7, but not with 2.2.7.1. Same behaviour, if I create an ecrypted zip with 7zip. I do not use Windows zip tool. 

Here is the snippet, as you see, not much magic in it.
Method readExplicitlyExported now throws an IOException at getInputStream. The file content.json is AES 256 encrypted.

`  
public void readZip(final String source, final char[] password) throws IOException {

    logger.info("Reading zip file: " + source);

    zipFile = new ZipFile(source);

    if (zipFile.isEncrypted()) {
      zipFile.setPassword(password);
    }

    List<FileHeader> fileHeaders = zipFile.getFileHeaders();

    readExplicitlyExported(zipFile);  

    addProjectProcessesToExplicitlyExported(zipFile);

    for (FileHeader fileHeader : fileHeaders) {
      if (shallExtract(fileHeader)) {
        InputStream inputStream = zipFile.getInputStream(fileHeader);
        try {
          if (fileHeader.getFileName().startsWith("files/")) {
            fileNames.add(FilenameUtils.getName(fileHeader.getFileName()));
          } else {
			// deleted code --> confidential :-)
          }
        } catch (IOException e) {
          logger.info(LogLabels.ERROR_COULD_NOT_READ_INPUT_STREAM, fileHeader.getFileName());
          throw new IOException(MessageFormatter.format(LogLabels.ERROR_COULD_NOT_READ_INPUT_STREAM, fileHeader.getFileName()).toString());
        } finally {
          if (inputStream != null) {
            IOUtils.closeQuietly(inputStream);
          }
        }
      }

    }
  }


  private void readExplicitlyExported(final ZipFile zipFile) throws IOException {
    try {
      FileHeader contentJson = zipFile.getFileHeader(Constants.FILENAME_CONTENT_JSON); // Content.json
      ZipInputStream contentJsonStream = zipFile.getInputStream(contentJson);  // --> IOException

 	  // deleted code --> confidential :-)

    } catch (IOException e) {
      logger.info(LogLabels.ERROR_COULD_NOT_READ, Constants.FILENAME_CONTENT_JSON);
      throw new IOException(MessageFormatter.format(LogLabels.ERROR_COULD_NOT_READ, Constants.FILENAME_CONTENT_JSON).toString());
    }

  }
`

Regards, Peter

**Comment by osterwiese** [comment]
Hi Srikanth,
as promised my test result:
2.2.7.1 is comparable fast as 1.3.2
The unencrypted zip is now down from ~225 min (2.2.7) to ~2,5 min (2.2.7.1). 
1.3.2 did it in ~2,25 min, but this can be normal fluctuations regarding the machine load.
And AES works (!!), of course it slows down a bit, but with 5,75 min still very good.
Thank you very much for your great support! 

Regards, Peter

**Comment by srikanth-lingala** [comment]
v2.2.7 released with the fix. It might take a few hours until the artefact is synced to maven central.

**Comment by srikanth-lingala** [comment]
> Thank you very much for your great support!

No problem Peter. Thank you for your support as well. Let me know if you have any further feedback or face any further issues with zip4j.

Regards
Srikanth
