### ISSUE TITLE
chinese comment error

### ISSUE THREAD

**Issue by strivezsh** [srikanth-lingala/zip4j#114]
zipFile.setComment("测试中文");
result:娴嬭瘯涓枃澶囨敞

net/lingala/zip4j/headers/HeaderWriter.java 599line
byte[] commentBytes = comment.getBytes(InternalZipConstants.CHARSET_UTF_8);
change
byte[] commentBytes = comment.getBytes("GBK");

Need to add configuration comment charset

**Comment by srikanth-lingala** [comment]
Issue fixed. Will include the fix in the next release.

**Comment by strivezsh** [comment]
ok thanks

**Comment by srikanth-lingala** [comment]
Reopening the issue. I will close the issue after I make a release. It will help me keep track of the issues in a release.

**Comment by srikanth-lingala** [comment]
v2.2.7 released with the fix. It might take a few hours until the artefact is synced to maven central.
