### ISSUE TITLE
How to add comments when I use ZipOutputStream?

### ISSUE THREAD

**Issue by beibm** [srikanth-lingala/zip4j#119]
in the example:

```
ZipParameters zipParameters = new ZipParameters();
zipParameters.setCompressionMethod(CompressionMethod.DEFLATE);
zipParameters.setFileNameInZip("aaa.txt");
zos.putNextEntry(zipParameters);

FileOutputStream fos = new FileOutputStream(outputZipFile);
ZipOutputStream zos = new ZipOutputStream(fos);
try(InputStream inputStream = new FileInputStream(fileToAdd)) {
  while ((readLen = inputStream.read(buff)) != -1) {
    zos.write(buff, 0, readLen);
  }
}

zos.closeEntry();
zos.flush();
zos.close();
```

I can not found how to add comments! please help me!

**Comment by srikanth-lingala** [comment]
Unfortunately, it is not possible to add comments when using ZipOutputStream.

**Comment by srikanth-lingala** [comment]
It is currently only possible to achieve that with `ZipFile` api

**Comment by beibm** [comment]
Is there any plan to add this as new-feature?

**Comment by srikanth-lingala** [comment]
I have to analyse this. There are two ways to write comments in a zip file. One comment is stored at each entry level, and other comment can be stored for the complete zip file. I have to see if it is possible to achieve them both or any one of them.

**Comment by beibm** [comment]
> I have to analyse this. There are two ways to write comments in a zip file. One comment is stored at each entry level, and other comment can be stored for the complete zip file. I have to see if it is possible to achieve them both or any one of them.

Glad to hear your reply! thanks

**Comment by srikanth-lingala** [comment]
Feature added in v2.3.0 released today.

There are two ways to add comment in a zip file. You can add comment for each entry in a zip file. You can achieve this with the below code:

```
ZipOutputStream zipOutputStream = new ZipOutputStream(...);
...
ZipParameters zipParameters = new ZipParameters();
zipParameters.setFileComment("file_comment");
zipOutputStream.putNextEntry(zipParameters);
...
```

And the second way to add a comment, is to set a comment at the zip outputstream level. This comment is then not for each entry, but for the zip archive as a whole. You can now achieve this with:

```
ZipOutputStream zipOutputStream = new ZipOutputStream(...);
...
zipOutputStream.setComment("some_comment");
...
```

Please note that the above code samples are only the relevant snippets. For a complete example of ZipOutputStream, please refer to the README.

**Comment by Allanksr** [comment]
Very good, in the second way it was possible to insert comments in ZipOutputStream.
Like this

     val zipOutputStream = ZipOutputStream(fos, password.toCharArray(), StandardCharsets.UTF_8)
      zipOutputStream.setComment("Open this file with X app \n" +
      "https://play.google.com/store/apps/details?id=x.example")
        zipOutputStream.use {
              //continue the work
        }
