### ISSUE TITLE
 How do I read a zip file and return it as a stream without printing it to disk？

### ISSUE THREAD

**Issue by AA99777** [srikanth-lingala/zip4j#121]
// I copied a zipfile, put a file to the copefile , and output the modified zipfile as stream.
// I finally deleted the modified file.
// How do I read a zip file and return it as a stream without printing it to disk？

```
File file = new File(filePath);
File copyFile = new File(copyPath + ".zip");
Files.copy(file.toPath(), copyFile.toPath(), StandardCopyOption.REPLACE_EXISTING);
InputStream input = null;
try {
  ZipFile zipFile = new ZipFile(copyFile);
  zipFile.setFileNameCharset(String.valueOf(StandardCharsets.UTF_8));
  ZipParameters parameters = new ZipParameters();
  parameters.setCompressionMethod(Zip4jConstants.COMP_DEFLATE);
  parameters.setFileNameInZip("info.json");
  parameters.setSourceExternalStream(true);
  byte[] bytes = objectMapper.writeValueAsBytes(object);
  input = new ByteArrayInputStream(bytes);
  zipFile.addStream(input, parameters);
} catch (Exception e) {
  e.printStackTrace();
} finally {
  if (input != null) {
    try {
      input.close();
    } catch (IOException e) {
      e.printStackTrace();
    }
  }
}

try (InputStream inputStream = new FileInputStream(copyFile);
        OutputStream outputStream = response.getOutputStream()) {
  response.setContentType("application/x-download");
  response.addHeader("Content-Disposition", "attachment;filename=" + URLEncoder.encode(templetName, "UTF-8") + ".zip");
  IOUtils.copy(inputStream, outputStream);
  outputStream.flush();
} catch (IOException e) {
  e.printStackTrace();
}

copyFile.delete();
```

**Comment by srikanth-lingala** [comment]
To work with zip files and streams, you have to use [ZipInputStream][1]. From your example, it looks like you are using v1.x of zip4j. I would recommend you to use v2.x of zip4j which has better support for streams. There are examples in README.

[1]: https://github.com/srikanth-lingala/zip4j/blob/master/src/main/java/net/lingala/zip4j/io/inputstream/ZipInputStream.java

**Comment by AA99777** [comment]
Can ZIP4J compress multiple files into an outputstream instead of generating disk files?

**Comment by srikanth-lingala** [comment]
Yes, it can. You can find the sample code under the section `Adding entries with ZipOutputStream` in [README][1]

[1]: https://github.com/srikanth-lingala/zip4j/blob/master/README.md
