### ISSUE TITLE
After the compression is completed, use the decompression software to open the two-layer directory.

### ISSUE THREAD

**Issue by lovemengmeng** [srikanth-lingala/zip4j#128]
When we use the latest version，use addFloder method,but result Not what we expected，we use the decompression software to open zip show two-layer directory.

**Comment by srikanth-lingala** [comment]
Can you share a sample zip file please? Also your code and the exact version of zip4j you are using will be helpful. Thanks.

**Comment by srikanth-lingala** [comment]
Another question: which tool do you use for decompression? It might also be a bug with the decompression software. I was not able to reproduce this on my machine. That is why it would be good to have a sample zip file from you, your code.

**Comment by genglong2019** [comment]
When we use the 2.1.0 version，use addFloder method,but result Not what we expected in linux，it is good inwindows. we use the decompression software to open zip show two-layer directory.

**Comment by genglong2019** [comment]
Hi,When we use the 2.2.4 version,It is normal

**Comment by srikanth-lingala** [comment]
Please consider using the latest version 2.3.1, which has some more bug fixes.

**Comment by lovemengmeng** [comment]
It's really because the decompression tool is too old,thanks for your help
