### ISSUE TITLE
Play store give me warning of Fixing a Zip Path Traversal Vulnerability In Android

### ISSUE THREAD

**Issue by attaullahpro** [srikanth-lingala/zip4j#134]
Hi Dear! Recently I used your code for unzipping file to app folder and app is published on play store, play store give me warring of "Fixing a Zip Path Traversal Vulnerability In Android"
https://support.google.com/faqs/answer/9294009

**Comment by srikanth-lingala** [comment]
This is a duplicate of #133. I will close this issue and will update #133. Please follow the other issue for updates.
