### ISSUE TITLE
about create executor using our own ThreadFactory

### ISSUE THREAD

**Issue by Skyfy16** [srikanth-lingala/zip4j#136]
Hi, I'm back on my project using your java library "zip4j". I had made a request for a similar feature in issue 80, but I had explained myself badly.
this is the code of the actual AsyncZipTask.java
![AsyncZipTaskExecuteMethod_Actual](https://user-images.githubusercontent.com/51704546/73131362-f8b95400-4009-11ea-9b78-f2aa4b4f038b.PNG)

To do what I needed to do, I had to modify this method execute to that.
![AsyncZipTaskExecuteMethod_ModifiedByMyself](https://user-images.githubusercontent.com/51704546/73131361-f8b95400-4009-11ea-88cf-4557b9e26234.PNG)

 It would be nice to be able to create custom ThreadFactory.

**Comment by srikanth-lingala** [comment]
Yes, I remember your other issue. If I remember correctly, I closed it as there was no further feedback on that issue. Sure, I will look into passing in a ThreadFactory from the ZipFile api (something like `ZipFile.setThreadFactory(ThreadFactory)`. I will analyse it and update the thread.

**Comment by srikanth-lingala** [comment]
Feature included in v2.4.0 released today
