### ISSUE TITLE
How to create zipfile without save in local

### ISSUE THREAD

**Issue by sunwenjieIT** [srikanth-lingala/zip4j#140]
I just want create zipfile and upload in Cloud. Dont want save locally.

**Comment by srikanth-lingala** [comment]
You can create InMemory zip file without saving it to local. You can use `ByteArrayOutputStream` and pass it to `ZipOutputStream`. Then you can use this outputstream to write to your cloud. There is an example usage of `ZipOutputStream` in [ReadMe][1] under the section `Adding entries with ZipOutputStream`. Just replace `FileOutputStream` in this example with `ByteArrayOutputStream`. 

[1]: https://github.com/srikanth-lingala/zip4j/blob/master/README.md

**Comment by sunwenjieIT** [comment]
Thanks for your answer 👍
