### ISSUE TITLE
Previewing directory hierarchy 

### ISSUE THREAD

**Issue by gilshallem** [srikanth-lingala/zip4j#142]
Hi,
Awesome library!
I would like to use it to display a preview of the zip file without extracting it

I found zipFile.getFileHeaders()
But i can't figure out how to determine the parent directory of each file
it seams like FileHeader does not have a parent property.

**Comment by srikanth-lingala** [comment]
Zip4j will only give you the file name. Constructing the directory structure/mapping parent directory is not supported by zip4j. You will have to construct this yourself. You will probably have to have tree nodes and add sub nodes or an element depending on wether the entry is a directory or a file and do it recursively until you have all the entries in the zip file mapped out.

**Comment by srikanth-lingala** [comment]
You might want to look at [this][1] repo, especially [this][2] class. This was written by one of the users of zip4j. They developed it for their purpose mentioned in [this][3] issue here, so there is some special logic which fits their use case, so you might want to look at the code before you use it (that is if it is useful for your use case). The code seems to be pretty well documented, which should help.

[1]: https://github.com/joorei/zip-dir-tree/
[2]: https://github.com/joorei/zip-dir-tree/blob/master/src/main/java/joorei/zip4j/tree/TreeBuilder.java
[3]: https://github.com/srikanth-lingala/zip4j/issues/139

**Comment by gilshallem** [comment]
Thank you. I used the filename to make the tree. I would. Suggest to add, getPath() method that give the path and leave filename as just the filename to make it more clear.
