### ISSUE TITLE
Existing file not always being removed from zip when replaced by new file with same name

### ISSUE THREAD

**Issue by dayglorious** [srikanth-lingala/zip4j#144]
I've encountered an issue with replacing existing files in a zip archive. It only happens if the file I am adding is being renamed in the archive via the "renameTo" zipParameters property and replaces an existing file with the same name. While only one file gets extracted from the archive when I open it, there are two file headers, and the archive is twice the size it was before. If I add the same file again, I get the same result -- one file, three headers, archive 3x the size it was originally.

**Comment by srikanth-lingala** [comment]
I was able to reproduce this. Working on a fix.

**Comment by srikanth-lingala** [comment]
Fixed in v2.3.2 released today
