### ISSUE TITLE
ZipInputStream.read() breaks contract of InputStream.read()

### ISSUE THREAD

**Issue by pmahony893** [srikanth-lingala/zip4j#146]
The JavaDoc of `InputStream.read()` states:

> ... The value byte is returned as an int in the range `0` to `255`. ...

However, the `ZipInputStream.read()` simply returns `b[0]`, which is an integer in the range `-127` to `128` ([spec](https://docs.oracle.com/javase/tutorial/java/nutsandbolts/datatypes.html)). This needs to be converted to be in the correct range, e.g. by returning `b[0] & 0xff`.

This behaviour is causing issues with trying to use Apache Commons' `BOMInputStream`; there, it assumes that the delegate stream won't return anything negative (unless, I guess, an EOF was encountered).

**Comment by srikanth-lingala** [comment]
On it

**Comment by srikanth-lingala** [comment]
Fixed in v2.4.0 released today
