### ISSUE TITLE
Windows 10 compatibilty

### ISSUE THREAD

**Issue by bdbais** [srikanth-lingala/zip4j#147]
Good morning,
         I'm testing you great library and I created a password protected zip file with inside a csv but when I open on windows system with standard uncompress funcionality it said me it's impossible to copy the file:  Error 0x80004005 , same file with 7Zip works perfectly.
I tried to use:
Incompatibile: 
zipParameters.setEncryptFiles(true);
zipParameters.setEncryptionMethod(EncryptionMethod.AES);

Fix: 

Removed: zipParameters.setEncryptFiles(true);
changed:  zipParameters.setEncryptionMethod(EncryptionMethod.ZIP_STANDARD);

and it resolve.

by BAIS

**Comment by srikanth-lingala** [comment]
Please have a look at [my reply to a similar issue][1]. Although that reply talks of Mac, the same applies also to Windows.

[1]: https://github.com/srikanth-lingala/zip4j/issues/126#issuecomment-573826602

**Comment by srikanth-lingala** [comment]
I just also read that Windows does not support AES encrypted zip files. Closing this as it is not an issue with zip4j.

Sources:
https://superuser.com/questions/1255917/do-windows-8-1-or-10-support-aes-256-in-zip-files
https://www.winhelponline.com/blog/zip-error-0x80004005-extract-copy-unspecified-error/
https://stackoverflow.com/questions/29237022/why-cant-windows-7-extract-files-from-my-password-protected-zip-file-created-us
