### ISSUE TITLE
Zip headers not found. Probably not a zip file

### ISSUE THREAD

**Issue by mattxzhang** [srikanth-lingala/zip4j#151]
I have a zip file can be unzip in windows,but can't unzip by using zip4j or java system code,please check the exception below.

Exception in thread "main" net.lingala.zip4j.exception.ZipException: Zip headers not found. Probably not a zip file
	at net.lingala.zip4j.headers.HeaderReader.readEndOfCentralDirectoryRecord(HeaderReader.java:119)
	at net.lingala.zip4j.headers.HeaderReader.readAllHeaders(HeaderReader.java:74)
	at net.lingala.zip4j.ZipFile.readZipInfo(ZipFile.java:945)
	at net.lingala.zip4j.ZipFile.extractAll(ZipFile.java:437)
	at music.ZipTest.unZip(ZipTest.java:30)
	at music.ZipTest.main(ZipTest.java:19)

**Comment by srikanth-lingala** [comment]
Can you attach the zip file? Unfortunately, without a zip file it will be hard to tell what went wrong.

**Comment by mattxzhang** [comment]
thank you for reply. do you have personal email address,I just replied a mail with the zip file but it's been rejected because of the file size.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Srikanth Reddy Lingala"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月4日(星期三) 下午3:14
收件人:&nbsp;"srikanth-lingala/zip4j"<zip4j@noreply.github.com&gt;;
抄送:&nbsp;"1196263517"<1196263517@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [srikanth-lingala/zip4j] Zip headers not found. Probably not a zip file (#151)




Can you attach the zip file? Unfortunately, without a zip file it will be hard to tell what went wrong.

**Comment by srikanth-lingala** [comment]
Yes, please send it to srikanth.mailbox@gmail.com

**Comment by srikanth-lingala** [comment]
And also, which version of zip4j are you using?

**Comment by mattxzhang** [comment]
[test.zip](https://github.com/srikanth-lingala/zip4j/files/4285927/test.zip)
please check this file。version 2.4.0

**Comment by mattxzhang** [comment]
[testerror.zip](https://github.com/srikanth-lingala/zip4j/files/4285977/testerror.zip)
version 2.4.0

**Comment by srikanth-lingala** [comment]
That was in fact not a zip file. It was a rar file, with the file name having an extension of `.zip`. Below is the output from a tool that I got for you zip file:

```
Path = testerror.zip
Open WARNING: Can not open the file as [zip] archive
Type = Rar
```

**Comment by mattxzhang** [comment]
thank you for reply

**Comment by Lizhihzzx** [comment]
I met the same problem.But it is a zip file,and I can open and unzip it with zip method by 7zp.

**Comment by srikanth-lingala** [comment]
@Lizhihzzx Would it be possible for you to send me the zip file?

**Comment by jabran-q-khan** [comment]
I'm having the same issue, happening with multiple zip files randomly.
