### ISSUE TITLE
About compression method

### ISSUE THREAD

**Issue by Sentaroh** [srikanth-lingala/zip4j#152]
Are there any plans to add compression methods such as BZIP2, LZMA or XZ?

**Comment by srikanth-lingala** [comment]
I would love to have them in zip4j, but unfortunately I don't have enough free time now.

**Comment by Sentaroh** [comment]
Thank you.

**Comment by Zyxer22** [comment]
I would also be interested in seeing other compression methods added (specifically lzma). I understand that there isn't time at the moment, but would it make sense as a backlog item for future releases?
