### ISSUE TITLE
Reading support for specific ExtraDataRecords

### ISSUE THREAD

**Issue by joorei** [srikanth-lingala/zip4j#158]
Hello @srikanth-lingala, I wanted to ask if you would (or maybe already did) consider support for reading data from specific "extensible data fields".

To clearify: I know I can access the `ExtraDataRecord`s of a `FileHeader` with `fileHeader.getExtraDataRecords()` and then get the header ID and the actual `byte[]` data from the instances. But I did not find a way in zip4j to parse the `byte[]` data into the actual informations encoded in there.

I've implemented the parsing for the "NTFS Extra Field (0x000a)" and the "Info-ZIP Unicode Path Extra Field (0x7075)" myself in two small classes which are adjusted to my use case. But I wonder how zip4j could handle this for the user and if so how it would be integrated (below are some thoughts).

Or maybe this whole extra fields parsing is out of scope of zip4j anyway, but even then I would be interested in you opinion regarding the design.

I've gone with 6. and 8. for now but before I continue with more field types and maybe code in the wrong direction I wanted to coordinate with you in case this is something integratable.

----

1. Separate classes for each type of extra field versus a utility class?
2. Parsing integrated into `ExtraDataRecord`?
3. A separate subclass of `ExtraDataRecord` for each field type?
4. Common interface with `ExtraDataRecord`?
5. Wrapper around `ExtraDataRecord` instances?
6. Not related to `ExtraDataRecord` at all but working on `byte[]` only?
7. Mutable/immutable?
8. Lazy loaded (parsing when accessing getters) to avoid computations, instantiations and memory allocations as well as potential errors in case of invalid data for users never using the extra fields?
9. Automatic parsing when creating `FileHeader`s or leaving the parsing to the user for the reasons stated in 8.?
10. Separate getters for each supported extra field type on `FileHeader` to avoid casting for the user?
11. `FileHeader` providing a `Map<Integer,List<ExtraDataRecord>>` with the integer being the header ID?
12. …

**Comment by srikanth-lingala** [comment]
This is actually a good idea. My first impression is to have some parser utility that you can use which returns a list of parsed extra data records. The default behaviour still stays the same, i.e, zip4j returns a list of unparsed extra data records. But you can pass this list to the parser utility which will return you a list of parsed records. There are 37 extra data records that I know of. 2 of which are Zip64 and AES extra data records. These two are already implemented, so we need to implement another 35 of them. This feature will take some time to implement though.

**Comment by joorei** [comment]
I totally missed the Zip64 and AES extra data records until now. Please have a look at 575dc52 and the comments in there if it is anything like you envisioned.

**Comment by oleg-cherednik** [comment]
This is a list of most useful `ExtraRecords`:
- **0x9901** - AE-x encryption structure
- **0x0017** - Algorithm ID for strong encryption
- **0x0001** - Zip64 extended information extra field
- **0x5455** - extended timestamp
- **0x7875** - Info-ZIP UNIX (new)
- **0x5855** - Info-ZIP UNIX (original, also OS/2, NT, etc)
- **0x000A** - NTFS timestamp
- **0x000A** - NTFS timestamp

**Comment by srikanth-lingala** [comment]
@oleg-cherednik You can find a comprehensive list of extra data records [here][1]

[1]: https://fossies.org/linux/zip/proginfo/extrafld.txt

**Comment by srikanth-lingala** [comment]
@joorei I started with implementing this feature, but the more I get into it, the more complicated it gets. Especially with understanding all extra data record types and the way they have to be parsed. Some of them have complicated logic. And the list of possible extra data records is quite big (see the link in the post above for the list). It will be quite a big task to get this implemented.

**Comment by oleg-cherednik** [comment]
@srikanth-lingala yes, I have seen it. But it faced only with given fields. I have not seen most of them in real zip files from different platforms.

**Comment by srikanth-lingala** [comment]
I am short on free time to implement this feature myself. It is hard for me to catch up with other issues mentioned here and as this feature is a nice–to–have, I will be closing this one. I would be glad to get a pull request for this though.
