### ISSUE TITLE
How to create a zip with the same MD5 Checksum every time?

### ISSUE THREAD

**Issue by TheRabid** [srikanth-lingala/zip4j#159]
Hello. I'm trying to create a zip with your library that has the same MD5 Checksum every time you zip the same files with the same content in the same order, but I'm getting different MD5 checksums with every zip. Is there any option to do this? I've made a bit of a research and I think it may have something to do with the time headers (timestamp of each zip entry) but I don't see at first glance any option to change that...

Thanks in advance

**Comment by srikanth-lingala** [comment]
This depends on several factors:

- Are you using encryption?
- Which compression method are you using?
- Does the last modified time of any of the files being added change in the meantime?
- How are you creating the zip file? With `ZipFile` api or `ZipOutputStream`?

**Comment by TheRabid** [comment]
No encryption, compression method by default (I haven't changed that setting), and no I'm not changing the last modified time of the files. I'm using the `ZipFile` api.

**Comment by srikanth-lingala** [comment]
I have used the code below to add the same file to zip and I compared the crc of the files, md5 generated with JDK and md5 generated with Apache Commons Codec, and in each try the test succeeds, i.e, I get the same values for the zip file that is generated. 

```
@Test
public void testGenerateZipFile() throws IOException, DigestException, NoSuchAlgorithmException {
  File fileToAdd = new File(BASE_DIR + "sample.pdf");
  ZipFile zipFile = createZipAndAddFile(new File(BASE_DIR + "test/firstZipFile.zip"), fileToAdd);

  long firstFileCrc = CrcUtil.computeFileCrc(zipFile.getFile(), new ProgressMonitor());
  byte[] firstFileJdkMd5 = calculateJDKMd5(zipFile.getFile());
  String firstFileApacheCodecMd5 = calculateApacheCodecMd5(zipFile.getFile());

  zipFile = createZipAndAddFile(new File(BASE_DIR + "test/secondZipFile.zip"), fileToAdd);
  long secondFileCrc = CrcUtil.computeFileCrc(zipFile.getFile(), new ProgressMonitor());
  byte[] secondFileJdkMd5 = calculateJDKMd5(zipFile.getFile());
  String secondFileApacheCodecMd5 = calculateApacheCodecMd5(zipFile.getFile());

  Assertions.assertThat(firstFileCrc).isEqualTo(secondFileCrc);
  Assertions.assertThat(firstFileJdkMd5).isEqualTo(secondFileJdkMd5);
  Assertions.assertThat(firstFileApacheCodecMd5).isEqualTo(secondFileApacheCodecMd5);
}

private byte[] calculateJDKMd5(File file) throws IOException, NoSuchAlgorithmException, DigestException {
  MessageDigest md = MessageDigest.getInstance("MD5");
  try (InputStream is = Files.newInputStream(file.toPath());
       DigestInputStream dis = new DigestInputStream(is, md))
  {
    int readLen = -1;
    byte[] buff = new byte[4096];
    while ((readLen = dis.read(buff)) != -1) {
      md.digest(buff, 0, readLen);
    }
  }
  return md.digest();
}

private String calculateApacheCodecMd5(File file) throws IOException {
  try (InputStream is = Files.newInputStream(file.toPath())) {
    return DigestUtils.md5Hex(is);
  }
}

private ZipFile createZipAndAddFile(File outputZipFile, File fileToAdd) throws ZipException {
  ZipFile zipFile = new ZipFile(outputZipFile);
  zipFile.getFile().delete();
  zipFile.addFile(fileToAdd);
  return zipFile;
}
```

**Comment by srikanth-lingala** [comment]
Hope the above solution helped. If you still have any question please feel free to open a new issue or reopen this issue if your question is related to this one.
