### ISSUE TITLE
Errors extracting old Zip4J Archives (1.x) with new Zip4J

### ISSUE THREAD

**Issue by schaarda** [srikanth-lingala/zip4j#162]
I have a couple of Zips that were built with Zip4J 1.3.1 for backup-purposes of our users. Because of the size limitation 65.535 files with the old zip, we changed to Zip4J 2.1.2 and now tried 2.5.0. None of the work correctly.

The first error was the same as described here: https://github.com/srikanth-lingala/zip4j/issues/39. Extraction stopped with the crc-exception.

Zip4J 2.1.4 and 2.5.0 don't give this error, but  with 2.5.0 some(!) extracted files with german Umlauts (ä,ö,ü) and other non-Ascii characters now contain garbage chars. With 1.3.1 they extract normally.

Even more confusing is the fact, that not all characters are garbled. Sometime even the same subdirectory gets extracted twice, one time with the correct Umlaut and some files and a second time with the garbled char and the rest of the files.

Do you have any idea why this is happening? The archives were created with Zip4J 1.3.1 in one piece and have not been edited after creation. I can try to replicate the error with some non-confidential archives but this may take some time.

**Comment by srikanth-lingala** [comment]
I will try to reproduce this. I will first create a zip file with v1.3.1 of zip4j and then extract with the latest version. If I fail to reproduce, then I am afraid I have to ask you to send me a zip file that you can share with which I can reproduce this issue. I will let you know the results of my attempt.

**Comment by srikanth-lingala** [comment]
I was able to reproduce this issue. I fixed the issue and I included the fix in a snapshot release version I just made. Can you please test with zip4j version `2.5.1-SNAPSHOT` and let me know if it works? I will make a final release of v2.5.1 with the fix after I get your confirmation.

P.S.: If you have trouble accessing this snapshot version, refer to [this question][1] on Stackoverflow

[1]: https://stackoverflow.com/questions/7715321/how-to-download-snapshot-version-from-maven-snapshot-repository

**Comment by schaarda** [comment]
Thank you for the fix. I will test it on Wednesday / Thursday  when I'm back at work where I have the relevant test files. 

Am 22. März 2020 14:51:46 MEZ schrieb Srikanth Reddy Lingala <notifications@github.com>:

**Comment by schaarda** [comment]
I can confirm 2.5.1-SNAPSHOT is working fine with my test data.

**Comment by srikanth-lingala** [comment]
Fix included in zip4j v2.5.1 released today.
