### ISSUE TITLE
File Name Encryption

### ISSUE THREAD

**Issue by ShihabudheenK** [srikanth-lingala/zip4j#163]
#FeatureRequest 

I know File Name Encryption option is available in WinRAR and 7zip Softwares. This will basically hide the filenames and will show it only if correct password is entered by user. Currently if I zip some files with Zip4j and encrypt it, the password is applicable only when I click the files inside Zip. File Names are still exposed. I think there should be facility to hide Metadata or File Names as well and it's a must needed feature from a security point of view. Is it available in Zip4j ? If not could you implement file name metadata encryption.

**Comment by srikanth-lingala** [comment]
The feature you are talking about is called "Strong Encryption" in zip specification. This allows to encrypt file names. But unfortunately this encryption method is patented and proprietary to PKWare, the company behind zip specification. Refer to the section "7.0 Strong Encryption Specification" in the [zip specification][1].

[1]: https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT
