### ISSUE TITLE
Use different passwords for multiple file compression

### ISSUE THREAD

**Issue by lakxtxue** [srikanth-lingala/zip4j#164]
Hello, is it supported to use different password encryption when adding files to ZipFile？

**Comment by srikanth-lingala** [comment]
Yes, it is possible to have different encryption/password for different files in a zip. In that case you have to deal with a file by file basis when adding files and extracting files. So the logic goes something like this:

To add files with different passwords/encryption:
```
ZipFile zipFile = new ZipFile("zipfile.zip");
ZipParameters zipParameters = new ZipParameters();

zipParameters.setEncryptionMethod(EncryptionMethod.AES);
zipFile.setPassword("password1".toCharArray());
zipFile.addFile("file1");

zipParameters.setEncryptionMethod(EncryptionMethod.ZIP_STANDARD);
zipFile.setPassword("password2".toCharArray());
zipFile.addFile("file2");
```

Similarly, to extract files with different passwords/encryption:
```
ZipFile zipFile = new ZipFile("zipfile.zip");

zipFile.setPassword("password1".toCharArray());
zipFile.extractFile("file1", "outputDirectory");

zipFile.setPassword("password2".toCharArray());
zipFile.extractFile("file2", "outputDirectory");
```

**Comment by lakxtxue** [comment]
Yes, thank you.

**Comment by srikanth-lingala** [comment]
I have also add a test case to make sure that this works. See the commit above for test details.
