### ISSUE TITLE
Chinese unzip password

### ISSUE THREAD

**Issue by 1491112574** [srikanth-lingala/zip4j#165]
When the decompression password is set to Chinese, other decompression software cannot decompress

**Comment by srikanth-lingala** [comment]
There seems to be no standard way of handling non-ascii passwords. According to zip specification:

> General purpose bit 11 will not imply any encoding of file content or
> password.  Values defining character encoding for file content or 
> password MUST be stored within the 0x0008 Extended Language Encoding 
> Extra Field.

But 0x0008 extra field is still not officially defined. Again according to zip specification:

> D.3 Applications MAY choose to supplement this file name storage through the use 
> of the 0x0008 Extra Field.  Storage for this optional field is currently 
> undefined, however it will be used to allow storing extended information 
> on source or target encoding that MAY further assist applications with file 
> name, or file content encoding tasks.  **Please contact PKWARE with any
> requirements on how this field SHOULD be used.**
> 
> D.4 The 0x0008 Extra Field storage MAY be used with either setting for general 
> purpose bit 11.  Examples of the intended usage for this field is to store 
> whether "modified-UTF-8" (JAVA) is used, or UTF-8-MAC.  Similarly, other 
> commonly used character encoding (code page) designations can be indicated 
> through this field.  **Formalized values for use of the 0x0008 record remain 
> undefined at this time.  The definition for the layout of the 0x0008 field
> will be published when available.**  Use of the 0x0008 Extra Field provides
> for storing data within a ZIP file in an encoding other than IBM Code
> Page 437 or UTF-8.

This is actually a suprise for me that there is still no standard way of dealing with non-ascii passwords. But unfortunately, until there is an official specification there is nothing I can do. 

To wrap up: zip files created using non-ascii passwords with zip4j can be extracted with zip4j but not with other tools as there is no standard way of doing this.
