### ISSUE TITLE
Zip in memory

### ISSUE THREAD

**Issue by kanuku** [srikanth-lingala/zip4j#167]
Dear contributors & maintainers,

First of all, thank you for giving us, java developers, such a very handy library!!

I have been looking for a java library that enables me to create password protected zip files.
It was not long before I bumped into various example of how to use this library to do the job.

But unfortunately, for the project I am working on, I am looking for a way to encrypt zip files in memory, without writing files to the disk. To be more specific, I would be happy if I could zip files by passing the array of bytes of even a java `OutputStream`/`InputStream`.

I think it is not a very rare use case to do such file operations in-memory. I have seen many projects that generate pdf's (in-memory) or even store files in a DB.

**Comment by srikanth-lingala** [comment]
Yes, it is possible to create a zip in-memory with zip4j. Please look at [this example][1] in the documentation. Just replace `FileOutputStream` with `ByteArrayOutputStream` in that example, and you have your zip in memory.

[1]: https://github.com/srikanth-lingala/zip4j#adding-entries-with-zipoutputstream

**Comment by kanuku** [comment]
Thank you, this is what worked for me!

```
import lombok.extern.slf4j.Slf4j;
import net.lingala.zip4j.io.outputstream.ZipOutputStream;
import net.lingala.zip4j.model.ZipParameters;
import net.lingala.zip4j.model.enums.CompressionMethod;
import net.lingala.zip4j.model.enums.EncryptionMethod;
import org.springframework.stereotype.Component;

import java.io.ByteArrayOutputStream;
import java.io.IOException;

import static java.util.Objects.requireNonNull;

@Component
@Slf4j
public class CompressorServiceImpl implements CompressorService {


    /**
     * Compresses the file into zip format and encrypts the
     * file with a password if necessary.
     *
     * @param input            - file in bytes to be zipped
     * @param originalFilename - input identification name of the original file, which will be visible after unzipping the archive, like: document.pdf
     * @param password         - The password to be used to encrypt the input
     * @return
     * @throws IOException
     */
    @Override
    public byte[] compressWithPassword(final byte[] input, final String originalFilename, final String password) throws IOException {
        requireNonNull(input, "Filename content(bytes) may not be null");
        requireNonNull(originalFilename, "original Filename may not be null");
        requireNonNull(password, "Password may be null");

        final ZipParameters zipParameters = createZipParameters(originalFilename);
        final ByteArrayOutputStream bos = new ByteArrayOutputStream();
        final ZipOutputStream zos = new ZipOutputStream(bos, password.toCharArray());
        zos.putNextEntry(zipParameters);
        zos.write(input);
        zos.closeEntry();
        zos.close();
        bos.close();

        return bos.toByteArray();
    }


    private ZipParameters createZipParameters(final String filename) {
        ZipParameters zipParameters = new ZipParameters();
        zipParameters.setCompressionMethod(CompressionMethod.DEFLATE);
        zipParameters.setEncryptFiles(true);
        zipParameters.setEncryptionMethod(EncryptionMethod.ZIP_STANDARD);
        zipParameters.setFileNameInZip(filename);
        return zipParameters;
    }

}

```

**Comment by jbraga** [comment]
Hi @kanuku,

Thanks for posting the solution, what are you doing with the zip file afterwards?
I'm having problems sending it via email, the file is always corrupted and I cannot open it. Have you experienced anything like this?

**Comment by kanuku** [comment]
Hi José

I am also sending it via email.

But I had similar problems...

But before sending the file via email, you need to write the file to local
computer and make sure you can open it from you computer.
Only after this works on your machine, You can start testing via email...

**Comment by constructor-s** [comment]
Hi @kanuku thank you for the sample code. 

Maybe this is asking for too much, but is there an equivalent to create an in-memory zip from a folder containing many files? Something equivalent to:

```Java
ZipFile zipFile = new ZipFile("output.zip", "secret_password".toCharArray()); //-> instead of writing to .zip, write to memory
zipFile.addFolder(new File("source/folder/"), zipParameters); 
```

Is there a convenient `addFolder` for this purpose, or do I have to call `createZipParameters` for each file? I am zipping up to hundreds or thousands of files on Android, so I am a bit (over-)worried about performance.

**Comment by kanuku** [comment]
I don’t know your requirements, so I can only make a guess to try to solve
your  problem!
The zip mechanism would work with folder or file, it is agnostic due to
OutputStream mechanism! You don’t need to read file by file I think...
So yes I think you should be able to read a whole folder and zip it in
memory!
But it can be risky if you have to handle multiple requests at the same
time in the same instance or service because memory can become the
bottleneck!
If that is the case, I can advise you to write 2 services that share a file
system were you can write the zipped file to!
One System zips, encrypts the file, writes to file system and then passes
the zipped file name and password to the second system!
The second system reads the file in memory and sends it to the mail service!
To make both systems more reliable, you need multiple instances running of
the same services with a strict round-robin strategy to avoid one instance
having to read too much data into memory!
Please contact me on Telegram if you need better advise, my username is
Kanuku!
I am very curious about your requirements and I can give you more insights
in how I solved my problem!!

And otherwise good luck to you, although I am very curious to how you will
manage to solve this challenge!

**Comment by Romain-P** [comment]
I know this topic is old but here is a fast implementation of in-memory zipping:
https://gist.github.com/Romain-P/2caea2c984442642a54fccba9ea151e2
