### ISSUE TITLE
addFolder issue

### ISSUE THREAD

**Issue by branimir-vujicic** [srikanth-lingala/zip4j#169]
Hi, is there an option to include empty folders in archive. I'm trying to create backup archive for my folders, but empty folders are missing in created zip file.

**Comment by srikanth-lingala** [comment]
I just tried to add a folder which contains empty folders inside it, and it had the empty folders in the generated zip file. And even the empty folder was created when extracting the same zip file again with zip4j. It could be that the tool which shows/extracts the zip file in your case, ignore empty directories. Can you attach a sample zip file generated by zip4j which was supposed to have empty folders in it?

**Comment by branimir-vujicic** [comment]
Hi, I'm using ubuntu 18.04, oracle java 8 version  1.8.0_241.
The folder I'm trying to archive contains empty folders (no files, just other empty folders).
This is a list of folder :
![Screenshot from 2020-04-05 21-02-50](https://user-images.githubusercontent.com/5188457/78509687-35cf5e80-7790-11ea-89ae-5482eaf4d19a.png)
and this is a screenshot of the zip archive:
![Screenshot from 2020-04-05 21-07-36](https://user-images.githubusercontent.com/5188457/78509694-4a135b80-7790-11ea-8ae7-3181977b787c.png)
library version is 2.5.0
here is my code:
 ```java
	public Path createArchiveZip4j(Path sourceDir, Path zipDestinationDir, String sessionUid) throws InternalErrorException {

		Path zipPath = zipDestinationDir.resolve(sessionUid + ".zip");
		try {

			ZipParameters parameters = new ZipParameters();
			parameters.setCompressionMethod(CompressionMethod.DEFLATE);
			parameters.setCompressionLevel(CompressionLevel.NORMAL);
			parameters.setIncludeRootFolder(false);

			net.lingala.zip4j.ZipFile zipFile = new net.lingala.zip4j.ZipFile(zipPath.toFile());

			// Add a folder to the zip file
			zipFile.addFolder(sourceDir.toFile(), parameters);
		} catch (ZipException e) {
			log.error(ERROR_CREATING_ARCHIVE);
			throw new InternalErrorException(ERROR_CREATING_ARCHIVE, e);
		}
		return zipPath;
	}
```

**Comment by srikanth-lingala** [comment]
If I understand the issue right from the screenshot, zip4j missed to add some directories, for example "matrices", "sdfsdfsd", etc, right? Does these directories have any content inside them like other directories or files? Was the zip file already existing before your code executed?

I was still not able to reproduce this with a similar directory structure as you. My guess is that the files api is not returning the directories that in the end zip4j missed to add. Can you please set a breakpoint at AddFilesToZipTask.getFilesToAdd() line 66 as shown in the image below, and let me know if you see the directories that are missed in the zip created by zip4j? Maybe you can also post a screenshot?

<img width="914" alt="Bildschirmfoto 2020-04-08 um 19 41 22" src="https://user-images.githubusercontent.com/3450302/78815723-f04da400-79d0-11ea-8aab-6f02887da170.png">

**Comment by branimir-vujicic** [comment]
From the previous example, folder matrices contain only empty folders.
Zip file didn't exist before the execution of the program.

This is a list of the folder to archive : 
(folders starting with folder_with_files contain files, folder starting with folder_without_files contain only other folders and no files)

```
temp/zip_test/to_archive/
└── test
    ├── folder_with_files_01
    │   ├── 981850.jpg
    │   └── folder_with_files_01_01
    │       └── download.png
    ├── folder_with_files_02
    │   └── Neon.jpg
    ├── folder_without_files_01
    │   └── folder_without_files_01_01
    └── folder_without_files_02

```

Here's complete code for example:

```
import lombok.extern.slf4j.Slf4j;
import net.lingala.zip4j.model.ZipParameters;
import net.lingala.zip4j.model.enums.CompressionLevel;
import net.lingala.zip4j.model.enums.CompressionMethod;

import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.UUID;

@Slf4j
public class ZipTest {

	private static final String ERROR_CREATING_ARCHIVE = "Error creating archive !";

	public static void main(String[] args) {

		Path sourceDir      = Paths.get("/home/bane/temp/zip_test/to_archive");
		Path destinationDir = Paths.get("/home/bane/temp/zip_test/archive");

		String sessionUuid = UUID.randomUUID().toString();

		ZipTest test = new ZipTest();
		try {
			Path zipFile = test.createArchiveZip4j(sourceDir, destinationDir, sessionUuid);
			log.debug(zipFile.toString());
		} catch (Exception e) {
			log.error(ERROR_CREATING_ARCHIVE, e);
		}
	}

	public Path createArchiveZip4j(Path sourceDir, Path zipDestinationDir, String sessionUid) throws Exception {

		Path zipPath = zipDestinationDir.resolve(sessionUid + ".zip");
		try {

			ZipParameters parameters = new ZipParameters();
			parameters.setCompressionMethod(CompressionMethod.DEFLATE);
			parameters.setCompressionLevel(CompressionLevel.NORMAL);
			parameters.setIncludeRootFolder(false);

			net.lingala.zip4j.ZipFile zipFile = new net.lingala.zip4j.ZipFile(zipPath.toFile());

			// Add a folder to the zip file
			zipFile.addFolder(sourceDir.toFile(), parameters);
		} catch (Exception e) {
			log.error(ERROR_CREATING_ARCHIVE, e);
			throw new Exception(ERROR_CREATING_ARCHIVE);
		}
		return zipPath;
	}
}
```


This is the list of files from the brake point: 

```
filesToAdd = {java.util.ArrayList@867}  size = 10
 0 = {java.io.File@876} "/home/bane/temp/zip_test/to_archive/test"
 1 = {java.io.File@877} "/home/bane/temp/zip_test/to_archive/test/folder_without_files_02"
 2 = {java.io.File@878} "/home/bane/temp/zip_test/to_archive/test/folder_without_files_01"
 3 = {java.io.File@879} "/home/bane/temp/zip_test/to_archive/test/folder_without_files_01/folder_without_files_01_01"
 4 = {java.io.File@880} "/home/bane/temp/zip_test/to_archive/test/folder_with_files_01"
 5 = {java.io.File@881} "/home/bane/temp/zip_test/to_archive/test/folder_with_files_01/981850.jpg"
 6 = {java.io.File@882} "/home/bane/temp/zip_test/to_archive/test/folder_with_files_01/folder_with_files_01_01"
 7 = {java.io.File@883} "/home/bane/temp/zip_test/to_archive/test/folder_with_files_01/folder_with_files_01_01/download.png"
 8 = {java.io.File@884} "/home/bane/temp/zip_test/to_archive/test/folder_with_files_02"
 9 = {java.io.File@885} "/home/bane/temp/zip_test/to_archive/test/folder_with_files_02/Neon.jpg"

```
this is archive created by OS ( nautilus -> compress)
[test.zip](https://github.com/srikanth-lingala/zip4j/files/4456143/test.zip)

and this is an archive created by the example program
[ec84b720-c207-49f4-9e6e-9e9c0e066381.zip](https://github.com/srikanth-lingala/zip4j/files/4456147/ec84b720-c207-49f4-9e6e-9e9c0e066381.zip)

**Comment by srikanth-lingala** [comment]
The zip file generated by zip4j `ec84b720-c207-49f4-9e6e-9e9c0e066381.zip` has the empty directories in it. Screenshot below shows the files inside the zip file when zip4j reads your zip file:

<img width="677" alt="Bildschirmfoto 2020-04-09 um 14 59 41" src="https://user-images.githubusercontent.com/3450302/78897644-c947ae80-7a72-11ea-9f24-db694c761f69.png">

This is the content after zip4j extracted that zip file. As you can see there were empty directories also extracted.

<img width="707" alt="Bildschirmfoto 2020-04-09 um 14 59 08" src="https://user-images.githubusercontent.com/3450302/78897568-ad440d00-7a72-11ea-9e16-822f62f9c0a2.png">

Maybe the tool which you use to extract does not extract empty directories from a zip. Or maybe if you are just viewing the zip file, the tool does not show empty directories in its view.

**Comment by branimir-vujicic** [comment]
Hi, 
this is what I see in the Ubuntu archive manager:
![Screenshot from 2020-04-09 15-17-15](https://user-images.githubusercontent.com/5188457/78899276-6f94b380-7a75-11ea-8967-c2f720b97617.png)

Also, I received a complaint from windows users that they cannot see empty folders in Windows Explorer (compressed folder).
I will check this on windows

**Comment by srikanth-lingala** [comment]
When you extract it with zip4j, are the empty directories extracted?

**Comment by srikanth-lingala** [comment]
And also, with the zip file generated by native OS tool, can you see those empty directories in Ubuntu archive manager?

**Comment by branimir-vujicic** [comment]
Hi, when I extract the archive, all folders are there, I'll check how it behaves on windows and let you know.

**Comment by srikanth-lingala** [comment]
Can you also answer this question please:

> And also, with the zip file generated by native OS tool, can you see those empty directories in Ubuntu archive manager?

**Comment by branimir-vujicic** [comment]
When I create an archive with a native OS tool (for ubuntu Linux 18.04: nautilus -> compress ), I can see empty folders in the archive.

![Screenshot from 2020-04-09 23-17-17](https://user-images.githubusercontent.com/5188457/78941640-5e20cb00-7ab8-11ea-8e17-aa155635eed0.png)

**Comment by srikanth-lingala** [comment]
I have generated three test files for testing. Can you please post me the screenshots if the Ubuntu Archive manager is showing empty folders for any of these zip file?

[file_only_second_header.zip](https://github.com/srikanth-lingala/zip4j/files/4458876/file_only_second_header.zip)
[file_only_first_header.zip](https://github.com/srikanth-lingala/zip4j/files/4458878/file_only_first_header.zip)
[file_with_both_headers.zip](https://github.com/srikanth-lingala/zip4j/files/4458879/file_with_both_headers.zip)

**Comment by branimir-vujicic** [comment]
here are screenshots:
![Screenshot from 2020-04-10 07-53-08](https://user-images.githubusercontent.com/5188457/78966747-ef1b9480-7b00-11ea-838c-e73e156a287f.png)
![Screenshot from 2020-04-10 07-53-34](https://user-images.githubusercontent.com/5188457/78966759-f3e04880-7b00-11ea-9a2a-50c52fe52df8.png)
![Screenshot from 2020-04-10 07-53-48](https://user-images.githubusercontent.com/5188457/78966768-f9d62980-7b00-11ea-8194-8051e66271b1.png)

**Comment by srikanth-lingala** [comment]
Can you please check again with this file if it shows empty folders?
[test.zip](https://github.com/srikanth-lingala/zip4j/files/4461319/test.zip)

**Comment by branimir-vujicic** [comment]
Now, archive manager shows empty folders :D
![Screenshot from 2020-04-10 13-41-54](https://user-images.githubusercontent.com/5188457/78988445-3a4d9b80-7b31-11ea-96dd-d1cb69c53b14.png)

**Comment by srikanth-lingala** [comment]
This one was created by Keka, and not by zip4j. There are not too many differences between the one created by zip4j and by Keka or ubuntu tool. Not sure why Archive manager decides to skip the ones created by zip4j. Looking into it. It might be that I will send you a few more files to check.

**Comment by srikanth-lingala** [comment]
Can you check these 3 zip files again please?
[fileWithoutUtf8AndWithVersionMadeBy.zip](https://github.com/srikanth-lingala/zip4j/files/4461528/fileWithoutUtf8AndWithVersionMadeBy.zip)
[filewithversionmadeby.zip](https://github.com/srikanth-lingala/zip4j/files/4461529/filewithversionmadeby.zip)
[filewithoututf8.zip](https://github.com/srikanth-lingala/zip4j/files/4461530/filewithoututf8.zip)

**Comment by branimir-vujicic** [comment]
here are screenshot
![Screenshot from 2020-04-10 15-21-53](https://user-images.githubusercontent.com/5188457/78993930-3759a780-7b3f-11ea-8e90-9516794afa81.png)
![Screenshot from 2020-04-10 15-22-05](https://user-images.githubusercontent.com/5188457/78993943-3aed2e80-7b3f-11ea-89ed-b2118dd8051e.png)
![Screenshot from 2020-04-10 15-22-11](https://user-images.githubusercontent.com/5188457/78993949-3e80b580-7b3f-11ea-8794-e12a6d5db84a.png)

**Comment by srikanth-lingala** [comment]
I think now I figured out the issue. But I am quite surprised that the archive manager is behaving this way. Basically, zip4j uses utf8 as default charset. Archive manager seems to ignore the directories which are marked as utf8. Strangely it shows files which are utf8, but seems to ignore only the directories if they are utf8. 

Do you have utf8 charset support on your os? And also can you please post the screenshot for one more zip file attached below?

[test.zip](https://github.com/srikanth-lingala/zip4j/files/4461784/test.zip)

**Comment by branimir-vujicic** [comment]
![Screenshot from 2020-04-10 16-51-15](https://user-images.githubusercontent.com/5188457/78999774-9ae9d200-7b4b-11ea-97ad-b595473a05f7.png)

UTF-8 is default character encoding on my OS

**Comment by srikanth-lingala** [comment]
This is a really strange behaviour by Archive Manager. This seems to be a bug in their tool. Zip specification allows using Cp-437 and utf-8 as standard charsets. And zip4j uses utf-8 as its default charset. Apparently, archive manager on Ubuntu seems to ignore directories which use utf-8 encoding but file names does not contain any non-ascii character. This is totally not against the zip specification, and utf-8 encoding can be used as long as the appropriate flag is set, which zip4j sets in this case. One way for zip4j would have been to use cp-437 by default and use utf-8 only when needed (in case of non-ascii characters), but  I do not want to change the default behaviour of zip4j now for this bug in Archive manager, especially when such behaviour is not against zip specification. And moreover, the files and folders in the zip are properly extracted, and other tools do not have any problem with viewing and extracting, I will have to mark this as "not-an-issue".

**Comment by branimir-vujicic** [comment]
Thank You for Your time and effort. 
I will close this issue.
