### ISSUE TITLE
Slow unzipping with password

### ISSUE THREAD

**Issue by sgdmitriev** [srikanth-lingala/zip4j#170]
Hi.
I use your library in my app (Android, Kotlin, Zip4j v2.5.1)
to decompress (for example) archive with about 700 files inside (compressed size only 4MB).
Source code is pretty simple:
val zipFile = ZipFile(sSourcePath)
if(zipFile.isEncrypted) zipFile.setPassword(cZIP_PASSWORD.toCharArray())
zipFile.extractAll(sTargetPath)
If archive is not encrypted, time is 4 seconds on my old Sony Tabled Z3
The same archive with password takes approx 190 sec to decompression
If archive contains only one file with compressed size ~5MB, the time is
1 sec without password and 5 secs with it. Password may be simple "1". Does not matter
It would be cool if you could fix this issue

**Comment by srikanth-lingala** [comment]
Encryption/Decryption of data from zip file, especially with AES, is very memory intensive process. It really depends on the amount of memory (RAM) available to the process at the time of execution. I presume that the device you are testing on does not have too much memory allotted for this application. Because zip4j is used by a lot of apps on Android, and I have never heard it being slow on Android. I guess this is a hardware issue, and as mentioned earlier, just that not a lot of memory is available. I would also encourage you to test it on a device with higher memory to see if this is still the case.

**Comment by srikanth-lingala** [comment]
And just to test, maybe you can also test to extract with any other app on Android and see how much time that app takes (presuming both the apps have same amount of resources available).

**Comment by sgdmitriev** [comment]
And here we go with fresh stats)

**archive: 750 java files compressed size 5MB**

Sony Xperia Z3 compact RAM 2GB
https://www.gsmarena.com/sony_xperia_z3_compact-6538.php

Zip4j v2.5.1
w/o password 4 sec
with password 3min 10 sec

WinZip android app (by WinZip Computing)
w/o password 9 sec
with password 28 sec

**archive: 3800 java files compressed size 14MB**

Sony Xperia Z3 compact RAM 2GB

Zip4j v2.5.1
w/o password 5 sec
with password 16 min !!!

WinZip android app (by WinZip Computing)
w/o password 50 sec - too slow probably because file-by-file progress animating
with password 2 min 27 sec

Android Emulator RAM 4GB on my Lenovo L340-17IWL (intel i7 16GB SSD)
Zip4j v2.5.1
w/o password 2.5 sec
with password 2 min 20 sec !!!

WinRAR windows app on my Lenovo L340
with password 7s

I also check app process via Android Studio Profiler while decryption is in progress.
On Sony tablet memory usage 100-200MB, on Emulator at my Windows host 70-100MB.
CPU usage both 50%

So i guess something wrong inside decryption algorythm...

**Comment by srikanth-lingala** [comment]
thanks for the detailed info. Which encryption method was being used? AES or Zip Standard (ZipCrypto)?

**Comment by sgdmitriev** [comment]
AES.
But thanks) you pointed me on that i simply could change file encryption to old Zip 2.0 style.
And after that decryption takes only 3 secs. Thanks)
