### ISSUE TITLE
Zip headers not found. Probably not a zip file at ...

### ISSUE THREAD

**Issue by myaghobi** [srikanth-lingala/zip4j#172]
I'm using zip4j-2.5.1 on Android (`minSdkVersion16`). I have an encrypted zip file that needs to unzip, but I got this error from some(about 10%) of my users!
`Zip headers not found. Probably not a zip file at ...`

**Comment by srikanth-lingala** [comment]
Can you share the zip file? Without a zip file in this case, it will be hard to say what might have happened.

**Comment by myaghobi** [comment]
It's containing a small SQLite database(about 10 MB). Usually, I use WinRAR to make that zip file with password & default options. 
It's not possible to share the zip file.

**Comment by srikanth-lingala** [comment]
> Usually, I use WinRAR to make that zip file with password & default options.

Could it be that it was a rar file by mistake? As mentioned earlier, without the zip file, it will be hard to say for me. All I can say for now is that, as the error message says, zip4j was unable to find the relevant zip headers in the file. For now, my conclusion would be that it most likely is not a zip file.

**Comment by myaghobi** [comment]
No, It's a zip file I saved with `.mp3` format! Decryption works fine on my devices, AVDs and on the device of most of my users.

**Comment by srikanth-lingala** [comment]
What do you mean by a zip file with .mp3 format?

**Comment by srikanth-lingala** [comment]
Closing this issue as there is no further feedback.
