### ISSUE TITLE
注释不支持gbk？

### ISSUE THREAD

**Issue by wolfing88** [srikanth-lingala/zip4j#173]
zipFile.setCharset(Charset.forName("GBK")); 乱码

**Comment by wolfing88** [comment]
zipFile.setComment("Lingala哥们");

**Comment by srikanth-lingala** [comment]
Please post your question/issue in English.

**Comment by wolfing88** [comment]
zipFile.setComment("Lingala哥们"); 

GBK garbled ?

**Comment by srikanth-lingala** [comment]
The following example worked fine for me:

```
@Test
public void testGenerateZipFileWithComment() throws IOException {
    String commentToAdd = "Lingala哥们";
    ZipFile zipFile = new ZipFile("test.zip");
    zipFile.setCharset(Charset.forName("GBK"));
    if (zipFile.getFile().exists()) {
      zipFile.getFile().delete();
    }
    zipFile.addFile(new File("test.pdf"));
    zipFile.setComment(commentToAdd);

    zipFile = new ZipFile("test.zip");
    zipFile.setCharset(Charset.forName("GBK"));
    System.out.println(zipFile.getComment());
    Assertions.assertThat(zipFile.getComment()).isEqualTo(commentToAdd);
}
```

The test passes and prints out expected `Lingala哥们`

**Comment by srikanth-lingala** [comment]
Please note that the zip comment will be garbled when using any other tool other than zip4j, unless the tool provides a way to pass in custom charsets to read comments. Zip specification does not specify a way to store charset information when adding comments. When you use a custom charset to add comment to a zip file, this makes it incompatible with other tools, and will work fine with zip4j of course. But, as mentioned earlier, if the tool has a way to use custom charset like zip4j does, then you can pass in your custom charset to the tool.

**Comment by srikanth-lingala** [comment]
Hope the above post answers your question. If you have any further questions/issues, please feel free to reopen this issue.
