### ISSUE TITLE
Exclude files from being zipped

### ISSUE THREAD

**Issue by JarFiles** [srikanth-lingala/zip4j#176]
Hey,
I wanted to know if it's possible to exclude files from being zipped.
For example:
ZipFile#addFolder adds all files and it's subdirectories to the zip file.
But there are a few files which I just don't want being added. I tried getting all files manually and then using ZipFile#addFiles but now all files end up being in the root directory of the zip file. Is there a way to keep the folder structure in the zip file?

**Comment by fatmyxtap** [comment]
Hi all, I have this problem too, I tried to find workaround and I prepared all files which I want to zip as ArrayList<File> and executed ZipFile#addFiles, but my structure of directories was broken inside the zip file. I believe we can save structure and we can exclude some files or directories too.

**Comment by JarFiles** [comment]
I'll try to add it to the src and create a pull request later

**Comment by srikanth-lingala** [comment]
PR merged. Issue to add tests created #189 . I will add tests before I release this feature.

**Comment by srikanth-lingala** [comment]
I have added tests. And also, I made some changes to the PR which was merged:

- Renamed `ExcludeFileHandler` to `ExcludeFileFilter`
- Moved `ExcludeFileFilter` from `ZipParameters` to method argument in `ZipFile.addFolder()`, as this feature is only available when adding a folder to the zip file

**Comment by srikanth-lingala** [comment]
Actually, after some more thoughts, I moved the filter back to ZipParameters, because as part of an upcoming feature in #84, it will be possible to add folders also with `ZipFile.addFiles()` method. In this case, it will be useful to have this filter in `ZipParameters`.

**Comment by srikanth-lingala** [comment]
Feature added in v2.6.0 released today
