### ISSUE TITLE
Update file example

### ISSUE THREAD

**Issue by mgalanb** [srikanth-lingala/zip4j#184]
Hello, do you have an example of how to update a file in a zip?, Otherwise it could be how to add one in a specific path inside the zip. Thanks!

**Comment by srikanth-lingala** [comment]
To update a file in a zip, just add the file you want to update, and as long as it has the same file name, zip4j will update the file with the file you have added. For example: if a zip file has a file with file name `abc.txt`, and if you add a file again with the same name `abc.txt`, zip4j will update this file. If the file you want to update is inside a directory with directory structure: `root_dir/sub_dir1/filename.txt`, to update this file, you have to add file with the same complete name. For this you can make use of `ZipParameters.setFileNameInZip("root_dir/sub_dir1/filename.txt")`. I guess this also answers your second question.

**Comment by srikanth-lingala** [comment]
Closing this issue. Please feel free to reopen if you find any issues with the proposed solution above.
