### ISSUE TITLE
No suitable constructor found for ZipFile(String,char[])

### ISSUE THREAD

**Issue by ErShakirAnsari** [srikanth-lingala/zip4j#186]
ZipFile zipFile = new ZipFile("filename.zip", "password".toCharArray());

> No suitable constructor found for ZipFile(String,char[])

zipFile.addFiles(filesToAdd, zipParameters);

> cannot find symbol
>   symbol:   method addFiles(List<File>,ZipParameters)
>   location: variable zipFile of type ZipFile
> 

version: 2.5.2

**Comment by ErShakirAnsari** [comment]
Was using `java.util.zip.ZipFile` instead `net.lingala.zip4j.ZipFile`

**Comment by alejouribesanchez** [comment]
Yes, I was getting the same android import by default ava.util.zip.ZipFile
