### ISSUE TITLE
how to close zipFile

### ISSUE THREAD

**Issue by huangjunchao** [srikanth-lingala/zip4j#188]
when I read a zip file,then I call file.delete return false; how can i close the zip4j using the file

**Comment by srikanth-lingala** [comment]
When you are using `ZipFile` api, the zip file is closed by zip4j, but when you are using `ZipInputStream`, you have to close the file. Are you using `ZipFile` or `ZipInputStream`? Which version of zip4j are you using? And also, can you post your code?

**Comment by srikanth-lingala** [comment]
And also which OS are you on?

**Comment by huangjunchao** [comment]
o, i know, i used ZipIuputStream but not closed it,think you,the problem is solved
