### ISSUE TITLE
Exception adding Streams at result file size > 4.2 GB

### ISSUE THREAD

**Issue by mmagicgit** [srikanth-lingala/zip4j#190]
Hi, I'm getting a exception if I add multiple streams to a zip file. The pseudo code and exception is below. Let the code run until the resulting zip file reaches 4.2 GB. I think that code should work, what do you think?

Thx in advance!

Code:
Path zipFile = /* zip File */;
byte[] bytes = Files.readAllBytes(/* path to 10 Mb file*/);
for (int i = 0; i < 500; i++) {
  ZipParameters parameters = new ZipParameters();
  parameters.setFileNameInZip(i + "");
  new ZipFile(zipFile.toFile()).addStream(new ByteArrayInputStream(bytes), parameters);
 }

Exception:
net.lingala.zip4j.exception.ZipException: invalid signature for zip64 end of central directory record
	at net.lingala.zip4j.headers.HeaderReader.readZip64EndCentralDirRec(HeaderReader.java:389)
	at net.lingala.zip4j.headers.HeaderReader.readAllHeaders(HeaderReader.java:91)
	at net.lingala.zip4j.ZipFile.readZipInfo(ZipFile.java:973)
	at net.lingala.zip4j.ZipFile.addStream(ZipFile.java:403)

I'm using version 2.6 but earlier versions were also affected in a different way. Version 2.3 doesnt throw an exception but produces a corrupted zip file.

**Comment by srikanth-lingala** [comment]
Code seems to be fine. It should have worked. I will try it out and update the thread.

**Comment by srikanth-lingala** [comment]
I was able to reproduce this. Working on a fix.

**Comment by srikanth-lingala** [comment]
Issue fixed. Will include the fix in the next release.

**Comment by mmagicgit** [comment]
Thank you for the fast response and fix. I tested this and can confirm the issue is solved in 2.6.1-SNAPSHOT. Good Work!
Are there any plans for the next release? Can you say when that will be approximately?

**Comment by srikanth-lingala** [comment]
There are a couple of more bugs reported that need to be fixed and I will make a release. Most likely this week/weekend.

**Comment by srikanth-lingala** [comment]
Fix included in v2.6.1 released today.
