### ISSUE TITLE
compatible low-level jdk

### ISSUE THREAD

**Issue by Moqu** [srikanth-lingala/zip4j#191]
In RemoveFilesFromZipTask.updateHeaders， Math.negateExact  is jdk version 1.8, it is recommended to rewrite it, so that it can support low-level android calls

**Comment by srikanth-lingala** [comment]
I am not an android expert, but [there are tests][1] to make sure that zip4j is compatible with Android. These tests run on different versions of Android SDK from 23 to 29, and the test are passing there. Do you mean this method in missing in a SDK version lower than 23?

[1]: https://circleci.com/gh/srikanth-lingala/zip4j-android-test

**Comment by Moqu** [comment]
yes！The SDK below version 23, removeFiles will crash, because the SDK below version 24 uses java jdk1.6, SDK 24 ~ 26 uses java jdk 1.7, SDK 26 above uses java jdk 1.8 ...

**Comment by srikanth-lingala** [comment]
This is a minor change, and the method call can be implemented directly in zip4j to avoid calling jdk's method, but I hope that there are no more such methods, it will be difficult to change all method calls if there are any more. I will make this change and include it in the next release.

**Comment by srikanth-lingala** [comment]
Fix included in v2.6.1 released today.
