### ISSUE TITLE
Extracting jar file: Unexpected end of input stream

### ISSUE THREAD

**Issue by Frank-Buettner-Knowis** [srikanth-lingala/zip4j#194]
Hi,

we want to extract a "ordinary" jar file. With version 1.3.3 it's working like a charm. From version 2.0 on we get a
> net.lingala.zip4j.exception.ZipException: Could not read corresponding local file header for file header: META-INF/MANIFEST.MF

With verion 2.6.0, it's a 
> java.io.EOFException: Unexpected end of input stream

This is the code

> ZipFile zipFile = new ZipFile(JAR_FILE_NAME);
    Path tempDirectory = Files.createTempDirectory(null);
    tempDirectory.toFile().deleteOnExit();
    zipFile.extractAll(tempDirectory.toString());

You can use your [own jar](https://repo1.maven.org/maven2/net/lingala/zip4j/zip4j/2.6.0/zip4j-2.6.0.jar) for reproducing the issue.

**Comment by srikanth-lingala** [comment]
Issue fixed. Will include the fix in the next release.

**Comment by srikanth-lingala** [comment]
Fix included in v2.6.1 released today.
