### ISSUE TITLE
Provide a migration guide from version 1.x to 2.x

### ISSUE THREAD

**Issue by jimmyMaci** [srikanth-lingala/zip4j#197]
Hi there, im using zip4j in version 1.3.2 and wanted to migrate to version 2.x latest.

Im getting error 

error: package net.lingala.zip4j.core does not exist

**Comment by adityaponnada** [comment]
I am having the same issue. Looks like instead of that we need to import:
`import net.lingala.zip4j.ZipFile;`
But the method calls seem to have changed significantly

**Comment by srikanth-lingala** [comment]
Unfortunately I am extremely short on free time to write this. There are not many changes in v2.x compared to v1.x. Please go through the documentation written in the README. If there are still any questions, I would be glad to answer them.
