### ISSUE TITLE
Some packages cannot print folders

### ISSUE THREAD

**Issue by Qoen** [srikanth-lingala/zip4j#198]
> As shown in the title，

### Use:
`for (FileHeader fileHeader : zipFile.getFileHeaders()){`
`fileHeader.getFileName()`
`}`

### Example

**The normal printed log should look like this:**
`r/ (this is a folder)`
`r/a.xml`
`r/b.xml`

**Unable to print out folder:**
`r/a.xml`
`r/b.xml`

> I found that when using WinRAR to open these compressed packages that can't print out the folders, the modification time of their folders is empty

**Comment by srikanth-lingala** [comment]
Do I understand correct, that the zip file was generated with WinRAR, and when you print out all the names of the entries in the zip with zip4j, the folder name is missing?

**Comment by Qoen** [comment]
This zip is obtained like this:
Install any Android application, get the application.apk through data/app/(application package name)/application.apk, and change the application.apk to application.zip

**Comment by srikanth-lingala** [comment]
zip4j reads the entries in the zip file metadata to print out all the file names present in the zip. If zip4j did not print out an entry, it means that that entry is not in the zip metadata. There is nothing much zip4j can do here unfortunately. Note that for directories in a zip file, it is not a must that the root directory be present in the zip entries. Some tools when creating zip file with directories decide to skip adding the root folder, which was the case in your zip/apk. The tool that created the apk decided not to add the root folder. Technically it is not an issue if a tool does not add it, and even without the root folder, a zip file is a perfectly valid zip file. 

But just to repeat again, this has nothing to do with zip4j, and zip4j is just printing out the entries added to the zip file. The tool that created the zip file chose not to add the root folder, and therefore you do not see it in the above output

**Comment by Qoen** [comment]
Thank you. I get it
