### ISSUE TITLE
setDefaultFolderPath() is not working as expected

### ISSUE THREAD

**Issue by BullyWiiPlaza** [srikanth-lingala/zip4j#199]
I'm trying to replace the `MANIFEST.MF` file inside a `JAR` (which is essentially a `ZIP`) using the library (`v2.6.1`) and the parent directory always ends up being named `NF` instead of the full `META-INF`. Is there anything wrong with my code or is this a bug?
```
String metaInfFolderName = "META-INF";
Path extractedManifestFilePath = Paths.get("...");
ZipFile zipFile = new ZipFile("Test-Zip-File.zip");
ZipParameters zipParameters = new ZipParameters();
zipParameters.setDefaultFolderPath(metaInfFolderName);
zipFile.addFile(extractedManifestFilePath.toFile(), zipParameters);
```
Thank you.

**Comment by srikanth-lingala** [comment]
Looking into it. I am going through some pretty busy days, so please expect some delays in my response. Rest assured, I will look into it as soon as I can.

**Comment by srikanth-lingala** [comment]
To replace a file in zip, it is better to make use of `ZipParameters.setFileNameInZip()` property, rather than `ZipParameters.setDefaultFolderPath()`. Here is a slight modification of your code where I used `setFileNameInZip()` and it worked fine. Please note that I also appended `metaInfFolderName` with a forward slash at the end.

```
String metaInfFolderName = "META-INF/";
Path extractedManifestFilePath = Paths.get(BASE_DIR, "MANIFEST.MF");
ZipFile zipFile = new ZipFile(BASE_DIR + "Test-1.0.jar");
ZipParameters zipParameters = new ZipParameters();
zipParameters.setFileNameInZip(metaInfFolderName + extractedManifestFilePath.getFileName().toString());
zipFile.addFile(extractedManifestFilePath.toFile(), zipParameters);
```

**Comment by srikanth-lingala** [comment]
As mentioned above, please use `setFileNameInZip`. I am closing this issue now. Please feel free to reopen if the proposed solution does not work for you.
