### ISSUE TITLE
Feature: Unzip multiple ZIPs at once

### ISSUE THREAD

**Issue by ckzgraphics** [srikanth-lingala/zip4j#201]
:green_book: **Use case:**

- Suppose I have multiple zips (multiple files with _.zip_ extension) on some directory
- I want to extract all of these zips

:dart: **Example:**

- (_Maybe_) Create a method that accepts the 3 arguments- Source Path. Zip Names, Destination Path
- The zips could be stored in a String Array, List, etc

Source Path => `/path/to/zips`
List of Zips => `String[] allZips = { "file1.zip", "file2.zip" }` OR List<String>
Destination Path => `/path/to/extract`

`object.extractTheseZIPs(SourcePath, ZIPList, DestinationPath);`

**Comment by ckzgraphics** [comment]
Thoughts, @srikanth-lingala ?

**Comment by srikanth-lingala** [comment]
This can be achieved with a simple for loop. Pseudo-code would be something like:

for each item in the list of files
  ZipFile zipFile = new ZipFile();
  zipFile.extractAll();

I am a bit hesitant to adding such feature to zip4j. This logic should be outside of zip4j. Even if I added it to zip4j, the code would be the same as above. I really appreciate your thoughts on this, but I think such logic should exist outside of zip4j.
