### ISSUE TITLE
Feature: add validity check for missing z* files

### ISSUE THREAD

**Issue by yarix** [srikanth-lingala/zip4j#202]
is it possible to add (or change existing) validity check that will verify if all split files exists?

it happens that sometimes one or few zip split files (z01, z02 ...etc.) are missing on the disk (due to various reasons, not related to zip4j). The `extractAll` method will start the extraction and will fail only when it encounter the missing file with
```Caused by: java.io.FileNotFoundException: zip split file does not exist: /home/ec2-user/bigZip.z11```

it would be nice if i could test for missing files in advance. (like `zipFile.isValidZipFile()` add `zipFile.isValidSplitZipFile()` )

**Comment by srikanth-lingala** [comment]
Sure, I think it is a good idea as well. I will add this logic to the existing `ZipFile.isValidZipFile()` method.

**Comment by srikanth-lingala** [comment]
Feature added. Will include it in the next release

**Comment by yarix** [comment]
👍

**Comment by srikanth-lingala** [comment]
Feature added in v2.6.2 released today.
