### ISSUE TITLE
Files added with ZipFile#addStream can't be opened

### ISSUE THREAD

**Issue by quilicicf** [srikanth-lingala/zip4j#205]
Hi, 

I'm trying to add files in an encrypted zip by stream but I can't open them after I unzip the archive.

My code looks like this (I'm using v2.6.1):

```java
public void createZip() {
  final ZipFile zip = new ZipFile(path, "password".toCharArray());

  final String content = "content";
  try (final InputStream stream = new  ByteArrayInputStream(content.getBytes(StandardCharsets.UTF8))) {
    zip.addStream(stream, createZipParameters("folder/myfile.txt"));
  }
}

public ZipParameters createZipParameters(String fileNameInZip) {
  final ZipParameters zipParameters = new ZipParameters();
  zipParameters.setCompressionMethod(DEFLATE);
  zipParameters.setCompressionLevel(MAXIMUM);
  zipParameters.setEncryptFiles(true);
  zipParameters.setEncryptionMethod(ZIP_STANDARD);
  zipParameters.setFileNameInZip(fileNameInZip);
  return zipParameters;
}
```

When I extract an archive built like this, the files have no rights, see the output of ls:

```
ls -l 
total 8
---------- 1 me me 7573 juin  17 12:29 myfile.txt
```

What am I doing wrong?

> Also, replacing the encryption method by AES I can't even unzip the generated archive :-(

**Comment by srikanth-lingala** [comment]
Your code works perfectly fine for me. PFA the generated zip file. I tried opening the zip file with several tools (zip4j, Keka, Mac inbuilt zip, Unarchiver), and it was successfully extracted with each of the tool. Which OS are you working on? Which tool did you use to extract the zip file?

**Comment by quilicicf** [comment]
I'm on Ubuntu and used the default tool from the GUI. Also tried `unzip` without success (but it might be the same tool as the GUI's). 

I've just tried with 7zip and it works indeed. Looks like the Ubuntu tools are buggy.

I guess the best action for this would be some documentation?

**Comment by srikanth-lingala** [comment]
It would be hard to document without knowing the scenario which is causing this issue. Zip4j is used by Ubuntu users and I haven't heard of such issue so far. I will try to reproduce this issue on an Ubuntu, and if this issue is persistent without regard to file size, etc, I would then add it to documentation with the details.

**Comment by quilicicf** [comment]
Seems right yeah :+1: 
Tell me if you need more information.

**Comment by srikanth-lingala** [comment]
Closing this issue, as this is not an issue with zip4j, but rather with the zip tools on Ubuntu.
