### ISSUE TITLE
Bug : Encrypted password unzipped without password(The Unarchiver:mac)

### ISSUE THREAD

**Issue by malvern** [srikanth-lingala/zip4j#207]
I have noticed that if I try to unzip an encrypted file using **The Unarchiver software** in **macOS(High Sierra)** no password prompt window is the display and the application(The Unarchiver) proceeds to unzip the files.

Copying the same folder(zipped folder) to other **OS(Linux mint Sarah and Windows 7)** unzipping the file requires a password.

Code used to generate the zipped folder

      try {
            File txt = new File("NoiseMakersList.txt");
            txt.createNewFile();
            ZipParameters zipParameters = new ZipParameters();
            zipParameters.setEncryptFiles(true);
            zipParameters.setEncryptionMethod(EncryptionMethod.AES);
            zipParameters.setAesKeyStrength(AesKeyStrength.KEY_STRENGTH_256);
            char[] charPassword = new char[]{'p','a','s'};
            ZipFile zipFile = new ZipFile("/Desktop/physics-docs/noiseMaker.zip", charPassword);
            zipFile.addFiles(new ArrayList<>(Collections.singleton(txt)), zipParameters);
        } catch (IOException e) {
            e.printStackTrace();
        }

**Comment by srikanth-lingala** [comment]
I tested your code on a mac catalina, and I was prompted for a password when extracting with The Unarchiver. I will try to test this on High Sierra, but I would be quite surprised if I saw a different behaviour. Would it be possible for you to share the zip file?

**Comment by malvern** [comment]
[noiseMaker.zip](https://github.com/srikanth-lingala/zip4j/files/4878921/noiseMaker.zip)

find attached zipped folder

**Comment by srikanth-lingala** [comment]
This happens because, The Unarchiver seems to not ask a password if the file size is 0. I have reproduced the scenario you mentioned, and as long as the file size was 0, The Unarchiver did not ask any password. But as soon as I added a single charachter to the text file, The Unarchiver asks for a password.

**Comment by malvern** [comment]
ok, I got it however, I have noticed that on file extraction password pop up if user clicks continue without password a blank file is returned. 

That's the reason why I thought its a bug.

![image](https://user-images.githubusercontent.com/6083879/88476702-e083ac80-cf3a-11ea-87be-ea73b197eb45.png)
