### ISSUE TITLE
Error with version 6.1 2

### ISSUE THREAD

**Issue by chxc** [srikanth-lingala/zip4j#208]
When I call the BBB method, it crashes.If not called, the main thread will be blocked.Version zip4j_1.3.2 does not appear.

**Comment by srikanth-lingala** [comment]
What do you mean by BBB method?

**Comment by chxc** [comment]
I`m so sorry .BBB=ZipFile.setRunInThread(true);
I called it before the “ZipFile.extractAll(filePath);” method.
This is Erro log:
java.lang.BootstrapMethodError: Exception from call site #0 bootstrap method

**Comment by chxc** [comment]
My code like this:
void zipToolMethodTest(String zipFilePath,String targetPath){
	File file=new File(zipFilePath);
	ZipFile zFile=new ZipFile(file);
    ProgressMonitor progressMonitor = zFile.getProgressMonitor();	
	new Thread(new Runnable() {
            @Override
            public void run() {
                while (true){
                    System.out.println("current progress :"+progressMonitor.getPercentDone());
                    try {
                        Thread.sleep(50);
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                }
            }
        }).start();
    zFile.setRunInThread(true);
    zFile.extractAll(filePath);

}

**Comment by chxc** [comment]
My code like this.
`void zipToolMethodTest(String zipFilePath,String targetPath){
	File file=new File(zipFilePath);
	ZipFile zFile=new ZipFile(file);
    ProgressMonitor progressMonitor = zFile.getProgressMonitor();	
	new Thread(new Runnable() {
            @Override
            public void run() {
                while (true){
                    System.out.println("current progress :"+progressMonitor.getPercentDone());
                    try {
                        Thread.sleep(50);
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                }
            }
        }).start();
    zFile.setRunInThread(true);
    zFile.extractAll(filePath);

}`

**Comment by chxc** [comment]
My code like this.
`void zipToolMethodTest(String zipFilePath,String targetPath){
	File file=new File(zipFilePath);
	ZipFile zFile=new ZipFile(file);
    ProgressMonitor progressMonitor = zFile.getProgressMonitor();	
	new Thread(new Runnable() {
            @Override
            public void run() {
                while (true){
                    System.out.println("current progress :"+progressMonitor.getPercentDone());
                    try {
                        Thread.sleep(50);
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                }
            }
        }).start();
    zFile.setRunInThread(true);
    zFile.extractAll(targerPath);
}`

**Comment by chxc** [comment]
My code like this.
`void zipToolMethodTest(String zipFilePath,String targetPath){
	File file=new File(zipFilePath);
	ZipFile zFile=new ZipFile(file);
    ProgressMonitor progressMonitor = zFile.getProgressMonitor();	
	new Thread(new Runnable() {
            @Override
            public void run() {
                while (true){
                    System.out.println("current progress :"+progressMonitor.getPercentDone());
                    try {
                        Thread.sleep(50);
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                }
            }
        }).start();
    zFile.setRunInThread(true);
    zFile.extractAll(targerPath);
}`

**Comment by chxc** [comment]
My code like this.
```
    void zipToolMethodTest(String zipFilePath,String targetPath) throws ZipException {
        File file=new File(zipFilePath);
        ZipFile zFile=new ZipFile(file);
        final ProgressMonitor progressMonitor = zFile.getProgressMonitor();
        new Thread(new Runnable() {
            @Override
            public void run() {
                while (true){
                    System.out.println("current progress :"+progressMonitor.getPercentDone());
                    try {
                        Thread.sleep(50);
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                }
            }
        }).start();
        zFile.setRunInThread(true);
        zFile.extractAll(targetPath);
    }

```

**Comment by srikanth-lingala** [comment]
Your code seems to work fine, and unfortunately there is not enough information in the exception message nor your code that I can help you any further with this issue. I have however, slightly modified your code to check the appropriate status and result codes when running in thread mode:

```
File file=new File(BASE_DIR + "test/test.zip");
ZipFile zFile=new ZipFile(file);
final ProgressMonitor progressMonitor = zFile.getProgressMonitor();
zFile.setRunInThread(true);
zFile.extractAll(BASE_DIR + "test/");

while (progressMonitor.getState().equals(ProgressMonitor.State.BUSY)) {
  System.out.println("Current progress: " + progressMonitor.getPercentDone());
  try {
    Thread.sleep(50);
  } catch (InterruptedException e) {
    e.printStackTrace();
  }
}

if (progressMonitor.getResult().equals(ProgressMonitor.Result.SUCCESS)) {
  System.out.println("successfully extracted");
} else {
  System.out.println("Extraction failed");
  if (progressMonitor.getException() != null) {
    progressMonitor.getException().printStackTrace();
  }
}
```

To investigate your issue, I need some more information, for example, your OS, version of zip4j you are using and more importantly more details about the exception you are getting, for example a complete stacktrace including the exception message.

**Comment by srikanth-lingala** [comment]
And what do you mean by version 6.1 2? Which version are you talking about? JDK?

**Comment by chxc** [comment]
> And what do you mean by version 6.1 2? Which version are you talking about? JDK?
That is version"2.6.1".
And I did as you said .Then my app get some Exceptions.
-----------------------------  Frist Exception    ----------------------------------------
java.lang.BootstrapMethodError: Exception from call site #1 bootstrap method
        at net.lingala.zip4j.tasks.AsyncZipTask.execute(AsyncZipTask.java:30)
        at net.lingala.zip4j.ZipFile.extractAll(ZipFile.java:445)
...
(some of my code ,Ignore it )
...
        at android.view.View.performClick(View.java:6668)
        at android.view.View.performClickInternal(View.java:6639)
        at android.view.View.access$3100(View.java:794)
        at android.view.View$PerformClick.run(View.java:26200)
        at android.os.Handler.handleCallback(Handler.java:907)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7586)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)

----------------------   second Exception  -------------------------
AndroidRuntime: FATAL EXCEPTION: main
    PID: 4488
    java.lang.SecurityException: Permission Denial: Component com.google.android.gms/.chimera.container.SharedModuleProvider requests FLAG_SINGLE_USER, but app does not hold android.permission.INTERACT_ACROSS_USERS
        at android.os.Parcel.createException(Parcel.java:1953)
        at android.os.Parcel.readException(Parcel.java:1921)
        at android.os.Parcel.readException(Parcel.java:1871)
        at android.app.IActivityManager$Stub$Proxy.attachApplication(IActivityManager.java:3936)
        at android.app.ActivityThread.attach(ActivityThread.java:7365)
        at android.app.ActivityThread.main(ActivityThread.java:7573)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
     Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.am.ActivityManagerService.isSingleton(Ljava/lang/String;Landroid/content/pm/ApplicationInfo;Ljava/lang/String;I)Z(libmapleservices.so:4257573)
        at com.android.server.am.ActivityManagerService.generateApplicationProvidersLocked(Lcom/android/server/am/ProcessRecord;)Ljava/util/List;(libmapleservices.so:5304813)
        at com.android.server.am.ActivityManagerService.attachApplicationLocked(Landroid/app/IApplicationThread;IIJ)Z(libmapleservices.so:5695961)
        at com.android.server.am.ActivityManagerService.attachApplication(Landroid/app/IApplicationThread;J)V(libmapleservices.so:5957733)
        at android.app.IActivityManager$Stub.onTransact(ILandroid/os/Parcel;Landroid/os/Parcel;I)Z(libmapleframework.so:4808817)

**Comment by chxc** [comment]
My zip file contains folders

**Comment by srikanth-lingala** [comment]
Even with your second exception it is hard to see what is going wrong, or if this issue is even related to zip4j. Did you figure out something in the meanwhile?

**Comment by srikanth-lingala** [comment]
Closing the issue, as there was no further feedback. Please feel free to reopen if you have any further information.
