### ISSUE TITLE
Mention JRE requirement more prominently in README

### ISSUE THREAD

**Issue by Marcono1234** [srikanth-lingala/zip4j#212]
Point 5 of the [FAQ](https://github.com/srikanth-lingala/zip4j#faq) mentions in a side note that this project requires at least Java 8.
This requirement is probably rather important for many users of the library and it would be good if this could be mentioned somewhere at the beginning of the README. Though I am not sure which one of the existing sections would fit, so maybe adding a new "Requirements" section would be good?

**Comment by srikanth-lingala** [comment]
Sure, and actually this point needs to be updated as zip4j supports Java 7 as well. When rewriting zip4j, the minimum version of JDK supported was 8, but based on requests by android app developers, I had to rewrite some parts to supports Java 7 as well to support older Android SDKs.

**Comment by Marcono1234** [comment]
Should I write a pull request, or do you want to perform this change?

**Comment by srikanth-lingala** [comment]
I added it to a newly created section `Requirements` in README.

**Comment by Marcono1234** [comment]
Thanks. I have left some comments on the commit describing how it could possible be slightly improved.

**Comment by Marcono1234** [comment]
@srikanth-lingala, have you seen my comments on your commit 1bbb90c?

**Comment by srikanth-lingala** [comment]
Actually, I just had a look at them. And they are now fixed.
