### ISSUE TITLE
FileHeader.getLastModifiedTime() is Incorrect

### ISSUE THREAD

**Issue by wlfbck** [srikanth-lingala/zip4j#214]
I'm not ruling out a 100% that i'm doing something wrong, but i don't think so. Here's a minimal example:
```
import java.io.File;
import java.io.IOException;

import net.lingala.zip4j.ZipFile;
import net.lingala.zip4j.model.FileHeader;

public class Test {
	public static void main(String[] args) throws IOException {
		File f = new File("test.txt");
		f.createNewFile();
		ZipFile zf = new ZipFile(new File("test.zip"));
		zf.addFile(f);
		for(FileHeader header : zf.getFileHeaders()) {
			System.out.println(header.getLastModifiedTime());
		}
		java.util.zip.ZipFile javazip = new java.util.zip.ZipFile(new File("test.zip"));
		System.out.println(javazip.getEntry("test.txt").getLastModifiedTime());
		System.out.println(javazip.getEntry("test.txt").getLastAccessTime());
	}
}
```

At the time of writing this, i got `1357412609`. Which according to https://www.epochconverter.com/ is several years in the past (and in seconds instead of milliseconds, but oh well). Note that javas method returns the correct timestamp `2020-07-08T13:08:02Z` and `null` for last accessed.

If i open the zip with winrar however, it displays a correct last modified timestamp:
![grafik](https://user-images.githubusercontent.com/1621804/86922562-206e2580-c12d-11ea-931d-d2045d8153e0.png)

**Comment by wlfbck** [comment]
Alright, i found the problem myself. What zip4j is giving me is the dos timestamp and not epoch time. It would be great if that could be noted in the javadoc or better yet, the timestamp converted to epoch time in ms :)

**Comment by srikanth-lingala** [comment]
According to the zip specification, the date and time format in zip headers are encoded in DOS format. I would prefer to update the documentation, and leave the getter as it is, that is, it returns a dos timestamp. Another reason, I cannot change it now is that any change to this return value will break backward compatibility and will break applications relying on this field.

**Comment by wlfbck** [comment]
Oh interesting, didn't know that. And yeah, good point on compatibility. Would it be possible to add another method to return the epoch time?

**Comment by srikanth-lingala** [comment]
Yes, sure, I will add a method to return epoch time.

**Comment by wlfbck** [comment]
Cool, thank you very much! :)

**Comment by srikanth-lingala** [comment]
Feature added. And BTW, I found an issue where conversion to DOS time was causing a loss of a second in some cases. I fixed this issue, and also added the feature to retrieve epoch time through FileHeader. I will include this in the next release.

**Comment by srikanth-lingala** [comment]
Feature added in v2.6.2 released today.
