### ISSUE TITLE
java.util.zip.ZipException: invalid CEN header (encrypted entry)

### ISSUE THREAD

**Issue by timonvlad** [srikanth-lingala/zip4j#215]
I have zipped with AES256 single file.... Then added to this encrypted zip comment with public key.... But when I try to read comment from encrypted zip - get just = java.util.zip.ZipException: invalid CEN header (encrypted entry)/// wtf?)

**Comment by srikanth-lingala** [comment]
What do you mean by "encrypted zip comment with public key"? How exactly did you add an encrypted zip comment with public key? Do you mean you encrypted a string with a key and then added that text as a comment? Can you post your code? And also which version of zip4j are you using?

P.S: I would appreciate if you avoid using offensive words. Thanks.

**Comment by srikanth-lingala** [comment]
Closing this issue as there was no response. Feel free to reopen if you have any feedback to my questions from my previous post.
