### ISSUE TITLE
Is it possible to set BUFFER_SIZE from outside?

### ISSUE THREAD

**Issue by namjitharavind** [srikanth-lingala/zip4j#216]
can we set BUFFER_SIZE from outside in case extractAll method?

**Comment by srikanth-lingala** [comment]
Unfortunately not at the moment. I will add this as a new feature though.

**Comment by srikanth-lingala** [comment]
Feature added in v2.7.0 which was released today. You can now set custom buffer size with `ZipFile.setBufferSize(int)`.
