### ISSUE TITLE
Exporting to CSV is failing without any error

### ISSUE THREAD

**Issue by ddramireddy** [srikanth-lingala/zip4j#219]
Hi Srikanth,

First, I would like to Thank you for providing this wonderful utility.

I am currently using 2.3.1 version. We are exporting around 10 tables to a zip file using this library. After exporting to zip file, I see zip file has only first 3 tables. However, in the logs I don't see any error and all 10 tables export process is getting completed. If i exclude 4th  table, I see zip file has  remaining 9 tables. So, the 4th table is causing the issue. But I don't see any error message related to it.

Is there any way, I can identify the error, that is causing? By any chance, is it fixed in later versions?

**Comment by srikanth-lingala** [comment]
What do you mean by "tables"? Is it database tables you are talking about? How are you exporting it? Any sample code? I would highly recommend trying with the latest version and to see if that fixes the issue.

**Comment by srikanth-lingala** [comment]
Closing this as there is no further feedback. Feel free to reopen if you have a feedback to my questions in the post above.
