### ISSUE TITLE
net.lingala.zip4j.exception.ZipException: Probably not a zip file or a corrupted zip file

### ISSUE THREAD

**Issue by Mobackharshavardhanreddy** [srikanth-lingala/zip4j#221]
Hi, 

I'm trying yo unzip multipart file using zip4j , but unfortunately it is throwing below exception

net.lingala.zip4j.exception.ZipException: Probably not a zip file or a corrupted zip file
	at net.lingala.zip4j.core.HeaderReader.readEndOfCentralDirectoryRecord(HeaderReader.java:179)
	at net.lingala.zip4j.core.HeaderReader.readAllHeaders(HeaderReader.java:78)
	at net.lingala.zip4j.core.ZipFile.readZipInfo(ZipFile.java:425)
	at net.lingala.zip4j.core.ZipFile.getFileHeaders(ZipFile.java:688)
	at com.ugaan.campusdirect.profile.controller.RecruiterContoller.lambda$uplo

**Comment by Mobackharshavardhanreddy** [comment]
@RequestMapping(value = "/uploadFiles", method = RequestMethod.POST, consumes = "multipart/form-data")
	public ResumeUploadResponse uploadFile(@RequestParam(value = "files") MultipartFile[] files,
			@RequestParam(value="company_id") String company_id,
			@RequestParam(value="recruiter_id") String recruiter_id,
			@RequestParam(value="folder", defaultValue = "") String folder) {
		ResumeUploadResponse resp = new ResumeUploadResponse();
		List<String> list = new ArrayList<String>();
		List<String> list2 = new ArrayList<String>();
		HashMap<InputStream, String> map=new HashMap<InputStream, String>();
		Arrays.asList(files).stream().forEach(file -> {
			InputStream inputStream=null;
			try {
				 inputStream = file.getInputStream();	
			String fileName=file.getOriginalFilename();
		//	String fileName="C:\\Users\\moback\\Desktop\\resumes.zip";
			
			if(FilenameUtils.getExtension(fileName).equals("zip")) {
				
					ZipFile zf = new ZipFile(fileName);
					zf.addStream(inputStream, new ZipParameters());
					List fileHeaderList = zf.getFileHeaders();
					
					  for (int i = 0; i < fileHeaderList.size(); i++) { 
						  FileHeader fileHeader = (FileHeader) fileHeaderList.get(i); 
						  ZipInputStream is =zf.getInputStream(fileHeader); 
						  InputStream ip = new FileInputStream(fileHeader.getFileName()); 
						  String result = recruiterServices.uploadFileToS3(ip, fileHeader.getFileName(),
					  file.getContentType(),company_id,recruiter_id,folder); list.add(result); }
					System.out.println(fileHeaderList.toString());
}

**Comment by srikanth-lingala** [comment]
ZipFile api works only with File api, and the complete file should be available for reading, because zip4j seeks to the end of file, and tries to read the zip headers located at the end of the zip file. When using MultipartFile, I guess the complete file is not available for seeking to the end of the file, and zip4j cannot find the headers. I would suggest working only with ZipOutputStream when working with Multipart files

**Comment by Mobackharshavardhanreddy** [comment]
Thanks for your quick reply, you are suggesting to work with import net.lingala.zip4j.io.ZipOutputStream or java.util.zip.ZipOutputStream

**Comment by srikanth-lingala** [comment]
If you want to work with zip4j, then use `net.lingala.zip4j.io.ZipOutputStream`. `java.util.zip.ZipOutputStream` should also work if you want to rely directly on JDK's zip classes.
