### ISSUE TITLE
README: Incorrect addFolder with ExcludeFileFilter example

### ISSUE THREAD

**Issue by constructor-s** [srikanth-lingala/zip4j#222]
https://github.com/srikanth-lingala/zip4j/blob/bc8e344149c1020f168758260966b5ad6bbdcff3/README.md#L97-L104

Clearly, `..., new ZipParameters, ...); ` is not proper Java syntax with constructor called without brackets (unless I am missing some new Java features...)

I guess it should be:?

```Java
ExcludeFileFilter excludeFileFilter = filesToExclude::contains;
ZipParameters zipParameters = new ZipParameters();
zipParameters.setExcludeFileFilter(excludeFileFilter);
new ZipFile("filename.zip").addFolder(new File("/user/myuser/folder_to_add"), zipParameters);
```

**Comment by srikanth-lingala** [comment]
Thanks for pointing it out. I fixed it.

**Comment by srikanth-lingala** [comment]
Issue fixed.
