### ISSUE TITLE
Where can we find the change logs for version 2.6.2?

### ISSUE THREAD

**Issue by adityaponnada** [srikanth-lingala/zip4j#224]
I can see it is available in maven for use in Android: https://mvnrepository.com/artifact/net.lingala.zip4j/zip4j

But we can't find any change logs. We want to upgrade from 1.3.2 to this version.

**Comment by srikanth-lingala** [comment]
v2.6.2 is not released yet. I do not see any artefact by that version in the link you posted as well, which makes sense.

Usually all change logs are updated [here](https://github.com/srikanth-lingala/zip4j/releases), as soon as a version of zip4j is released.

**Comment by adityaponnada** [comment]
Sorry, I meant 2.6.1. 

Changing from 1.3.3 to 2.6.1 seems to require massive code changes. Was wondering if there is a tutorial for that transition?

**Comment by srikanth-lingala** [comment]
This is a matter of perception, but I think the changes are not too many. Unfortunately, there is no migration documentation, but the examples described in the README should be a good start. All the use cases have sample code in README. If you miss to find any information, please ask me here.

**Comment by srikanth-lingala** [comment]
Will be tracked as part of #197
