### ISSUE TITLE
Zip4j 1.3.3 deleting files from within the folder

### ISSUE THREAD

**Issue by adityaponnada** [srikanth-lingala/zip4j#225]
Hello, thanks for this library. it is really useful. I use it in my app to zip and encrypt a set of folders (all zipped and encrypted separately). However, I notice that in some cases (hard to reproduce), some files of the folders go missing. The way i figured out was i got the size of the folder before compressing and after. In cases where it worked, it should have been compressed to 1.5 MB. But then there are cases where the size is 0.4 MB. On extracting the files, it turns out that one of the files was missing which was present right before `createZipFileFromFolder` is called. But after the call, the folder is zipped with just one file inside. I am trying to understand under what conditions this can happen. Any information will be helpful. Here is a sample code snippet that runs for these folders individually:

```
public static void zipFolderWithEncryption(String folderPath, Context context) {
        boolean isException = false;
        Log.i(TAG, "zipFolderWithEncryption - " + folderPath, context);
        File zipFolder = new File(folderPath);
        try {
            if (folderPath.charAt(folderPath.length() - 1) == '/') {
                folderPath = folderPath.substring(0, folderPath.length() - 1);
            }
            File zipFile = new File(folderPath + ".zip");

            if (zipFile.exists()) {
                //Log.i(TAG, "ZipFile already exists, deleting - " + zipFile.getAbsolutePath(), context);
                //FileUtils.delete(zipFile);
                return;
            }
            ZipParameters zipParameters = new ZipParameters();
            zipParameters.setCompressionMethod(Zip4jConstants.COMP_DEFLATE);
            zipParameters.setCompressionLevel(Zip4jConstants.DEFLATE_LEVEL_ULTRA);
            zipParameters.setIncludeRootFolder(false);
            zipParameters.setEncryptFiles(true);
            zipParameters.setEncryptionMethod(Zip4jConstants.ENC_METHOD_AES);
            zipParameters.setAesKeyStrength(Zip4jConstants.AES_STRENGTH_256);
            zipParameters.setPassword("xxxxxxxxxxx");
            ZipFile zip = new ZipFile(zipFile);
            Log.i(TAG, "Creating ZipFile from Folder - " + zipFolder.getAbsolutePath(), context);
            zip.createZipFileFromFolder(zipFolder, zipParameters, false, 0);
            refreshFileSystem(zipFile, context);

        } catch (ZipException e) {
            isException = true;
            Log.i(TAG, "Exception while creating zip folder with encryption", e, context);
        }

        if (!isException) {
            Log.i(TAG, "Deleting Folder - " + zipFolder.getAbsolutePath(), context);
            FileUtils.delete(zipFolder);
        }
    }
```

**Comment by srikanth-lingala** [comment]
Zip4j 1.3.3 is not supported anymore. Can you please upgrade to the latest version? There were a lot of critical fixes done in v2.x. It might as well be that the issue you reported here got resolved as well.

**Comment by adityaponnada** [comment]
Thank you so much. Just recently, we figured that the issue was calling the library in a thread. Changing it to single thread solved it for us. However, we did notice that the corrupted zip file is created even when zipping failed due to exception. We handle it within our code. You can close this.
