### ISSUE TITLE
Can folder encryption

### ISSUE THREAD

**Issue by hainanlxk** [srikanth-lingala/zip4j#226]
I want to encrypt the entire folder so that the user can only open the folder by entering the correct password

**Comment by srikanth-lingala** [comment]
What exactly do you mean by encrypt the folder? If you mean encrypting all files in a folder, you can do it with ZipFile.addFolder() call. Have a look at the example in ReadMe for sample code.

**Comment by hainanlxk** [comment]
Hello, my idea is that I can't see the name of all the files in the folder including the contents. Can I do the whole compression package encryption, which means the outermost layer of encryption, but all the folders and files inside are not encrypted? When I open the compression package, I need to enter the password to open the compression package and see all the files inside

**Comment by hainanlxk** [comment]
Hello, my idea is that if you can be the most outer layer encryption, the entire package all the folders and files is not encrypted, when I opened the package need password, to open the package to see all of the files in it, and you side is after open the package to need a password to open the file, this is not what I want.

**Comment by srikanth-lingala** [comment]
If I understand you right, you would like the user to enter password even before they see the folder/file names. If this is the case, there is such a possibility with zip specification, called Strong Encryption. Search for "7.0 Strong Encryption Specification" in [this document](https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT). But this is PKWARE Proprietary (copyright), and needs license from PKWare to implement it.

**Comment by hainanlxk** [comment]
Thank you for your help.

**Comment by hainanlxk** [comment]
Is there no other way?

**Comment by srikanth-lingala** [comment]
Unfortunately no.
