### ISSUE TITLE
`addFolder` causes the compressed file to have an unwanted top-level directory

### ISSUE THREAD

**Issue by ijliym** [srikanth-lingala/zip4j#227]
When I use the `addFolder` method to add a directory into a zip file, the result zip file will has a top-level directory, this maybe redundant.

Please see the picture.
![image](https://user-images.githubusercontent.com/43025881/90509515-02fc9480-e18c-11ea-8992-76b9aeea1ab4.png)

**Comment by srikanth-lingala** [comment]
Use ZipParameters.includeRootFolder(false) to exclude the root folder. I believe this is set to true by default.

**Comment by ijliym** [comment]
Thank you very much. It works!
