### ISSUE TITLE
Single/Multi-threaded Compression of Files/Folders

### ISSUE THREAD

**Issue by ShihabudheenK** [srikanth-lingala/zip4j#229]
#FeatureRequest

I have got two requests.

1. I was wondering Is there any way to utilize the no of cores in CPU to increase the speed of compression without compromising the compression level.
2. Is there any method to add all the files (or files with a specific extension) in a folder to a zip file during compression without having the root folder present in zip file?

 If these are already present, please guide me else could you check the feasibility of implementing the same?

**Comment by srikanth-lingala** [comment]
1. Zip file format (like most other compression formats) is sequential, that is one compressed entry follows another compressed entry. To compress an entry means that the compressed size is unknown until the compression is done. Only after the compression is done, the next entry can be added. In other words, compression of one entry cannot start until compression of the previous entry is complete. It will not be impossible to achieve this, but will be quite complicated and a bit risky (leading to corrupt zip files) depending on the implementation. 

2. You can use `ZipParameters.setIncludeRootFolder(false)` to skip adding root folder.

**Comment by srikanth-lingala** [comment]
Closing this issue. Feel free to reopen if you have any further feedback/questions.
