### ISSUE TITLE
Maybe you should add an api that unpacks all the files with keywords?

### ISSUE THREAD

**Issue by isMeiying** [srikanth-lingala/zip4j#23]
And, I added some extensions for the zip4j kotlin version and added an api for him, like this: 

> file.extractTo(destination, "keyword1/fileName", "keyword2/fileName")

Actually in java it should be:
> ZipFile().extractFile(String, String...)

maybe you should add it in zip4j, thank you very much, zip4j is a very great library, It is the best library I have used. The imperfection is that its api is not perfect.

**Comment by srikanth-lingala** [comment]
Thanks for your feedback. My first impression of this feature is that this use-case is a unique requirement and not a generic one to be included in the library. And also regarding this feature I see several uncertainties like: what if the keyword is a nested directory (some_dir/keyword/someFileName) or what if the keyword is the name of a file. 

Please don't get me wrong. I would very much welcome feedback for new features. But I get a lot of requests (sometimes also via email) for features which I see to be not generic ones. If I include all those features, the library will get very bloated and will be difficult to maintain and also to use. 

My suggestion for this feature is that if I get any upvotes on this feature or if I get any requests for similar feature like this one, I will definitely integrate it into the library.
