### ISSUE TITLE
`dosToJavaTme` typo mistake

### ISSUE THREAD

**Issue by ijliym** [srikanth-lingala/zip4j#230]
`net.lingala.zip4j.util.Zip4jUtil#dosToJavaTme` method name has a typo mistake.

**Comment by srikanth-lingala** [comment]
This has been fixed (or rather changed), as part of a different issue #214 . The new method will be called `dosToExtendedEpochTime`. I will include this in the next release.

**Comment by srikanth-lingala** [comment]
I will close this issue as this will be tracked in #214
