### ISSUE TITLE
unzip ZipEntry getSize 

### ISSUE THREAD

**Issue by water-rookie** [srikanth-lingala/zip4j#235]
The getSize method of ZipEntry returns - 1

**Comment by srikanth-lingala** [comment]
Which ZipEntry you mean? Zip4j does not have a class ZipEntry. Do you mean the ZipEntry from [JDK's zip library][1]?

[1]: https://docs.oracle.com/javase/8/docs/api/java/util/zip/ZipEntry.html

**Comment by srikanth-lingala** [comment]
Closing this issue, as there is no further feedback.
