### ISSUE TITLE
Facing issue during extraction of password protected zip file

### ISSUE THREAD

**Issue by anilj95** [srikanth-lingala/zip4j#238]
Created Password protected zip file using zip4j, able to extract in android mobile. In my macOs Catalina, I am not able to extract folder after providing password, showing password dialog again and again. attaching zip folder and screenshot
<img width="468" alt="Screenshot 2020-09-10 at 9 52 19 AM" src="https://user-images.githubusercontent.com/15407018/92681703-fc58db80-f34b-11ea-99a9-2c1268a0f658.png">
[2020-08-26_13_07_34_Lenovo L38043__.zip](https://github.com/srikanth-lingala/zip4j/files/5199173/2020-08-26_13_07_34_Lenovo.L38043__.zip)

password: seahawks

**Comment by srikanth-lingala** [comment]
Entries in this zip file are encrypted with AES. Mac's default Archive Utility does not support AES encryption. You can use third party tools like Keka, The Unarchiver, etc.

**Comment by anilj95** [comment]
Thank you for your valuable input.
