### ISSUE TITLE
Spring Boot dependency not working

### ISSUE THREAD

**Issue by NischayaSharma** [srikanth-lingala/zip4j#240]
I have added `net.lingala.zip4j `in my dependencies but still when i import it in my service and use the ZipFile class to create an object it says `ZipFile cannot be resolved to a type`.

https://github.com/NischayaSharma/unzipPasswordFile/
here is my current code i am working on.

**Comment by srikanth-lingala** [comment]
Check your maven settings. Your code worked perfectly fine for me. I followed the instructions in your README and I got the file name back in the response as described in your readme.

**Comment by NischayaSharma** [comment]
Alright, That was just the logic i wrote, Good to know its working
properly. I will check the maven config in my environment
