### ISSUE TITLE
decode failed with chinese file name

### ISSUE THREAD

**Issue by lidaling** [srikanth-lingala/zip4j#242]
```
使用：fileHeader.getFileName()
解压成功 ：test_md/πÇÉµò░µì«ΘççΘ¢å_Σ╕èµ╡╖πÇæσêÿµÖ║ 2σ╣┤.md
使用：fileHeader.getFileName()
解压成功 ：test_md/πÇÉµò░µì«ΘççΘ¢å_Σ╕èµ╡╖πÇæΣ╕çσå¢σìÄ 2σ╣┤.md
使用：fileHeader.getFileName()
解压成功 ：test_md/πÇÉσ¢╛σâÅΦ»åσê½ _ Σ╕èµ╡╖ 15k-30kπÇæτ½áµÿÄµÿƒ 4σ╣┤.md
使用：fileHeader.getFileName()
解压成功 ：test_md/πÇÉµò░µì«ΘççΘ¢å_Σ╕èµ╡╖πÇæΣ╕üΣ║ÜΣ╕£ 5σ╣┤.md
```

**Comment by srikanth-lingala** [comment]
Most likely a custom Charset was used during the creation of the zip file. Zip specification allows two charsets by default (CP850 and UTF8). But a lot of tools (including zip4j) also allow using custom charset to encode file names. But the side effect of using custom charset is that the zip filenames cannot be decoded with other zip tools unless you know the charset that was used by the tool that created the zip file. If you know the charset, you can pass it to ZipFile.setCharset() and this should then work.

To verify that my assumption is right, would it be possible to attach the zip file?

**Comment by srikanth-lingala** [comment]
Closing this issue as there is no further feedback.

**Comment by chuxubank** [comment]
>  If you know the charset, you can pass it to ZipFile.setCharset() and this should then work.

How to set charset when using `ZipInputStream` ?
