### ISSUE TITLE
Handle filename accents in add folder method

### ISSUE THREAD

**Issue by damien-guillermet** [srikanth-lingala/zip4j#243]
Hello,

it seems that the method `net.lingala.zip4j.ZipFile.addFolder(File folderToAdd, ZipParameters zipParameters)` does not handle the accents in file/directory names (i.e.: 'àéÔ').
The result zip/archive skip the accents.

By the way I would like to thank you for this usefull library!

Thanks for your help, best regards.

---
Used version: 2.6.2

**Comment by srikanth-lingala** [comment]
Works fine for me. Here is the code I am using

```
@Test
public void testIssue243() throws IOException {
    ZipFile zipFile = new ZipFile(BASE_DIR + "test.zip");
    zipFile.addFolder(new File(BASE_DIR));
}
```

And here is the zip file generated. This zip file contains a folder which contains a file by the name "àéÔ.txt"

[test.zip](https://github.com/srikanth-lingala/zip4j/files/5270055/test.zip)

I see that you also use `ZipParameters`. Do you set any flag/value in  the `zipParameters`?

**Comment by srikanth-lingala** [comment]
Closing this issue as there is no further feedback.
