### ISSUE TITLE
Compare 2 zip archives

### ISSUE THREAD

**Issue by pavelnazimok** [srikanth-lingala/zip4j#252]
Hi @srikanth-lingala , been using zip4j to work with zip archives and it is really helpful. Currently, I have a task to compare the content of 2 zip archives. 

So is there a way to compare 2 zip archives using your library? By 'compare' I mean to check if the file tree and all the files inside both archives are identical to each other.

If not, what do you think about adding this feature in the future?

**Comment by srikanth-lingala** [comment]
It is an interesting idea, but might get slightly challenging to implement. The problem might arise with the definition of equality of zip files. Are two zip files which have same files, and contents of the file are same as well, but just one of the file has been compressed with different algorithm, the same? How many fields should we include in comparison? For example does the comparison logic include timestamps? There are many, many more fields a file in a zip can contain. How far should the comparison algorithm go? Even if I draw some boundaries and implement something like this in zip4j, two zip files which are not equal (content same, but wrong timestamps for example) might be flagged as equal by zip4j, which results in inconsistencies.

I think this is more a specific to the application feature than a general feature that can be implemented in zip4j.

**Comment by pavelnazimok** [comment]
@srikanth-lingala Thanks for your insight! I see your point and I think you are right, so I'm closing this issue.
