### ISSUE TITLE
Invoke-customs are only supported starting with Android O (--min-api 26)

### ISSUE THREAD

**Issue by monkey1992** [srikanth-lingala/zip4j#253]
After integrating zip4j 2.6.4, I want to run my Android application on the Android 4.4.4 device, but the following error will be reported during the compilation process:

```AGPBI: {"kind":"error","text":"Invoke-customs are only supported starting with Android O (--min-api 26)","sources":[{}],"tool":"D8"}

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sample:mergeDexUatDebug'.
> Could not resolve all files for configuration ':sample:uatDebugRuntimeClasspath'.
   > Failed to transform artifact 'zip4j.jar (net.lingala.zip4j:zip4j:2.6.4)' to match attributes {artifactType=android-dex, dexing-enable-desugaring=false, dexing-is-debuggable=true, dexing-min-sdk=19, org.gradle.usage=java-runtime-jars}.
      > Execution failed for DexingNoClasspathTransform: /Users/xiaoyu/.gradle/caches/modules-2/files-2.1/net.lingala.zip4j/zip4j/2.6.4/b1edd95127caa3a6c38b75b092b9c4a3ab91b835/zip4j-2.6.4.jar.
         > Error while dexing.
           The dependency contains Java 8 bytecode. Please enable desugaring by adding the following to build.gradle
           android {
               compileOptions {
                   sourceCompatibility 1.8
                   targetCompatibility 1.8
               }
           }
           See https://developer.android.com/studio/write/java8-support.html for details. Alternatively, increase the minSdkVersion to 26 or above.
```
Does zip4j still retain some of the grammatical features of java 8？
I don't want to configure android compileOptions。

**Comment by monkey1992** [comment]
I found lambda expressions in many places，like this:
![image](https://user-images.githubusercontent.com/13364538/97938426-58743500-1dbc-11eb-9d4c-f7ce9a769eb1.png)
If these lambda expressions are replaced by anonymous classes, this problem can be solved！
Otherwise, java.util.Collection#stream is supported since java 1.8:
![image](https://user-images.githubusercontent.com/13364538/97945241-ddae1880-1dc1-11eb-8b99-03d56e23058d.png)
this should be replaced with programming syntax supported by java 1.7 or lower.

**Comment by srikanth-lingala** [comment]
I am not an Android expert, but one of the users of zip4j has contributed to run zip4j on different versions of Android during the build process. You can check that [here][1], and the configuration is [here][2]. How is it working with api version lower than 26 in this case?

[1]: https://app.circleci.com/pipelines/github/srikanth-lingala/zip4j-android-test
[2]: https://github.com/srikanth-lingala/zip4j-android-test

**Comment by srikanth-lingala** [comment]
Closing this issue as there is no further feedback on this. Please feel free to reopen if you have any further feedback for my post above.
