### ISSUE TITLE
Is there any way to lower the requirements to Java 6?

### ISSUE THREAD

**Issue by jtholmi** [srikanth-lingala/zip4j#255]
Hello, I would like to utilize the zip4j library in MATLAB, but one version of it only uses Java 6. Is there any way to lower the requirements to Java 6? Or is there a specific reason that zip4j requires Java 7?

**Comment by srikanth-lingala** [comment]
zip4j 1.x was written on java 6, but some features added to jdk in 7/8, especially nio package, are useful for some features of zip. A couple of reasons being that I cannot lower the requirement: It will now require some considerable effort to go back to Java 6, and more importantly going back would mean losing some important features (restoring file permissions, etc).

**Comment by jtholmi** [comment]
Thanks for your detailed reply! It is actually helpful that I can use zip4j 1.x on Java 6.
