### ISSUE TITLE
EncryptionMethod.ZIP_STANDARD_VARIANT_STRONG

### ISSUE THREAD

**Issue by rrconstantin** [srikanth-lingala/zip4j#256]
https://github.com/srikanth-lingala/zip4j/blob/b1d523cdf9cbe808b7a271095c3add7c877bb8e5/src/main/java/net/lingala/zip4j/model/enums/EncryptionMethod.java#L20

When using ZIP_STANDARD_VARIANT_STRONG, a ZipException("Invalid encryption method") is thrown because in ZipOutputStream only AES and ZIP_STANDARD encryption methods are treated.

**Comment by rrconstantin** [comment]
After further debugging, I see that EncryptionMethod.ZIP_STANDARD_VARIANT_STRONG is used for unzipping only, so maybe the exception message can be more meaningful, ie "ZIP_STANDARD_VARIANT_STRONG not supported for encryption".

**Comment by rrconstantin** [comment]
Created PR https://github.com/srikanth-lingala/zip4j/pull/257

**Comment by minguser** [comment]
use zip4j zip File,success to make a zip file
`            ZipFile zipFile = new ZipFile(destZipFile);
            ArrayList filesToAdd = new ArrayList();
            filesToAdd.add(new File(filePath));
            ZipParameters parameters = new ZipParameters();
            parameters.setCompressionMethod(CompressionMethod.DEFLATE);
            parameters.setCompressionLevel(CompressionLevel.MAXIMUM);
            zipFile.createSplitZipFile(filesToAdd, parameters, true, spilitFileMaxLength);`

but unzip failed.unzip code:`try {
            ZipInputStream zin = new ZipInputStream(in);
            ZipEntry ze;
            while ((ze = zin.getNextEntry()) != null) {
                if (!(ze.isDirectory())) {
                    byte[] buf = new byte[1024];
                    try {
                        ByteArrayOutputStream swapStream = new ByteArrayOutputStream();
                        byte[] buff = new byte[1024]; //buff用于存放循环读取的临时数据
                        int rc = 0;
                        while ((rc = in.read(buff, 0, 1024)) > 0) {
                            swapStream.write(buff, 0, rc);
                        }
                        buf = swapStream.toByteArray(); //in_b为转换之后的结果
                    } catch (Exception e) {
                        e.printStackTrace();

                    }

                    InputStream bais = new ByteArrayInputStream(buf);
                    BufferedReader br = new BufferedReader(new InputStreamReader(bais));
                    String name = ze.getName();
                   ......
                }
            }
            zin.closeEntry();
            zin.close();
        } catch (Exception e) {
            e.printStackTrace();
        }`,and zin.getNextEntry() is always null,I don't konw the reason,

**Comment by srikanth-lingala** [comment]
> After further debugging, I see that EncryptionMethod.ZIP_STANDARD_VARIANT_STRONG is used for unzipping only, 

Actually, `ZIP_STANDARD_VARIANT_STRONG` is neither supported for encryption nor for decryption. This is a proprietary encryption method by PKWare and using this encryption technology needs license from them. The only reason I had it as an enum is that this field is defined in the zip specification.

**Comment by srikanth-lingala** [comment]
I appreciate the PR, but unfortunately, I cannot accept the PR as it might mislead the users that unzipping using `ZIP_STANDARD_VARIANT_STRONG` is supported, which is not the case.

**Comment by rrconstantin** [comment]
I appreciate your response. You can use the same message for decryption too. My issue was that the exception message is misleading: using an ecryption method offered by the library is labeled as invalid (not supported is something else).

**Comment by srikanth-lingala** [comment]
I pushed a commit with a small change to your exception message because of the reason mentioned above. I will close your PR, but thanks again for your PR.

**Comment by srikanth-lingala** [comment]
Fixed in v2.7.0 which was released today.
