### ISSUE TITLE
ZipFile can be constructed with a null File causing NPE some time later

### ISSUE THREAD

**Issue by mdaloia** [srikanth-lingala/zip4j#263]
Current version (2.6.4) allows to construct a `ZipFile` with a `null` `File` reference: (i.e. `new ZipFile((File) null)`) without proper validation. This does not happen if you use the constructor with the `String` argument as internally it does a `new File(string)` and if the string is `null` the `File` constructor throws a NPE.

The consequence of this is that when you want to do an operation with the `ZipFile` instance (e.g. `zipFile.getFileHeaders()` it throws a NPE on this [line](https://github.com/srikanth-lingala/zip4j/blob/b1d523cdf9cbe808b7a271095c3add7c877bb8e5/src/main/java/net/lingala/zip4j/ZipFile.java#L960).

To avoid these scenarios, it should be properly validated on construction of `ZipFile` if accepting a null reference as File is not valid later.

On previous versions (1.3.2) there was a check that somehow on later releases it was removed (particularly on [this commit](https://github.com/srikanth-lingala/zip4j/commit/d72a4710b2b70c0674b4bd6a180381d70e20c5cc)).
This is 1.3.2:
![image](https://user-images.githubusercontent.com/1738654/100474497-87ca4900-30bf-11eb-9005-0c7b64274f7c.png)

**Comment by srikanth-lingala** [comment]
Thanks for pointing it out. I will add this check.

**Comment by srikanth-lingala** [comment]
Issue fixed in v2.7.0 which was released today.
