### ISSUE TITLE
Add an option to compress the file without locking it.

### ISSUE THREAD

**Issue by alizadehei** [srikanth-lingala/zip4j#264]
I want to compress a file that is already locked by another process.
when I try to compress it, I receive following error: 
`the process cannot access the file because another process has locked a portion of the file`
It seems that there isn't a way of doing that in the current version of Zip4J. Since, compressing only needs reading the files and in some applications (like online backup on a database that has failover capabilities and locking is not necessary since it can handle problems in copying) locking may not be necessary, it may be a good idea to add an option to Zip4J so that it does not lock the files when compressing.

**Comment by srikanth-lingala** [comment]
Usually compressing the file should not lock it. If this is happening, then it needs to be changed. I will try to reproduce this. The difficulty in reproducing this issue is that the behaviour is highly dependent on OS and I do not have access to all OSs'. But I will give it a try.

**Comment by srikanth-lingala** [comment]
Can you provide me a way to reproduce this issue? I tried to lock a file on my mac with one program locking a file (via FileChannel.lock()), and other process trying to read the same file. I do not see any error in this case and it works fine. As mentioned earlier, this is probably highly dependent on OS. And also, if a process has intentionally locked a file (also from reading), isn't it then the right behaviour that the application trying to read the file throws an exception?

**Comment by srikanth-lingala** [comment]
Closing this issue as there is no further feedback on it. Please feel free to reopen if you have any further feedback for my post above.
