### ISSUE TITLE
Unix permissions are messed up after upgrading to 2.6.0 - part2

### ISSUE THREAD

**Issue by hugomprado** [srikanth-lingala/zip4j#266]
Based on this issue:
[Issue #231](https://github.com/srikanth-lingala/zip4j/issues/231)
Previously we were zipping files using ZipOutputStream and we were getting 664 permissions.
With the new fix (from v. 2.6.2) we are getting 600 permissions.
Our use case involves unzipping the file and leaving it in an sftp folder, then other users can get the unzipped file and download it to local machines.
This can't be done using 600, since the users trying to get the file are not owners.
Could you please add default perm to 664 (as was before) instead of 600 ?

Thanks

**Comment by srikanth-lingala** [comment]
I think the default unix permissions are 644. I would rather prefer 644 for default for zip4j. 664 will give write permission to group, and I am not sure if that is the right step to have it as a default.

**Comment by hugomprado** [comment]
Yes! That would be great! 644 works perfectly. Thanks Srikanth

**Comment by hugomprado** [comment]
Great! Looking forward to try out the new release!

**Comment by srikanth-lingala** [comment]
Issue fixed in v2.7.0 which was released today.
