### ISSUE TITLE
V2.6.4 zip4j in Android 11 os and Linux Kernel 5.4  Have permission problem

### ISSUE THREAD

**Issue by qq641472246** [srikanth-lingala/zip4j#267]
V2.6.4 zip4j in Android 11 os and Linux Kernel 5.4 , file cannot be read or written after decompression

Comment code FileUtil. applyPosixFileAttributes file permission is ok

![image](https://user-images.githubusercontent.com/6420415/102347097-e148d800-3fda-11eb-81b6-6d6c68a45c5b.png)

Hope the zip4j author can solve this problem

**Comment by qq641472246** [comment]
zipxx folder is Comment code FileUtil. applyPosixFileAttributes
zip folder is v2.6.4 zip4j source code

**Comment by srikanth-lingala** [comment]
zipi4j restores the permissions that are defined in the zip headers, and those permissions in file headers are taken from the file permissions when a zip file is created. If you want some other permissions than what zip4j restores you have to manually set them to the values you need.

**Comment by srikanth-lingala** [comment]
Closing this issue as there is no further feedback.
