### ISSUE TITLE
file attributes of zipped folders are not applied on extraction

### ISSUE THREAD

**Issue by schwammk** [srikanth-lingala/zip4j#268]
there is this piece of code in AbstractExtractFileTask.java

        if (fileHeader.isDirectory()) {  
            if (!outputFile.exists()) {  
                if (!outputFile.mkdirs()) {  
                    throw new ZipException("Could not create directory: " + outputFile);  
                }  
            }  
        } else if (isSymbolicLink(fileHeader)) {  

so whenever the extraction comes across a directory in the zip file, upon visiting or creating it the attributes stored in the zip won't get applied. I guess this could be fixed by the following (I successfully tested on Windows with hidden dirs):

        if (fileHeader.isDirectory()) {
            if (!outputFile.exists()) {
                if (!outputFile.mkdirs()) {
                    throw new ZipException("Could not create directory: " + outputFile);
                }
            }
            UnzipUtil.applyFileAttributes(fileHeader, outputFile);
        } else if (isSymbolicLink(fileHeader)) {

This would need some testing on Linux/Mac as well. Which I cannot do right now. Especially some obscure settings might prevent e.g. other files from being extracted into read-only folders afterwards etc.

**Comment by srikanth-lingala** [comment]
You are right. This file attributes should be applied in the if-block as you mentioned. I will test this on mac/linux and include a fix in the next release.

**Comment by srikanth-lingala** [comment]
Issue fixed in v2.7.0 which was released today.
