### ISSUE TITLE
use ZIP_STANDARD and password zipfile ,cannot unzip in linux

### ISSUE THREAD

**Issue by AustinKwang** [srikanth-lingala/zip4j#269]
use algorithm EncryptionMethod.ZIP_STANDARD and password to zip file , but cannot unzip file by linux unzip command.

**Comment by srikanth-lingala** [comment]
I do not have access to a linux machine, but I just tried it on a mac and the unzip worked fine for a zip file which is encrypted with ZIP_STANDARD. I wiil try to get access to a linux machine and test it

**Comment by srikanth-lingala** [comment]
I tried this on my raspberry pi (with Raspbian os which is based on linux), and it worked fine. Please try using latest version to test it. I also recommend using only ascii characters for password, as non-ascii characters is not supported by all zip tools. I am closing this issue, but please feel free to reopen if you still face this issue with the latest version of zip4j. If you reopen, let me know which flavour of linux you tested on (also any OS version info), and also the password you are using (to see if this is non-ascii).
