### ISSUE TITLE
Could not read corresponding local file header for file header: icons/com.android.bbk.lockscreen3.png

### ISSUE THREAD

**Issue by macheng-vivo** [srikanth-lingala/zip4j#272]
when i try ro extract a folder,it happend
![com android bbk lockscreen3](https://user-images.githubusercontent.com/76809736/103404447-8a243500-4b8e-11eb-8148-5e17034df042.png)

net.lingala.zip4j.exception.ZipException: Could not read corresponding local file header for file header: icons/com.android.bbk.lockscreen3.png
12-31 17:23:46.877 25728 27120 W System.err:    at net.lingala.zip4j.tasks.AbstractExtractFileTask.verifyNextEntry(AbstractExtractFileTask.java:140)
12-31 17:23:46.877 25728 27120 W System.err:    at net.lingala.zip4j.tasks.AbstractExtractFileTask.extractFile(AbstractExtractFileTask.java:52)
12-31 17:23:46.877 25728 27120 W System.err:    at net.lingala.zip4j.tasks.ExtractFileTask.executeTask(ExtractFileTask.java:39)
12-31 17:23:46.877 25728 27120 W System.err:    at net.lingala.zip4j.tasks.ExtractFileTask.executeTask(ExtractFileTask.java:21)
12-31 17:23:46.877 25728 27120 W System.err:    at net.lingala.zip4j.tasks.AsyncZipTask.performTaskWithErrorHandling(AsyncZipTask.java:46)
12-31 17:23:46.877 25728 27120 W System.err:    at net.lingala.zip4j.tasks.AsyncZipTask.execute(AsyncZipTask.java:40)
12-31 17:23:46.877 25728 27120 W System.err:    at net.lingala.zip4j.ZipFile.extractFile(ZipFile.java:485)
12-31 17:23:46.877 25728 27120 W System.err:    at net.lingala.zip4j.ZipFile.extractFile(ZipFile.java:549)
12-31 17:23:46.877 25728 27120 W System.err:    at net.lingala.zip4j.ZipFile.extractFile(ZipFile.java:508)
12-31 17:23:46.877 25728 27120 W System.err:    at com.bbk.theme.utils.ApplyThemeHelper.installCurrentRes(ApplyThemeHelper.java:704)
12-31 17:23:46.877 25728 27120 W System.err:    at com.bbk.theme.utils.ApplyThemeHelper.copyResFiles(ApplyThemeHelper.java:214)
12-31 17:23:46.878 25728 27120 W System.err:    at com.bbk.theme.utils.ResApplyManager$9.run(ResApplyManager.java:722)
12-31 17:23:46.878 25728 27120 W System.err:    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
12-31 17:23:46.878 25728 27120 W System.err:    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
12-31 17:23:46.878 25728 27120 W System.err:    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-31 17:23:46.878 25728 27120 W System.err:    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-31 17:23:46.878 25728 27120 W System.err:    at java.lang.Thread.run(Thread.java:764)

**Comment by srikanth-lingala** [comment]
Unfortunately, for this case, without the zip file, it would be quite difficult to say what went wrong. Would it be possible for you to attach the zip filie?

**Comment by srikanth-lingala** [comment]
@macheng-vivo As posted above, can you attach a sample zip file for which you see this issue? If you can share it, but do not want to post to publicly, you can also send me an email. My email id is in the [README][1].

[1]: https://github.com/srikanth-lingala/zip4j/blob/master/README.md#faq

**Comment by srikanth-lingala** [comment]
Closing this issue as there is no further feedback for my posts above.
