### ISSUE TITLE
[PLEASE HELP] Creating ZipFile from Inputstreem to bypass android permission problems

### ISSUE THREAD

**Issue by gilshallem** [srikanth-lingala/zip4j#273]
Hi.
In android 11 scoped storage is forced.
Please please help!
By allowing inputstream instead of file as input it will be solved as we can get an inputstream from DocumentFil (android storage api)

Is there a current way to use input/outputstream to compress/decompress a file with a password?

Thank you

**Comment by srikanth-lingala** [comment]
So you mean something like `new ZipFile(InputStream)`? Is it not possible to get a file handle anymore from Android 11?

**Comment by gilshallem** [comment]
Exactly.
In android 11 you have to have a new special permission that most apps can not have, or you can use their own storage framework which can only provide inputstream/outputstream 

I'm in the process of converting all my code including the use of ZipInputStream instead of ZipFile. however, it will be much easier if there was such a constructor for ZipFile

**Comment by srikanth-lingala** [comment]
ZipFile needs a seekable stream, ideally a RandomAccessFile which can seek to any position in a file without reading through the complete file. This won't work with Input/Outputstream. Unfrotunately what you ask for can't be done with ZipFile and Input/OutputStream. The only option in this case is to use ZipInput/Output Stream.

**Comment by srikanth-lingala** [comment]
Closing this issue, as this feature cannot be implemented for the reason mentioned above.
