### ISSUE TITLE
addFolder not preserving folder tree

### ISSUE THREAD

**Issue by nicolabeghin** [srikanth-lingala/zip4j#275]
Hi 
we're experiencing a weird behavior, don't know if it's expected behavior on latest 2.6.4.

Specifically, we have this folder called `cpqfixes` containing a given folder tree
![image](https://user-images.githubusercontent.com/2743637/104341757-6fd94800-54fa-11eb-864a-87760d1225c6.png)

When using 

    ZipParameters zipParameters = new ZipParameters();
    zipParameters.setIncludeRootFolder(true);
    new ZipFile(zipFile).addFolder(folder, zipParameters);

the output ZIP [cpqfixes.zip](https://github.com/srikanth-lingala/zip4j/files/5803410/cpqfixes.zip) does not contain intermediate parent `resources` folder

    unzip cpqfixes.zip -d tmp

![image](https://user-images.githubusercontent.com/2743637/104341946-9eefb980-54fa-11eb-9f05-b8be68fac504.png)

If we compress the folder through Windows/WinRAR/etc the output file [cpqfixes.zip](https://github.com/srikanth-lingala/zip4j/files/5803405/cpqfixes.zip) preserves the structure. 

Any hint on why this is happening? 

thanks!
nicola

**Comment by nicolabeghin** [comment]
FYI we tried the workaround in https://github.com/srikanth-lingala/zip4j/issues/153#issuecomment-595913182 with [no luck](https://github.com/srikanth-lingala/zip4j/files/5803586/cpqfixes.zip):

![image](https://user-images.githubusercontent.com/2743637/104346171-64d4e680-54ff-11eb-9a0e-28484d4d3d56.png)

**Comment by srikanth-lingala** [comment]
I tried it on my machine with your attachment and it works fine. This was the code I used:

```
@Test
public void testIssueAdd() throws IOException {
  File folderToAdd = new File(BASE_DIR + "cpqfixes/");
  ZipParameters zipParameters = new ZipParameters();
  zipParameters.setIncludeRootFolder(true);
  new ZipFile(BASE_DIR + "test.zip").addFolder(folderToAdd, zipParameters);
}
```

And here is the folder structure after extracting the zip file:

<img width="365" alt="Bildschirmfoto 2021-01-12 um 20 42 23" src="https://user-images.githubusercontent.com/3450302/104364273-b046bf00-5516-11eb-93e1-b4d3befce661.png">


I suspect this might be something related to the folder being resolved in the end from the folder you pass in. I mean, in some cases, your folder will be resolved to a different folder than what you expect it to be. Example: canonical path != absolute path. Another example: a folder pointing to the resources folder in a typical maven project points to the folder under the resources in some cases I think, although I am not completely sure about this. Could something like this be in play here?

**Comment by nicolabeghin** [comment]
thanks @srikanth-lingala the only change I see from your test is that you used the `ZipFile(String)` constructor while we're using the `ZipFile(File)` constructor. Could that explain the different behavior?

**Comment by srikanth-lingala** [comment]
You mean to say that it worked fine for you with the `String` constructor but did not work for you with the `File` constructor? In zip4j, as you can see [here][1] a call to `ZipFile(String)` just initialises a `File` object from that string and calls the `ZipFile(File)` constructor. If I understood you right that it worked fine with `String` constructor, it is hard for me to say why it worked without knowing your code. My best guess is that something like absolute path, canonical path are in play, but again, this is just a wild guess.

[1]: https://github.com/srikanth-lingala/zip4j/blob/master/src/main/java/net/lingala/zip4j/ZipFile.java#L93

**Comment by nicolabeghin** [comment]
In the end I had to revert to use standard Java code to create the ZIP since I had to close this. Thanks anyway, I'm using the library successfully in other projects!
