### ISSUE TITLE
workCompleted gets bigger than totalWork in the ProgressMonitor

### ISSUE THREAD

**Issue by joorei** [srikanth-lingala/zip4j#28]
This uses the **compressed** size as `totalWork` in the `progressMonitor`.
https://github.com/srikanth-lingala/zip4j/blob/7dc3f9a061322f1183c2edcabc80e381d4ce8353/src/main/java/net/lingala/zip4j/tasks/ExtractFileTask.java#L38

But this updates the `workCompleted` in the `progressMonitor` with the **uncompressed** size.
https://github.com/srikanth-lingala/zip4j/blob/7dc3f9a061322f1183c2edcabc80e381d4ce8353/src/main/java/net/lingala/zip4j/tasks/AbstractExtractFileTask.java#L72

This results in
https://github.com/srikanth-lingala/zip4j/blob/7dc3f9a061322f1183c2edcabc80e381d4ce8353/src/main/java/net/lingala/zip4j/progress/ProgressMonitor.java#L36
getting bigger than
https://github.com/srikanth-lingala/zip4j/blob/7dc3f9a061322f1183c2edcabc80e381d4ce8353/src/main/java/net/lingala/zip4j/progress/ProgressMonitor.java#L34

**Comment by srikanth-lingala** [comment]
Fixed with https://github.com/srikanth-lingala/zip4j/pull/30

**Comment by srikanth-lingala** [comment]
Fixed in v2.1.2
