### ISSUE TITLE
How to list zip entries using ZipInputStream for Android 11 SAF?

### ISSUE THREAD

**Issue by EvolveWorx** [srikanth-lingala/zip4j#285]
Thank you so much for this amazing library, I need a little help, I need to list files from a zip archive but without using any File or ZipFile objects as I'm developing for Android 11 that uses Storage Access Framework (SAF) which deals with streams only; I was able to list a zip archive contents using the ZipEntry from java.util.zip.ZipEntry; but that does not work for a password protected archive that uses LocalFileHeader.

Is there a way to get a list of entries for a password protected zip archive created with your library?

Thank you

**Comment by srikanth-lingala** [comment]
Yes, that should be possible. Here is a sample code:

```
@Test
public void listFiles() throws IOException {
  try(InputStream sourceStream = new FileInputStream(new File("test.zip"));
      ZipInputStream zipInputStream = new ZipInputStream(sourceStream, "password".toCharArray())) {
    LocalFileHeader localFileHeader;

    while ((localFileHeader = zipInputStream.getNextEntry()) != null) {
      System.out.println(localFileHeader.getFileName());
    }
  }
}
```

**Comment by EvolveWorx** [comment]
Still not working

Here's the code I used, you can also check the attached test.zip (Password: abc123)

[test.zip](https://github.com/srikanth-lingala/zip4j/files/5975716/test.zip)

`
            List<String> fileNameList = new ArrayList<>();
            ContentResolver resolver = getContentResolver();

            InputStream inputStream = resolver.openInputStream(srcFile.getUri());

            try (ZipInputStream zipInputStream = new ZipInputStream(inputStream, "abc123".toCharArray()))
            {
                LocalFileHeader localFileHeader;

                while ((localFileHeader = zipInputStream.getNextEntry()) != null)
                {
                    fileNameList.add(localFileHeader.getFileName());
                    System.out.println(localFileHeader.getFileName());
                }
            }
`

**Comment by EvolveWorx** [comment]
I don't know if you're familiar with SAF, the problem is that it uses URIs (content URI) like this:
content://com.android.externalstorage.documents/tree/primary%3A/document/primary%3A1%20Test%2Ftest.zip

so the " new File("test.zip") " is not gonna work

**Comment by srikanth-lingala** [comment]
> so the " new File("test.zip") " is not gonna work

I created the `new File()` as a sample code. The inputstream in my example was obviously supposed to be replaced with the inputstream you get in your Android code. 

> I don't know if you're familiar with SAF

I am not unfortunately. I am not familiar with Android.  All I can say from zip4j's perspective is that ZipInputStream can take an InputStream of the underlying zip file and read the contents of it.  In fact, on my mac, when I run the sample code from my post above against your test.zip, I get the following output,:

```
ABC 009.jpg
Folder 2/ABC 003.jpg
Folder 2/ABC 004.jpg
Folder 2/Folder 3/ABC 005.jpg
Folder 2/Folder 3/ABC 006.jpg
Folder 2/Folder 3/Folder 4/ABC 007.jpg
Folder 2/Folder 3/Folder 4/ABC 008.jpg
Folder 1/ABC 001.jpg
Folder 1/ABC 002.jpg
```

What do you mean by `still does not work`? What output do you get? Do you get any exception?

**Comment by EvolveWorx** [comment]
Yes I did pass an inputstream, you can see it in my code above, I'm not getting any exception, the only output I get is the first file only which is:

`ABC 009.jpg
`

I'm not getting the remaining files

**Comment by srikanth-lingala** [comment]
> Can you try passing that test.zip as an inputstream; you might be able to reproduce that scenario.

I did pass it as an inputstream. On my mac, I have to initialise it as a `FileInputStream`, as I cannot work with Android's `ContentResolver`. I tried with a small variation to my sample code, and used URL.openStream() to stream the zip contents, and it still works fine and I get the same output from my last post above. Here is the variation of my code:

```
@Test
  public void listFiles() throws IOException {
    try(InputStream inputStream = TestUtils.class.getResource("/test-files/test.zip").openStream();
        ZipInputStream zipInputStream = new ZipInputStream(inputStream, "abc123".toCharArray())) {
      
      LocalFileHeader localFileHeader;
      while ((localFileHeader = zipInputStream.getNextEntry()) != null) {
        System.out.println(localFileHeader.getFileName());
      }
    }
  }
```

This issue seems to be happening only with the `InputStream` which Android's `ContentResolver` creates. Can you send me a working Android project to reproduce this issue, and also let me know the steps to setup my environment to run this project? I can try to help if I am able to reproduce this issue.

**Comment by EvolveWorx** [comment]
I don't think it has some to do with the Android's `InputStream` because it's working fine with `java.util.zip.ZipInputStream`
Anyway thank you very much, you have done more than enough, and thanks again for this library 

I'll try to find a work around, I'll let you know if I get to something, I'll have to dig some more in the nasty Android 11 SAF

Should I close this issue or you have to close it (it's my first on github)?

**Comment by EvolveWorx** [comment]
It seems that you've fixed this issue; which is similar to:
https://github.com/srikanth-lingala/zip4j/issues/279

Is there a way to skip reading all the bytes for each entry to list files/entries faster?

Thank you very much

**Comment by srikanth-lingala** [comment]
With streams, unfortunately, there is no other option than to read the complete bytes.

**Comment by EvolveWorx** [comment]
That's OK, Thank you very much Srikanth
