### ISSUE TITLE
encrypt decrypt without password

### ISSUE THREAD

**Issue by croo** [srikanth-lingala/zip4j#295]
Is  there a way to encrypt a zip file witout a password, only using private/public keypairs?
I want to make a zip file which can be opened only by a private key.

**Comment by srikanth-lingala** [comment]
Yes there is. This feature of zip is called Strong Encryption. But this feature is PKWARE Proprietary Technology and is a patent held by them and requires license from them and that is probably the reason we don't see this feature in a lot of zip utilities. Here is a quote from the zip specification:

> 7.0.1 Portions of the Strong Encryption technology defined in this 
>  specification are covered under patents and pending patent applications.
>  Refer to the section in this document entitled "Incorporating 
>  PKWARE Proprietary Technology into Your Product" for more information.
