### ISSUE TITLE
Info about createSplitZipFile

### ISSUE THREAD

**Issue by jaisalj** [srikanth-lingala/zip4j#297]
Hi, 
I want to know what kind of division createSplitZipFile method does ?
We want to do binary division of a zip file. Will this method help in achieving that ?

Regards,
Jaisal

**Comment by srikanth-lingala** [comment]
Yes, you can merge split zip files with zip4j. [Here][1] is the documentation and a sample.

[1]: https://github.com/srikanth-lingala/zip4j#merging-split-zip-files-into-a-single-zip

**Comment by srikanth-lingala** [comment]
What do you mean by binary division of a zip file? If you mean, just take a zip file and split it into several parts, unfortunately that won't work because a split zip file has header information which needs to be updated with the split info.

**Comment by jaisalj** [comment]
Okay, means the split files that are created contains some additional information also ?

**Comment by oleg-cherednik** [comment]
Looks like its about `7-zip` like splitting, when files have name format `*.zip.001`. In this format split parts do not have separate header.

**Comment by srikanth-lingala** [comment]
zip4j will allow you to read the binary split zip files from 7zip (*.zip.001) but it does not allow creating such binary split zip. Binary splitting a zip file is not according to a zip specification. For whatever reason, 7zip uses that way to split zip files. If you split a zip file that way, it will not be compatible across other zip tools as this is not zip standard compliant. 

So, a short answer is, sure you can do it (not with zip4j though), but it will not be zip standard compliant.

**Comment by jaisalj** [comment]
Okay thanks for the clarification.
