### ISSUE TITLE
ZipException: File header and local file header mismatch

### ISSUE THREAD

**Issue by cyneck** [srikanth-lingala/zip4j#298]
![image](https://user-images.githubusercontent.com/7006221/109930256-67cfa480-7d02-11eb-902f-1cc5621dc720.png)
 I just unzip a encrypted file ，password is  correct！The  file  already unzip actually！

**Comment by srikanth-lingala** [comment]
Would it be possible to attach the zip file? And also which version of zip4j are you using?

**Comment by cyneck** [comment]
ok
