### ISSUE TITLE
Cannot extract folders

### ISSUE THREAD

**Issue by Dominicentek** [srikanth-lingala/zip4j#300]
I cannot extract folders from a zip file
`new ZipFile("file.zip").extractFile("folderInsideZip", "extracted");`
it throws `ZipException`.
And the readme says you can extract folders using `extractFile()` method.

**Comment by Ningxxxl** [comment]
I have the same problem.

**Comment by srikanth-lingala** [comment]
It worked fine for me. Below is the code I used. I have also attached the sample.zip I used for testing (which is a zip of the test-files folder in resources of zip4j).

```
new ZipFile("sample.zip").extractFile("test-files/sample_directory/", OUTPUT_DIR);
```

[sample.zip](https://github.com/srikanth-lingala/zip4j/files/6263583/sample.zip)

**Comment by srikanth-lingala** [comment]
Closing this issue as I could not reproduce it, and there is no feedback from the user.
