### ISSUE TITLE
read from zipstream with password

### ISSUE THREAD

**Issue by black-06** [srikanth-lingala/zip4j#301]
Hi,i want to read file from ZipInputstream.
This zip may be password protected or not,
and the password can also be any one of the known passwords.

I saw all the construction methods of ZipInputStream,but there is no suitable one.
What should I do?
Is there a method similar to ZipFile.isEncrypted and setPassword.
Thank you.

**Comment by srikanth-lingala** [comment]
Below is the equivalent of `ZipFile.isEncrypted`:

```
ZipInputStream zipInputStream = new ZipInputStream(...);
LocalFileHeader localFileHeader = zipInputStream.getNextEntry();
localFileHeader.isEncrypted();
```

But unfortunately, once the password is set via ZipInputStream`s constructor, it cannot be changed again. I will add a feature to also set the password later via a `ZipInputStream.setPassword(char[])` method. I will include this in the next release.

**Comment by srikanth-lingala** [comment]
Feature added in v2.8.0 released today.
