### ISSUE TITLE
zip4j 只对压缩包内文件 加密，无法为压缩包本身加密问题。

### ISSUE THREAD

**Issue by LiSanXiaoWei** [srikanth-lingala/zip4j#302]
如何解决，现在使用
zipFile的addStream(inputString,parameters)  方法，
zipFile.createZipFile(file, parameters);       方法

结果都是加进去文件加密 。我想要zip包加密 而不是里面内容加密。
 
而我想做到的结果是，最后生成一个“加密！”的zip文件，压缩包里面是文件。

**Comment by srikanth-lingala** [comment]
Please post your messages in English

**Comment by LiSanXiaoWei** [comment]
How to solve it now
zipfile.addstream (inputstring, parameters); method
zipFile.createZipFile (file, parameters); method
Generated compressed package, just inside the file encryption.

And what I want is,
Generate an encrypted zip file,
You need a password to click on the package.
