### ISSUE TITLE
file name encoding problem

### ISSUE THREAD

**Issue by kebenart** [srikanth-lingala/zip4j#304]
A compressed file contains the utf8 encoded file name and the gbk encoded file name. When reading, the utf8 encoding is set, and then the gbk encoded file name will be garbled `����`, how to deal with it

**Comment by kebenart** [comment]
why  function `decodeStringWithCharset` not  to perform first isUtf8Encoded?

If a different encoding is set while reading a compressed file, the internal filename will be forced to change to another encoding, even if it is incorrect. There is no support for setting the filename encoding


`  public static String decodeStringWithCharset(byte[] data, boolean isUtf8Encoded, Charset charset) {
    if (charset != null) {
      return new String(data, charset);
    }

    if (isUtf8Encoded) {
      return new String(data, InternalZipConstants.CHARSET_UTF_8);
    }

    try {
      return new String(data, ZIP_STANDARD_CHARSET_NAME);
    } catch (UnsupportedEncodingException e) {
      return new String(data);
    }
  }`

**Comment by srikanth-lingala** [comment]
If you know the file names upfront, you can first use utf-8 as the charset, and then user GBK  as the charset for the file which is GBK encoded. Since  zip4j uses utf-8 as default charset, you can skip setting that. Something like this:

```
ZipFile zipFile = new ZipFile("sample.zip");
zipFile.extractFile("file-name-with-utf8", OUTPUT_DIR);
zipFile.setCharset(Charset.forName("GBK"));
zipFile.extractFile("gbk-file-name", OUTPUT_DIR);
```

**Comment by kebenart** [comment]
Thank you for your reply. Unfortunately, I cannot know the encoding of the internal file. I hope to automatically recognize the encoding of the file when decompressing it. So I simply modified the source code. I checked the character set decoding again.  isFileNameUTF8Encoded Is the judgment accurate?








     public static String decodeStringWithCharset(byte[] data, boolean isUtf8Encoded, Charset charset) {
        if (isUtf8Encoded || isUtf8(data)) {
            return new String(data, InternalZipConstants.CHARSET_UTF_8);
        }

        if (charset != null) {
            return new String(data, charset);
        }

        try {
            return new String(data, ZIP_STANDARD_CHARSET_NAME);
        } catch (UnsupportedEncodingException e) {
            return new String(data);
        }
    }


    private static boolean isUtf8(byte[] rawtext) {
        int score = 0;
        int i, rawtextlen = 0;
        int goodbytes = 0, asciibytes = 0;
        // Maybe also use UTF8 Byte Order Mark: EF BB BF
        // Check to see if characters fit into acceptable ranges
        rawtextlen = rawtext.length;
        for (i = 0; i < rawtextlen; i++) {
            if ((rawtext[i] & (byte) 0x7F) == rawtext[i]) {
                // 最高位是0的ASCII字符
                asciibytes++;
                // Ignore ASCII, can throw off count
            } else if (-64 <= rawtext[i] && rawtext[i] <= -33
                    //-0x40~-0x21
                    && // Two bytes
                    i + 1 < rawtextlen && -128 <= rawtext[i + 1]
                    && rawtext[i + 1] <= -65) {
                goodbytes += 2;
                i++;
            } else if (-32 <= rawtext[i]
                    && rawtext[i] <= -17
                    && // Three bytes
                    i + 2 < rawtextlen && -128 <= rawtext[i + 1]
                    && rawtext[i + 1] <= -65 && -128 <= rawtext[i + 2]
                    && rawtext[i + 2] <= -65) {
                goodbytes += 3;
                i += 2;
            }
        }
        if (asciibytes == rawtextlen) {
            return false;
        }
        score = 100 * goodbytes / (rawtextlen - asciibytes);
        // If not above 98, reduce to zero to prevent coincidental matches
        // Allows for some (few) bad formed sequences
        if (score > 98) {
            return true;
        } else if (score > 95 && goodbytes > 30) {
            return true;
        } else {
            return false;
        }
    }

**Comment by jimfcarroll** [comment]
I have a similar issue. I have a zip file where the file name contains the string:

```
Français
```
The 'ç' is encoded: 0x63cca7

The filename is correctly decoded when I use org.apache.commons.compress.archivers.zip.ZipArchiveInputStream. However, when I use zip4j's ZipInputStream I get:

```
Franc╠ºais
```

where theses bytes are there instead: 0x63e295a0c2ba

**Comment by srikanth-lingala** [comment]
There have been several changes to the charset and file name decoding. I suggest anyone with similar issue to try with latest version and either reopen or create a new issue if you still face a similar issue.
