### ISSUE TITLE
Chinese garbled

### ISSUE THREAD

**Issue by andotorg** [srikanth-lingala/zip4j#305]
Chinese garbled

zip4j than IOUtils slow.

It's nearly double full.

**Comment by srikanth-lingala** [comment]
Can you please be a bit more specific about your issue? Your one-liners are really not helpful to understand what your issue is. I can probably guess that the Chinese names come out as garbled text, but is it file names or file comment? Which version of zip4j do you use? Do you set the charset to GBK? Sample code? Sample zip file?

**Comment by muzhix** [comment]
may be you can try set charset to `GBK`.
```
ZipFile zipFile = new ZipFile(file);
zipFile.setCharset(Charset.forName("GBK"));
```
here is my test result:
![image](https://user-images.githubusercontent.com/35456265/114492575-6bccdb80-9c4b-11eb-9c38-a0c2c2d26ca2.png)

**Comment by andotorg** [comment]
> Can you please be a bit more specific about your issue? Your one-liners are really not helpful to understand what your issue is. I can probably guess that the Chinese names come out as garbled text, but is it file names or file comment? Which version of zip4j do you use? Do you set the charset to GBK? Sample code? Sample zip file?

sorry,  is file name, not set GBK, i set encode is utf-8.

**Comment by andotorg** [comment]
> may be you can set charset to `GBK`.
> 
> ```
> ZipFile zipFile = new ZipFile(file);
> zipFile.setCharset(Charset.forName("GBK"));
> ```
> 
> here is my test result:
> ![image](https://user-images.githubusercontent.com/35456265/114492575-6bccdb80-9c4b-11eb-9c38-a0c2c2d26ca2.png)

ok. thanks.

**Comment by srikanth-lingala** [comment]
If I understood you right, your issue seems to be resolved now after you pass in the charset. I am closing this issue. Please feel free to reopen with more info if your issue is still not resolved.
