### ISSUE TITLE
could not read corresponding local filel header

### ISSUE THREAD

**Issue by qiyanlong** [srikanth-lingala/zip4j#306]
At  RNZipArchiveModule.java line 97 need change to 
 
if (!fileHeader.isDirectory()) {
              zipFile.extractFile(fileHeader, destDirectory);
              extractedFileNames.add(fileHeader.getFileName());
            }

**Comment by srikanth-lingala** [comment]
Which `RNZipArchiveModule` do you mean? There is no such class in zip4j.

**Comment by srikanth-lingala** [comment]
Closing this issue as this seems to be not related to zip4j. Please feel free to reopen with more info if you think otherwise.
