### ISSUE TITLE
No static method metafactory(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodHandle;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/CallSite; in class Ljava/lang/invoke/LambdaMetafactory; or its super classes (declaration of 'java.lang.invoke.LambdaMetafactory' appears in /apex/com.android.runtime/javalib/core-oj.jar)

### ISSUE THREAD

**Issue by HarishKumar7** [srikanth-lingala/zip4j#310]

**Comment by HarishKumar7** [comment]
--------- beginning of crash
04-20 14:16:02.904 E/AndroidRuntime(30855): FATAL EXCEPTION: AsyncTask #1
04-20 14:16:02.904 E/AndroidRuntime(30855): Process: com.kodiak.ui, PID: 30855
04-20 14:16:02.904 E/AndroidRuntime(30855): java.lang.RuntimeException: An error occurred while executing doInBackground()
04-20 14:16:02.904 E/AndroidRuntime(30855): 	at android.os.AsyncTask$4.done(AsyncTask.java:399)
04-20 14:16:02.904 E/AndroidRuntime(30855): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
04-20 14:16:02.904 E/AndroidRuntime(30855): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
04-20 14:16:02.904 E/AndroidRuntime(30855): 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
04-20 14:16:02.904 E/AndroidRuntime(30855): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
04-20 14:16:02.904 E/AndroidRuntime(30855): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
04-20 14:16:02.904 E/AndroidRuntime(30855): 	at java.lang.Thread.run(Thread.java:919)
04-20 14:16:02.904 E/AndroidRuntime(30855): Caused by: java.lang.NoSuchMethodError: No static method metafactory(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodHandle;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/CallSite; in class Ljava/lang/invoke/LambdaMetafactory; or its super classes (declaration of 'java.lang.invoke.LambdaMetafactory' appears in /apex/com.android.runtime/javalib/core-oj.jar)
04-20 14:16:02.904 E/AndroidRuntime(30855): 	at net.lingala.zip4j.tasks.AbstractModifyFileTask.cloneAndSortFileHeadersByOffset(AbstractModifyFileTask.java:78)
04-20 14:16:02.904 E/AndroidRuntime(30855): 	at net.lingala.zip4j.tasks.RemoveFilesFromZipTask.executeTask(RemoveFilesFromZipTask.java:52)
04-20 14:16:02.904 E/AndroidRuntime(30855): 	at net.lingala.zip4j.tasks.RemoveFilesFromZipTask.executeTask(RemoveFilesFromZipTask.java:21)
04-20 14:16:02.904 E/AndroidRuntime(30855): 	at net.lingala.zip4j.tasks.AsyncZipTask.performTaskWithErrorHandling(AsyncZipTask.java:46)
04-20 14:16:02.904 E/AndroidRuntime(30855): 	at net.lingala.zip4j.tasks.AsyncZipTask.execute(AsyncZipTask.java:40)
04-20 14:16:02.904 E/AndroidRuntime(30855): 	at net.lingala.zip4j.tasks.AbstractAddFileToZipTask.removeFile(AbstractAddFileToZipTask.java:271)
04-20 14:16:02.904 E/AndroidRuntime(30855): 	at net.lingala.zip4j.tasks.AbstractAddFileToZipTask.removeFilesIfExists(AbstractAddFileToZipTask.java:254)
04-20 14:16:02.904 E/AndroidRuntime(30855): 	at net.lingala.zip4j.tasks.AbstractAddFileToZipTask.addFilesToZip(AbstractAddFileToZipTask.java:65)
04-20 14:16:02.904 E/AndroidRuntime(30855): 	at net.lingala.zip4j.tasks.AddFilesToZipTask.executeTask(AddFilesToZipTask.java:27)
04-20 14:16:02.904 E/AndroidRuntime(30855): 	at net.lingala.zip4j.tasks.AddFilesToZipTask.executeTask(AddFilesToZipTask.java:15)
04-20 14:16:02.904 E/AndroidRuntime(30855): 	at net.lingala.zip4j.tasks.AsyncZipTask.performTaskWithErrorHandling(AsyncZipTask.java:46)
04-20 14:16:02.904 E/AndroidRuntime(30855): 	at net.lingala.zip4j.tasks.AsyncZipTask.execute(AsyncZipTask.java:40)
04-20 14:16:02.904 E/AndroidRuntime(30855): 	at net.lingala.zip4j.ZipFile.addFiles(ZipFile.java:319)

**Comment by srikanth-lingala** [comment]
Which JDK and Android version are you using?

**Comment by srikanth-lingala** [comment]
Closing this issue, as there is no further feedback from OP. Please feel free to reopen if you have any update.
