### ISSUE TITLE
when call the ZipFile.removefile method  have some problems about building zipmodel for remove

### ISSUE THREAD

**Issue by yuki-naki** [srikanth-lingala/zip4j#315]
a.zip inside have two file 
a.js
a.json 

when try remove file (a.js)

ZipFile zip = new ZipFile("a,zip");
zip.removeFile("a.js");

will remove a.js and a.json together

**Comment by srikanth-lingala** [comment]
Thanks for reporting this issue. I was able to reproduce it. I will include a fix in the next release.

**Comment by srikanth-lingala** [comment]
Fixed in v2.8.0 released today.
