### ISSUE TITLE
File fails CRC check

### ISSUE THREAD

**Issue by Kalyansunku** [srikanth-lingala/zip4j#318]
Hi I am using 2.7.0 version.

I created a password protected zip file with some pdf files using streams.

Following  are the Zip parameters
Compression method: Deflate
Encryption method: AES with key strength 256

While extracting the zip file it is throwing following error

File fails CRC check. I added 8 files to the zip. But when I view the zip file using IZArc it is only showing file.

The size of zip is showing all pdf files size.

Don’t understand why it is happening. Could you please help
![image](https://user-images.githubusercontent.com/84067097/117938061-41427100-b324-11eb-9f8f-6670698a6703.jpg)

**Comment by srikanth-lingala** [comment]
Do you close your zipOutputStream? I do not see the close call on this stream. Can you post the complete code please? Would it also be possible to attach a sample zip file?

**Comment by Kalyansunku** [comment]
Thank you @srikanth-lingala 

Whatever you mentioned is correct. I am reading the bytes from zip file before closing it. 

After modifying the code it is working fine.
