### ISSUE TITLE
ProgressMonitor resets itself when a task successfully or unsuccessfully finishes

### ISSUE THREAD

**Issue by joorei** [srikanth-lingala/zip4j#32]
The ProgressMonitor resets itself when a task successfully or unsuccessfully finishes. This purges valuable data needed after the task is done.
https://github.com/srikanth-lingala/zip4j/blob/7dc3f9a061322f1183c2edcabc80e381d4ce8353/src/main/java/net/lingala/zip4j/progress/ProgressMonitor.java#L71
https://github.com/srikanth-lingala/zip4j/blob/7dc3f9a061322f1183c2edcabc80e381d4ce8353/src/main/java/net/lingala/zip4j/progress/ProgressMonitor.java#L77

The ProgressManager should not automatically reset when a task is ended but only when a new task is started.

**Comment by srikanth-lingala** [comment]
Fixed in v2.1.2
