### ISSUE TITLE
Kotlin Support

### ISSUE THREAD

**Issue by Vicviral** [srikanth-lingala/zip4j#323]
I tried using it in Kotlin, It doesn't seem to have support for it.

**Comment by srikanth-lingala** [comment]
What do you mean "doesn't have support for it". zip4j is written in Java, and AFAIK, Java code can be called from Kotlin. [Reference](https://stackoverflow.com/questions/44472214/can-i-use-third-party-java-libraries-jar-for-android-development-with-kotlin)
