### ISSUE TITLE
Decrease the JDK version

### ISSUE THREAD

**Issue by cp214899** [srikanth-lingala/zip4j#324]
How to reduce to JDK7 execution when using ZIP4J-2.8.0.JAR?
The version was too high when I executed it.
My own JDK7 cannot be upgraded to JDK8.

**Comment by srikanth-lingala** [comment]
Zip4j is currently built for JDK 8 or higher. For JDK 7, I need to adjust the target version in maven and rebuild it. But I need to analyse this.

**Comment by cp214899** [comment]
Thanks

**Comment by srikanth-lingala** [comment]
Fixed in v2.9.0 released today.

**Comment by cp214899** [comment]
Thanks

**Comment by corporate-gadfly** [comment]
Seems like a step backwards. Java 7 went EOL in July 2015.

**Comment by sgflt** [comment]
I would set minimal requirement to JDK 11 with JDK 17 compatibility.

**Comment by EwoutH** [comment]
There now are a few versions that JDK 7 users can use, so raising the minimum version for the next release could be fine since users on JDK 7 or 8 can just use the current release.
