### ISSUE TITLE
[Feature Request] close() on ZipFile to close previously returned `InputStream`´s

### ISSUE THREAD

**Issue by nils91** [srikanth-lingala/zip4j#327]
Hi,

as far as i can tell there´s currently no way to close all InputStreams returned by `getInputStream()` on `ZipFile` at once, each stream needs to be closed individually. A `close()` on the ZipFile class itself would help to ensure that all input streams are closed and the zip file is 'closed'.
The `java.util.ZipFile` class has a close: https://docs.oracle.com/en/java/javase/16/docs/api/java.base/java/util/zip/ZipFile.html#close()

Thanks!

**Comment by srikanth-lingala** [comment]
Feature implemented. I will include this in the next release.

**Comment by srikanth-lingala** [comment]
@nils91 Please leave this issue open. I will close this once the release is done.

**Comment by srikanth-lingala** [comment]
Feature added in v2.9.0 released today.
