### ISSUE TITLE
zip4J -Regarding the issue of reading files

### ISSUE THREAD

**Issue by gaoyibing111** [srikanth-lingala/zip4j#332]
Very happy to see your reply, Why can't this code read a text file of only 30KB at a time? No matter how big I set the buffer, it will only read 1024*21 byte text data. Master, please advise.

e.g.

```
ZipInputStream is = zipFile.getInputStream(fileHeader);
                byte[] buff = new byte[1048576];
                is.read(buff)                
                a = new String(buff);
                is.close();
                is = null;
```

**Comment by srikanth-lingala** [comment]
This depends also on your operating system. It is not always guaranteed that a stream.read() method reads the complete contents into the memory. If you want to have. complete content in a byte array, you need to loop and store into an. array until the read method returns -1. As I wrote earlier, there could be several possible reasons why the complete content is not read at the same time, and it also depends on the operating system.
