### ISSUE TITLE
Split zip - Could not read corresponding local file header for file header

### ISSUE THREAD

**Issue by arekfajdek** [srikanth-lingala/zip4j#333]
Hey! I have an issue with the split zip file created by 7z.
Zip file contains 1 image, 1 text file, and I'm doing a simple extraction:
`try (var zipFile = new ZipFile("correctPathToZip\\some.zip.001")) {
                zipFile.extractAll("pathWhereToUnzip");
            }`

part1 and part2 are in the same folder. Image is extracted correctly, but for the text file I'm getting

`net.lingala.zip4j.exception.ZipException: Could not read corresponding local file header for file header: some/test.log`

I have attached my taste case. It seems like an issue in zip4j but I'm not 100% sure about it. 
It could be related to a small text file. 

Any idea what is the root cause of this issue?
[testCase.zip](https://github.com/srikanth-lingala/zip4j/files/6785075/testCase.zip)

**Comment by srikanth-lingala** [comment]
Thanks for the zip file. I was able to reproduce it. I will look into whats going wrong here.

**Comment by johnwongapi** [comment]
Hi, i faced the some exception on the above split zip.
It is created via 7zip software, we may need to take a look on code part about handling 7zip split.

**Comment by srikanth-lingala** [comment]
I am currently working on a fix for this. I will include the fix in the next release.

**Comment by srikanth-lingala** [comment]
Fixed in v2.11.0 released today
