### ISSUE TITLE
Zip file extraction

### ISSUE THREAD

**Issue by EXPLORATIONSSS** [srikanth-lingala/zip4j#337]
Hi @srikanth-lingala ,
During the extraction of zipfile, I'm not able to do it via reader . 
For example, inputstream reader = zipfile(filename,password)
Is there any other way of getting the contents 
My contents are in json format

**Comment by srikanth-lingala** [comment]
What exactly are you trying to do? If your file in the zip is of json format, you first have to extract the file or read the content of the file using an input stream. Something like this should probably work:

```
ZipFile zipFile = new ZipFile(BASE_DIR + "sample.zip");
FileHeader fileHeader = zipFile.getFileHeader("name_of_file_in_zip");
try (InputStream inputStream = zipFile.getInputStream(fileHeader)) {
 //Read content of the inputstream to a string (probably with a intermidate byte array to store the  complete raw content first)
 // Now the string will contain your json contents 
}
```

**Comment by srikanth-lingala** [comment]
Closing this as there is no further feedback.
