### ISSUE TITLE
extract zipfile with  password dose not work

### ISSUE THREAD

**Issue by azizkhani** [srikanth-lingala/zip4j#338]
I have zip file that extart successfully in linux and windows correctly but i can not open that with zip4j .
how can debug and find problem ?

**Comment by srikanth-lingala** [comment]
Which version of zip4j are you using? 
Can you attach the zip file here or send to me privately if it is not confidential?
What do you mean by does not work? Do you get any exception? If yes, can you post the stacktrace here?

**Comment by srikanth-lingala** [comment]
Closing this issue as there is no further feedback.
