### ISSUE TITLE
With `readZipInfo` encountering: "The process cannot access the file because it is being used by another process"

### ISSUE THREAD

**Issue by roboaks** [srikanth-lingala/zip4j#344]
We are running zip4j 2.5.1.

On occasion (a couple times per week on average), we encounter this:

```
C:\Users\ITSUser\Documents\Projects\Data Migration\Deployment\Resources\Configuration\IO\StatusService\Buffer\Results-1627967136949.zip (The process cannot access the file because it is being used by another process)
	at net.lingala.zip4j.ZipFile.readZipInfo(ZipFile.java:969)
	at net.lingala.zip4j.ZipFile.extractAll(ZipFile.java:437)
...
```

We have tried everything to ensure that the zip file is in a readable state, including code such as:

```java
	// Retry for 60 seconds; File.exists() check catches fast create-delete pairs
	for (int i = 0; (i < 600) && !Files.isReadable(path) && Files.exists(path); ++i)
	{
		try
		{
			Thread.sleep(100);
		}
		catch (InterruptedException e)
		{}
	}
```

Nothing we do seems to prevent zip4j from occasionally generating the error above. What's strange is that this error didn't start occurring until a couple months ago; AFAIK nothing changed on the relevant servers (AWS Windows servers).

Any ideas?

**Comment by srikanth-lingala** [comment]
Closing this issue as there is no further feedback

**Comment by daltontf** [comment]
I am using 2.9.1 and get this issue seemingly randomly when using ZipFile.addStream method.

**Comment by daltontf** [comment]
It seems to be related to Windows File Explorer "looking" into the file when presently navigated to the directory. I see like "expander" icon blinking in and out of existence as I am writing and navigating away made the issue go away.
