### ISSUE TITLE
supports zstd compression file

### ISSUE THREAD

**Issue by melin** [srikanth-lingala/zip4j#353]
zstd compression ratio is very high, decompression is very fast, directory archive uses zstd compression files

https://github.com/mcmilk/7-Zip-zstd
@srikanth-lingala

**Comment by srikanth-lingala** [comment]
I would love to have this in zip4j, but I am extremely short on free time at the moment. Any little free time I have goes into maintaining zip4j. Your feature request will take some considerable time. I can keep this in mind for any future changes that I do, and when time permits, but at the moment, I can't squeeze it in. I appreciate you letting me though.
