### ISSUE TITLE
ZipInputStream not finding next entry if entry is a folder with a Data Descriptor Still Not Fixed

### ISSUE THREAD

**Issue by mbach979** [srikanth-lingala/zip4j#354]
I believe this issue is still not fixed (tested in 2.9.0).   The attached simple example of writing a zip archive with just two directories using ZipOutputStream and then reading with ZipInputStream fails to read the second entry. 

The offending code seems to be in ZipInputStream.read(byte[], int, int) lines 155-157:
`
    if (localFileHeader.isDirectory()) {
      return -1;
    }
`
Since this stops reading before endOfCompressedDataRecord() can be called, and subsequently read the data descriptor block.   Reading the next entry then silently fails because the signature is for a data descriptor and not a local file header.

[Zip4jDirectoryDataDescriptorBug.zip](https://github.com/srikanth-lingala/zip4j/files/7093077/Zip4jDirectoryDataDescriptorBug.zip)

_Originally posted by @mbach979 in https://github.com/srikanth-lingala/zip4j/issues/309#issuecomment-910485641_

**Comment by srikanth-lingala** [comment]
Thanks for your analysis and also the sample code to test the issue. It really helped. I fixed the issue and I will include the fix in next release.

**Comment by srikanth-lingala** [comment]
Fixed in v2.9.1 released today.
