### ISSUE TITLE
get hash of encrypted zip file

### ISSUE THREAD

**Issue by FloJ12** [srikanth-lingala/zip4j#357]
I need to break a zip file created and encrypted with zip4j.

zip2john says it is corrupted, 7zip shows it is fine, only problem is I don't know the password - is there a possibility to get the hash of the password (for breaking it with for example hashcat)?

**Comment by srikanth-lingala** [comment]
I suggest you to read through the [zip file format specification](https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT) and see if you can find the position of the bytes you need and try reading those bytes. The information you ask for, cannot be obtained by zip4j.
