### ISSUE TITLE
open any zip file directly without extraction.

### ISSUE THREAD

**Issue by rafaqat8** [srikanth-lingala/zip4j#360]
**open any zip file directly without extraction.** 
Because user first check that how many and which file lies in this zip file, then he extract that file.

**Comment by srikanth-lingala** [comment]
You need to get list of file headers. Look at the example here: https://github.com/srikanth-lingala/zip4j#list-all-files-in-a-zip

**Comment by rafaqat8** [comment]
Thank you for your feedback. Can we get the file before extraction

**Comment by srikanth-lingala** [comment]
>Can we get the file before extraction
What do you mean by that?

**Comment by rafaqat8** [comment]
Can I read the file before extraction after viewing the file from the File Headers

**Comment by srikanth-lingala** [comment]
You can get the inputstream of the corresponding file header and read the content. Example [here](https://github.com/srikanth-lingala/zip4j#get-an-input-stream-for-an-entry-in-a-zip-file).
