### ISSUE TITLE
Arabic Unzip

### ISSUE THREAD

**Issue by hassanali2596** [srikanth-lingala/zip4j#361]
Arabic folders an files names are transformed to English letters after unzip operation

That's my code :

 ZipFile zipFile = new ZipFile(dir + "/fixed_exercises.zip", "123456".toCharArray());
 zipFile.extractAll(dir + "/fixed_exercises");

**Comment by srikanth-lingala** [comment]
It might be that the utf-8 flag is not set in the entry headers of the zip file. Which tool did you use to generate the zip file? Would it be possible to attach or send me a copy of the zip file with which I can reproduce this issue?

**Comment by srikanth-lingala** [comment]
Closing this issue as there is no further feedback
