### ISSUE TITLE
Could not open split zip files in Windows

### ISSUE THREAD

**Issue by hltdevlab** [srikanth-lingala/zip4j#362]
Hi, I tried using the createSplitZipFile() as follows:

`List<File> filesToAdd = new ArrayList<File>();`
`filesToAdd.add("C:\\thirtyMbFile.mp4");`
`filesToAdd.add("C:\\twoGbFile.mp4");`

`ZipFile zipfile = new ZipFile("C:\\output\\output.zip");`
`boolean splitArchive = true;`
`long splitLength = 500 * 1024 * 1024; // 500MB`

`zipfile.createSplitZipFile(filesToAdd, new ZipFileParameters(), splitArchive, splitLength);`

Everything works fine except when I tried to unzip. I am using the windows default unzip to open the .zip file and pull all files out to another folder.

The error dialog says "The same volume can not be used as both the source and destination".

I also tried right click"Extract All...". Also get the same error dialog.

What application should I use to extract the files?

Thanks.

**Comment by srikanth-lingala** [comment]
I think Windows tool does not support split zip files. 

Source: https://stackoverflow.com/questions/31286707/the-same-volume-can-not-be-used-as-both-the-source-and-destination

**Comment by hltdevlab** [comment]
> Please try using some other tool like 7-zip, etc.

Hi I tried using 7-zip to open the split zip files, it doesn't recognize it as an archive file.

Or you mean I can use 7-zip to create the split zip files instead?
