### ISSUE TITLE
ZipException: File header and local file header mismatch

### ISSUE THREAD

**Issue by aditya-agg** [srikanth-lingala/zip4j#363]
Hi, I have created zip using zip4j and it is failing with the mentioned exception during unzipping.
Zip file is created using following code

`            File outputFile = new File(zipFile);`
`            outputFile.getParentFile().mkdirs();`
`            ZipFile outputZippedFile = new ZipFile(zipFile);`
`            ZipParameters zipParameters = new ZipParameters();`
`            zipParameters.setSymbolicLinkAction(ZipParameters.SymbolicLinkAction.INCLUDE_LINK_ONLY);`
`            outputZippedFile.addFolder(new File(sourceFolder), zipParameters);`

I have been able to unzip it using other tools, but getting exception with Zip4j. Attaching zip file for reference
[zipFile.zip](https://github.com/srikanth-lingala/zip4j/files/7296533/zipFile.zip)

**Comment by aditya-agg** [comment]
The zip is created to mimic the issueUnfortunately, I cannot share the original zip. During debugging, I observed the exception being thrown when filename has escape character. Also, local file headers are being set correctly, but file headers are believed to be truncated(as seen in intellij), but I am not sure.

**Comment by srikanth-lingala** [comment]
> when filename has escape character.

Which character exactly was it in your case?

**Comment by aditya-agg** [comment]
In mac OS, the name of this file is being shown as "Co/\nfig". However, I am able to unzip the zipfile with IOS unzip software, but not with zip4j.

**Comment by srikanth-lingala** [comment]
Fixed in v2.9.1 released today.
