### ISSUE TITLE
Protection from zip bombs

### ISSUE THREAD

**Issue by antonlakida** [srikanth-lingala/zip4j#378]
Not an issue, more like a question. Does this library have any kind of protection from `zip-bombs`? [Here](https://www.bamsoftware.com/hacks/zipbomb/) you can check out some info

**Comment by srikanth-lingala** [comment]
At the moment, there is no in-built protection. Zip4j uses Java's inbuilt deflater to decompress entries in zip. I am not sure if Java's deflater has any such protection.

**Comment by tozka** [comment]
As Java's inbuilt deflater doesn't have such protection, would you consider accepting contributions that add one ?
