### ISSUE TITLE
net.lingala.zip4j.exception.ZipException: Zip headers not found. Probably not a zip file

### ISSUE THREAD

**Issue by weiyihz** [srikanth-lingala/zip4j#379]
I'm trying to extract zip file, but fail
[archive.zip](https://github.com/srikanth-lingala/zip4j/files/7472426/archive.zip)
.

net.lingala.zip4j.exception.ZipException: Zip headers not found. Probably not a zip file
	at net.lingala.zip4j.headers.HeaderReader.locateOffsetOfEndOfCentralDirectoryByReverseSeek(HeaderReader.java:739)
	at net.lingala.zip4j.headers.HeaderReader.locateOffsetOfEndOfCentralDirectory(HeaderReader.java:723)
	at net.lingala.zip4j.headers.HeaderReader.readEndOfCentralDirectoryRecord(HeaderReader.java:111)
	at net.lingala.zip4j.headers.HeaderReader.readAllHeaders(HeaderReader.java:77)
	at net.lingala.zip4j.ZipFile.readZipInfo(ZipFile.java:1142)
	at net.lingala.zip4j.ZipFile.extractAll(ZipFile.java:461)
	at FilezipApache.unzipFile(FilezipApache.java:147)
	at FilezipApache.main(FilezipApache.java:30)

zip4j version : 2.9.0

**Comment by srikanth-lingala** [comment]
This is a corrupt zip file. Zip headers (located at the end of the zip file) do not exist in the zip file. The actual issue exists in the tool which created this zip file. However, you can try extracting your archive with zip4j's `ZipInputStream` instead of the `ZipFile` api. I think that should work because `ZipInputStream` does not read the zip headers.

**Comment by weiyihz** [comment]
> This is a corrupt zip file. Zip headers (located at the end of the zip file) do not exist in the zip file. The actual issue exists in the tool which created this zip file. However, you can try extracting your archive with zip4j's `ZipInputStream` instead of the `ZipFile` api. I think that should work because `ZipInputStream` does not read the zip headers.



> This is a corrupt zip file. Zip headers (located at the end of the zip file) do not exist in the zip file. The actual issue exists in the tool which created this zip file. However, you can try extracting your archive with zip4j's `ZipInputStream` instead of the `ZipFile` api. I think that should work because `ZipInputStream` does not read the zip headers.



> This is a corrupt zip file. Zip headers (located at the end of the zip file) do not exist in the zip file. The actual issue exists in the tool which created this zip file. However, you can try extracting your archive with zip4j's `ZipInputStream` instead of the `ZipFile` api. I think that should work because `ZipInputStream` does not read the zip headers.

thanks bro

**Comment by weiyihz** [comment]
> This is a corrupt zip file. Zip headers (located at the end of the zip file) do not exist in the zip file. The actual issue exists in the tool which created this zip file. However, you can try extracting your archive with zip4j's `ZipInputStream` instead of the `ZipFile` api. I think that should work because `ZipInputStream` does not read the zip headers.

thanks  bro
