### ISSUE TITLE
Can we create a new exception type when Password is Null/Missing?

### ISSUE THREAD

**Issue by lakshans** [srikanth-lingala/zip4j#380]
Currently, when a password is null or empty, the following is thrown:

`throw new ZipException("empty or null password provided for AES decryption");`

Other exceptions have a type associated except for this one. It would be useful to have a "PASSWORD_EMPTY" zip exception type, or something along those lines.

**Comment by srikanth-lingala** [comment]
Sure. I will add it.

**Comment by srikanth-lingala** [comment]
Actually, after analysing the code, I will reuse the `WRONG_PASSWORD` type for this case as well. `ZipStandardDecrypter` throws this type of exception when the password is empty. Doing the same for `AesDecrypter` will keep this behaviour consistent.

**Comment by srikanth-lingala** [comment]
Fixed in v2.9.1 released today.
