### ISSUE TITLE
Multi-thread support

### ISSUE THREAD

**Issue by lzxshare** [srikanth-lingala/zip4j#381]
yes,i think Multi-thread is very useful in some scenarios，especially when dealing with large files, I hope the author can realize this function as soon as possible，many thanks

**Comment by srikanth-lingala** [comment]
I will most likely have some free time from first week of December. I will see if I can add this feature during that time.

**Comment by srikanth-lingala** [comment]
This is a duplicate of #319. Please follow that issue for updates
