### ISSUE TITLE
difference between AES and standardencryption

### ISSUE THREAD

**Issue by 3harish** [srikanth-lingala/zip4j#387]
what is the difference between AES and Zip standard encryption??

**Comment by srikanth-lingala** [comment]
Zip Standard is a legacy encryption, which although is strong, but can be vulnerable to attacks. AES is a much more sophisticated encryption added to the zip file format specification by WinZip, and is now adopted and supported by most of the zip tools. If you have a choice to choose between then, I would recommend AES over Zip Standard without any doubt. There are plenty of resources online to dig deeper if you wish to.

**Comment by 3harish** [comment]
> Zip Standard is a legacy encryption, which although is strong, but can be vulnerable to attacks. AES is a much more sophisticated encryption added to the zip file format specification by WinZip, and is now adopted and supported by most of the zip tools. If you have a choice to choose between then, I would recommend AES over Zip Standard without any doubt. There are plenty of resources online to dig deeper if you wish to.

thank you sir
