### ISSUE TITLE
Passwor protected zip can not be extracted using windows file explorer

### ISSUE THREAD

**Issue by marius91dat** [srikanth-lingala/zip4j#389]
When trying to extract the zipped file I get this message from windows:
![image](https://user-images.githubusercontent.com/56964204/144212050-6200b020-e7a8-4641-ba4a-7abe30066623.png)

I can unzip the file with other programs without any problems.
Do anyone have a clue why this happens?

This is the code I used to zip my files:
```
 ZipParameters zipParameters = new ZipParameters();
        zipParameters.setEncryptFiles(true);
        zipParameters.setEncryptionMethod(EncryptionMethod.AES);

        String completePath = getCompletePath(zipFileId);
        ZipFile zipFile = new ZipFile(completePath, password.toCharArray());
        try {
            zipFile.addFolder(temporaryFolder, zipParameters);
        } catch (ZipException e) {
            throw new ZipCaseException("Failed to zip files.");
        }
```

**Comment by srikanth-lingala** [comment]
Windows built-in zip tool does not support AES encryption. 

Reference: https://superuser.com/questions/1255917/do-windows-8-1-or-10-support-aes-256-in-zip-files

**Comment by marius91dat** [comment]
Thank you!
