### ISSUE TITLE
Cannot read Entire zipfile using ZipInputStream.read(byte[] b) method

### ISSUE THREAD

**Issue by gokul-prabha98** [srikanth-lingala/zip4j#392]
I need to read the content of the zip file without extracting it to the disk. But when I go with ZipInputStream.read(byte[] b) method, Only half of the content from the file is transferred to byte array. Pending value of b contains 0. It works fine for 5KB file. When I try with 35KB file, this issue occurs and also, zipInputStream.read() returns lesser value than the actual length of the file. For example: When run the line 
zipInputStream.read(b ,  0 , 20000), It returns 16518. When I iterate and read by length of 3000(zipInputStream(b , 0 , 3000)). I have the issue at same line at 6th iteration.

**Comment by srikanth-lingala** [comment]
Closing this as it is not an issue. Please feel free to reopen if you think otherwise.
