### ISSUE TITLE
I am getting error no main manifest attribute, in /Users/Downloads/zip4j-2.9.1.jar

### ISSUE THREAD

**Issue by MOHITDIXIT786** [srikanth-lingala/zip4j#397]
I tried a lot to resolve the issue but was not able to do so please help me out

**Comment by MOHITDIXIT786** [comment]
@srikanth-lingala  please help me out

**Comment by srikanth-lingala** [comment]
Can you please be more specific about the error you get? Where do you get this error?

**Comment by MOHITDIXIT786** [comment]
Thanks for your reply, the issue already got resolved
MOHIT DIXIT
