### ISSUE TITLE
Why createSplitZipFileFromFolder is not blocking?

### ISSUE THREAD

**Issue by antony84** [srikanth-lingala/zip4j#398]
Hi, why call to createSplitZipFileFromFolder is not blocking? 
How i can know when zip split process ended?

**Comment by srikanth-lingala** [comment]
It is blocking. I just tested it with a directory and it was blocking until the process was complete. Maybe you have the `setRunInThread` parameter set to true accidentally? Or was the directory you were trying to add too small to notice the block?
