### ISSUE TITLE
Problem extracting zip file: illegal file name that breaks out of the target directory: /

### ISSUE THREAD

**Issue by Gr33nbl00d** [srikanth-lingala/zip4j#400]
Hi i have problem extracting a zip file which was generated by maven assembly plugin.
https://github.com/srikanth-lingala/zip4j/blob/ed9eed54de22cb845ded8d582b7330adcc7ba9af/src/main/java/net/lingala/zip4j/tasks/AbstractExtractFileTask.java#L53

I debuged into that place and found out that the outputfile does not have a trailing slash but the outputCannonical path variable has.
Thats what i see in the IDE

> outputFile = {File@1809} "D:\Users\XXXXXXX\AppData\Local\Temp\dependentrules14443115985707206885"
    outputCanonicalPath = "D:\Users\XXXXXXX\AppData\Local\Temp\dependentrules14443115985707206885\\"
 

The zip file header looks like this:

> versionMadeBy = 788
fileCommentLength = 0
diskNumberStart = 0
internalFileAttributes = {byte[2]@1817} [0, 0]
externalFileAttributes = {byte[4]@1818} [16, 0, -19, 65]
offsetLocalHeader = 5294
fileComment = null
versionNeededToExtract = 10
generalPurposeFlag = {byte[2]@1819} [0, 0]
compressionMethod = {CompressionMethod@1820} "STORE"
lastModifiedTime = 1412516727
crc = 0
compressedSize = 0
uncompressedSize = 0
fileNameLength = 1
extraFieldLength = 0
fileName = "/"
isEncrypted = false
encryptionMethod = {EncryptionMethod@1822} "NONE"
dataDescriptorExists = false
zip64ExtendedInfo = null
aesExtraDataRecord = null
fileNameUTF8Encoded = false
extraDataRecords = null
isDirectory = true
signature = {HeaderSignature@1823} "CENTRAL_DIRECTORY"

Any solution to this? Is this a bug? Anyone had the same problem?

**Comment by Gr33nbl00d** [comment]
It seems like fix for #133 in commit ff3d3b34 caused that problem.
If found at least on windows new File (last line) in determineOutputFile method removes the trailing slash.

https://github.com/srikanth-lingala/zip4j/blob/ed9eed54de22cb845ded8d582b7330adcc7ba9af/src/main/java/net/lingala/zip4j/tasks/AbstractExtractFileTask.java#L165

new File("d:\test\2\) --> d:\test

In fix #133 you have added a file seperator to the extraction path in order somone can not extract in a different folder name. Unfortunatly the result of determineOutputFile does not contain a slash in case its the relative root folder.

https://github.com/srikanth-lingala/zip4j/blob/ed9eed54de22cb845ded8d582b7330adcc7ba9af/src/main/java/net/lingala/zip4j/tasks/AbstractExtractFileTask.java#L52

**Comment by srikanth-lingala** [comment]
@Gr33nbl00d Thanks for the PR. I merged your PR, but also made some [slight adjustment to your PR][1]. Instead of checking for just root directory, I now check if the outputFile is a directory, and append the fileSeparator if it is a directory. Can you please confirm if this change still works with your zip file?

[1]: https://github.com/srikanth-lingala/zip4j/commit/db41e9b47c82d728b66e9209a66cd00fa4aa52c0#diff-3f214bfe1a60439ad4cafcb2c9b107e031119da12a53d576b4ea9b8a80838756R75

**Comment by Gr33nbl00d** [comment]
I will check on wednesday if it still works. I have a day off tomorrow. Thanks for merging

**Comment by Gr33nbl00d** [comment]
Hi i have verified that the bugfix fixed the problem :)
