### ISSUE TITLE
Order of encryption and compression.

### ISSUE THREAD

**Issue by abhishekshan03** [srikanth-lingala/zip4j#401]
Can you please let me know what is the order of encryption and compression?
Ideally it should be compression and then encryption, so as to achieve a good compression.

But I see in zip4j ZipOutputStream delegates write to CompressedOutputStream which further delegates write to CipherOutputStream which actually encrypts and then zips.

```
  @Override
  public void write(byte[] b, int off, int len) throws IOException {
    encrypter.encryptData(b, off, len);
    zipEntryOutputStream.write(b, off, len);
  }
```
  
If my understanding is correct then please help me understand reason behind this order.
Else please correct me.
Thanks in advance.

**Comment by srikanth-lingala** [comment]
Your understanding is right. Flow of data is the following:

> DeflaterOutputStream -> CompressedOutputStream -> CipherOutputStream -> ZipEntryOutputStream -> SplitOutputStream

Data is first compressed, then encrypted.
