### ISSUE TITLE
Generating Big Zip with streams

### ISSUE THREAD

**Issue by brebDevv** [srikanth-lingala/zip4j#413]
Hi, I'm struggling to compress a file that is around 1GB of data, that contains around 2000 pdf documents. After around 1000 documents compression, this line: zos.closeEntry(); is throwing an OutOfMemoryException

I've documented really well the issue here: https://stackoverflow.com/questions/71561060/generating-big-zip-with-streamswith-zip4j-and-uploading-it-to-s3

Even do the heap space was increased considerably , this error is still throwing.
Are there any techniques that I can use, for example: to try to zip only a number of documents -> append to zip -> and repeat the process ? I've tried this but the ZIP will be overwritten by last batch of documents.

**Comment by srikanth-lingala** [comment]
There has been an attempt to find a solution to this issue a few years back, but this is an inevitable issue if you dealing with just streams. There can be some possible solutions when dealing with files. The thing is, in a zip file format, all entry (file) headers are stored at the end of the zip file/stream. So you have to keep all entries metadata in memory and write it out to a file/stream once all entries have been added. No matter how compact each metadata is (and you can't make it too compact as well), depending on application's available memory and number of entries being added to the zip file, you will at some point reach this OOM exception. When working with files though, there can be some solutions like writing the headers to a temporary file and appending this to the zip file once all entries have been added. But this solution hasn't been implemented yet. 

Your best bet at the moment is, as you rightly pointed out, to use `ZipFile.addStream()`. The reason each entry is being overwritten is that you probably aren't changing the file name in `ZipParameters`. Try setting a unique file name via `ZipParameters.setFileNameInZip()` and pass these `ZipParameters` to `addStream()` call.

**Comment by srikanth-lingala** [comment]
On a side note: 2000 entries is really not a lot. Maybe your application is running low on free memory? Each entry in a zip file has about 40 to 50 bytes of metadata (this can vary slightly depending on some factors such as encryption, etc). But even if we double that, and multiply by 2000, we are talking about approximately 100kb of file metadata that is stored in memory. Can you profile your application and check available memory when this issue occurs?

**Comment by brebDevv** [comment]
My tests results with `ZipFile.addStream()` were pretty weird. Since all the documents must be in the same folder called "pdf". So If I tried to use like this:

-  `ZipParameters.setFileNameInZip("pdf/")` the zip will have an empty folder pdf. Not sure why the documents are not added at all..
-  `ZipParameters.setFileNameInZip("pdf")` this will create a file, and only inside the "file" there are the documents are places, but as I said will be overwriten.
- `ZipParameters.setFileNameInZip("")` I'd really want to set an empty file, and the `.addStream(new ByteArrayInputStream(baos.toByteArray()), zp);` and the baos.toByteArray() will contain the information about the root folder: **pdf** and the related documents. And this to be looped. But if I set and empty file name, again nothing is inside the zip.

Thanks for the tip, I'll try with setting a unique file name via `ZipParameters.setFileNameInZip()`

So all the documents are around 1GB, but in the same transaction are read from DB, and the zip generation is being made. Even with a heap set on 16GB RAM, I still see the HeapOutOfMemory exception after document nr 1200.. 

Ok, I'll try to profile the application and keep you posted.

**Comment by srikanth-lingala** [comment]
The first two points are as expected. If a file name in zip ends with a "/", zip4j (and zip format in general) considers this to be a directory and ignores any content being added, and in the second case, whenever an entry is being added to a zip file, zip4j checks if an entry with that name already exists in the zip file, and if yes, overrides it. The third case however should throw an exception. It should not be possible to set an empty file name via `addStream()`. I will check and fix it.

If you want all your pdf's to be inside a directory called `pdf/` the just name the file as `pdf/your_file_name.pdf`. And since you will give each entry an unique name, you could do something like `pdf/0001.pdf`, `pdf/0002.pdf`, etc.
