### ISSUE TITLE
File archived with the password, cannot be extracted with the windows explorer. Works fine with 7zip tool

### ISSUE THREAD

**Issue by bhagyadesai** [srikanth-lingala/zip4j#414]
When we to Extract a password encrypted zip file using Windows Explorer it gives below error.
0x80004005: Unspecified error during unzipping
Please note that, the same zip file gets extracted properly with other zip tools like 7zip, pkunzip, etc

Here is the code snippet
zipParameters.setEncryptFiles(true);
     			zipParameters.setEncryptionMethod(EncryptionMethod.AES);
                zipFile.setPassword(password.toCharArray());

According to the below link, Windows doesnot support AES_256 encrypted password.

https://www.winhelponline.com/blog/zip-error-0x80004005-extract-copy-unspecified-error/
In that case, should I set it to AES_128 (e.g., zipParameters.setAesKeyStrength(AesKeyStrength.KEY_STRENGTH_128);

Ig will be helpful if there is anything I can do here so that it can be extracted from windows explorer as well.

Thank you.
Regards
- Bhagyashree

**Comment by srikanth-lingala** [comment]
Windows does not support AES irrespective of key length. If you need to support encrypted zip file with Windows explorer, you can consider using Zip Standard Encryption.

**Comment by bhagyadesai** [comment]
Thank you so much Srikanth for your quick support
