### ISSUE TITLE
When verifying a zip package, you do not need the entire file, but only a small piece of information at the end of the zip (including file header information)

### ISSUE THREAD

**Issue by jwzjay** [srikanth-lingala/zip4j#415]
When verifying a zip package, you do not need the entire file, but only a small piece of information at the end of the zip (including file header information),
Can the code of "https://github.com/srikanth-lingala/zip4j/blob/master/src/main/java/net/lingala/zip4j/headers/HeaderReader.java#L125"  be modified to "endOfCentralDirectoryRecord.setOffsetOfStartOfCentralDirectory(endOfCentralDirectoryRecord.getOffsetOfEndOfCentralDirectory()-endOfCentralDirectoryRecord.getSizeOfCentralDirectory());"
thanks a lot.

**Comment by srikanth-lingala** [comment]
Your issue title doesn't relate to the description of your issue. Can you please elaborate what you are trying to say?

> Can the code of "https://github.com/srikanth-lingala/zip4j/blob/master/src/main/java/net/lingala/zip4j/headers/HeaderReader.java#L125" be modified to "endOfCentralDirectoryRecord.setOffsetOfStartOfCentralDirectory(endOfCentralDirectoryRecord.getOffsetOfEndOfCentralDirectory()-endOfCentralDirectoryRecord.getSizeOfCentralDirectory());"

Although technically this might be true, why do you want to change this when this value is more reliable when it is read from the header than when we calculate it like you proposed?

**Comment by jwzjay** [comment]
If don't modify it, you need to upload the whole compressed package for verification. However, after modification, you only need to upload a small piece of compressed package information to verify whether the contents of the whole package meet the requirements, which saves the whole process of uploading and verifying the compressed package. Of course, you can also provide a selection method, and you can choose which kind of verification according to your needs

**Comment by jwzjay** [comment]
> 如果不修改，则需要上传整个压缩包进行验证。但是修改后只需要上传一小段压缩包信息，就可以验证整个包的内容是否符合要求，省去了上传和验证压缩包的全过程。当然你也可以提供一种选择方式，你可以根据自己的需要选择哪种验证方式

**Comment by srikanth-lingala** [comment]
I still don't get your point unfortunately. Upload content? Upload where?

**Comment by srikanth-lingala** [comment]
Closing this issue as there was no further clarification to the comment above
