### ISSUE TITLE
Support for CompressionLevel zero for DEFLATE

### ISSUE THREAD

**Issue by agollamandala** [srikanth-lingala/zip4j#416]
Hi,

We are shifting from java.util.zip to Zip4j to use the password feature. As we are working with streams for input, we are not able to use STORE compression method as it requires stream length to be calculated beforehand. Kindly please add CompressionLevel zero support for DEFLATE compression methods as it will be useful for us to continue working with streams without additional calculation/storage overhead.

Thanks and regards,
Abhilash.

**Comment by srikanth-lingala** [comment]
Feature added in v2.10.0 released today
