### ISSUE TITLE
File being archived with Japanese characters as password does not get extracted using Zip7, Windows Explorer tools on Japanese Environment

### ISSUE THREAD

**Issue by bhagyadesai** [srikanth-lingala/zip4j#417]
Hi all,

We  are using below code to archive the file.
zipParameters.setEncryptFiles(true);
zipParameters.setEncryptionMethod(EncryptionMethod.ZIP_STANDARD);
zipFile.setPassword(password.toCharArray());

When we try to unzip the file which is zipped by zip4j using windows explorer or 7zip,  we get the error  **password required (wrong password) box while extracting file**.   The problem occurs for the below combination only.
1)  zip file  which is password protected
2) Password having  Japanese characters
3) Environment - Japanese Windows OS

On the same environment(Japanese windows) if we use English characters for password, then extract works fine with windows explorer and 7zip.

Also a zip file created with the same  japanese password on English windows OS version also can be extracted correctly with windows explorer and 7zip.

The password that we tried were for with below characters 
       Japanese:-  日本語
       Single byte katakana -  ｧｨｫｬ
       NEC -  ①②㈲㈹㍾㍽
       IBM -  岺峵崧嵓﨑

**Extracting the zip file using zip4j works perfectly fine**.
Herewith attached the zip file(Test.zip) which is created by zip4j for your reference.
The password used in this zip file is : ｧｨｫｬ

Could you please look into this issue and advise.

Thank you .
- [Bhagyashree](url)
[Test.zip](https://github.com/srikanth-lingala/zip4j/files/8358431/Test.zip)

**Comment by bhagyadesai** [comment]
Additional input for analysis.
Same jar file extracted using WinRar extracts the file successfully

**Comment by srikanth-lingala** [comment]
I tested with the 7z command line utility, and it seems to be fine.

<img width="528" alt="Screen Shot 2022-03-28 at 8 32 23 AM" src="https://user-images.githubusercontent.com/3450302/160398791-8056adf9-e769-4152-9188-e69e5b1b51af.png">

 I also was successfully able to extract the file with zip4j. 

On a side note though, with non-ascii passwords, it depends on the tool on how they handle it. Some tools convert the password using utf-8 charset, and some don't. When using non-ascii passwords, the tool you are using to extract should be able to encode the password using utf-8 charset. If they don't do that, extraction/reading zip file will fail. For example, if Windows Explorer cannot extract the zip file, it is most likely that they don't convert the password using utf-8 charset. I remember reading somewhere that 7-zip UI had this issue as well, although I am unable to find any link to that. However, my advice is, if possible to not use non-ascii characters for passwords, especially if you are aiming for your zip files to be handled by several tools and want to maintain cross compatibility.

**Comment by bhagyadesai** [comment]
Thank you so much  for the detailed explanations.

**Comment by bhagyadesai** [comment]
Hi,

Could you find any reason why the zip which is generated on English Windows OS can be extracted and the one generated on Japanese OS cannot be extracted.
For your reference herewith attached the zip files generated from both the environment.
The password is same - ｧｨｫｬ

Could you please provide some info on this.


[Test_Jap.zip](https://github.com/srikanth-lingala/zip4j/files/8398239/Test_Jap.zip)
[Test_English.zip](https://github.com/srikanth-lingala/zip4j/files/8398240/Test_English.zip)


Thank you.
Regards
- Bhagyashree
