### ISSUE TITLE
it's possible only change password in encrypted zip file?

### ISSUE THREAD

**Issue by bellfive** [srikanth-lingala/zip4j#420]
thanks for maintaining such a top notch library.

I zip the file with a password. (Example: "111")
I want to change this password in the zip file. (Example: "222") 

only change password, not contents

it's possible?

I try to insert new file with modified password.

but password is old ("111"), not "222"

changeZipPassword("encryped zipfile", "222")

```
fun changeZipPassword(filename: String, password: String) {
        val zipOrgFile = ZipFile(filename)
        val directory = Environment.getExternalStorageDirectory().toString()+ "/videos/"
        val newFile = File(directory + ".empty")
        val zipParameters = ZipParameters()
        zipParameters.apply {
            isEncryptFiles = true
            encryptionMethod = EncryptionMethod.AES
            aesKeyStrength = AesKeyStrength.KEY_STRENGTH_256
        }
        zipOrgFile.setPassword(password.toCharArray())
        newFile.createNewFile()
        zipOrgFile.addFile(newFile, zipParameters)
        newFile.delete()
    }

```

I have to extract file and re-zip with new password??

**Comment by srikanth-lingala** [comment]
The only way to change a password for a zip file is to extract and compress again with the new password. Even if zip4j would provide a convenient method called `zipFile.changePassword(byte[] password)`, zip4j would have to do the same - i.e, to first extract the contents, and then to repack them with the new password. So for now, I would suggest you do the same. I want to add this feature to zip4j at some point, but honestly I am not sure when I will find time for this. But as explained earlier, it would be the same thing if zip4j did it as well or if you extracted and compressed again with the new password.

**Comment by bellfive** [comment]
Thank you for your kind reply~
