### ISSUE TITLE
zip4j.exception.ZipException: Zip headers not found. Probably not a zip file

### ISSUE THREAD

**Issue by XuXin007** [srikanth-lingala/zip4j#422]
1.The rar file on the computer is copied to the Android phone and cannot be decompressed, throwing an exception "net.lingala.zip4j.exception.ZipException: Zip headers not found. Probably not a zip file" .The compression software and version on the computer are shown in the picture.I love this repository of yours, thank you so much.
2.The decompression program I wrote myself cannot decompress the compressed package copied from the computer to the Android phone. The debug zipInputStream.getNextEntry() is null. I don't know why
![微信截图_20220415214416](https://user-images.githubusercontent.com/90443578/163579795-182f0fe3-826e-4c60-bae5-d3fbfc53d40d.png)
![微信截图_20220415214437](https://user-images.githubusercontent.com/90443578/163579807-1df828fe-c7a3-4a9e-a232-4bcdf0effa6d.png)
![微信截图_20220415215304](https://user-images.githubusercontent.com/90443578/163579896-19b963e5-7df9-43fa-9536-65c1d6d25037.png)

**Comment by srikanth-lingala** [comment]
Zip4j only supports zip files and does not support rar files.

**Comment by MasterAlexXu** [comment]
I got it, thanks a lot
