### ISSUE TITLE
Can I check whether the password is correct through Stream

### ISSUE THREAD

**Issue by XuBoZhangQvQ** [srikanth-lingala/zip4j#423]
```java
 try {
            ChannelSftp channelSftp = FileSFTPHandlerUtils.getSFTPObject().getSftp();
            channelSftp.cd("/output");
            InputStream inputStream = channelSftp.get("test.zip");
            String password = "1233";
            try (ZipInputStream zipInputStream = new ZipInputStream(inputStream, password.toCharArray())) {
                //Can I check whether the password is correct through Stream,like this
                //Boolean passwordState =  zipInputStream.validPassword();
                while (zipInputStream.getNextEntry() != null) {
                    BufferedReader bufferedReader = new BufferedReader(new InputStreamReader(zipInputStream, StandardCharsets.UTF_8));
                    String line = "";
                    // Or only start to read the stream, catch ZipException:wrong password
                    //net.lingual.zip4j.exception.ZipException: Wrong Password
                    while ((line = bufferedReader.readLine()) != null) {
                        System.out.println("line = " + line);
                    }
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
```

**Comment by srikanth-lingala** [comment]
If the password is wrong, you will get a ZipException of type `WRONG_PASSWORD` when you try to read the stream. You cannot check for password validity the way you wrote in your sample code but reading the content will fail with the exception mentioned above. [Here](https://github.com/srikanth-lingala/zip4j/blob/master/src/main/java/net/lingala/zip4j/exception/ZipException.java#L54) is the code reference.

**Comment by XuBoZhangQvQ** [comment]
only try to catch exceptions when reading the stream to determine whether the password is correcta

**Comment by XuBoZhangQvQ** [comment]
only try to catch exceptions when reading the stream to determine whether the password is correct

**Comment by XuBoZhangQvQ** [comment]
Because I want to traverse all file, determine the file status, and then read\process the file stream, I want to determine whether the file password is correct before reading

**Comment by srikanth-lingala** [comment]
This is a complicated question which I will try to explain as best as I can. It is complicated because of the way zip file format is. In short, you have to start reading the content of the zip to know if the password is correct and if all your files in a zip are encrypted with the same password, you will get an exception on your first attempt to read. By read, I mean you don't have to read the complete content of the zip file, like on this line:

> while ((line = bufferedReader.readLine()) != null)

but you have to read the next entry, like on this line:

> while (zipInputStream.getNextEntry() != null) 

and you will get an exception on the above line if the password is wrong. So technically you only are reading the headers of the file in the zip, and not the content of the file. You can try this out with a sample zip file and provide a wrong password and try to debug through the code.

**Comment by XuBoZhangQvQ** [comment]
I know what you mean,this is how I handle it at present, but for the following operations, I just check the file status, and then process the data in other places, I just want to get whether the file password is correct here
whatever，Thank you for your reply😄
```java
                String password = sm2.decryptStr(packdata.split(SPILT_REGEX)[2], KeyType.PrivateKey);
                dataFileEntity.setZipAesPassword(password);
                InputStream inputStream = channelSftp.get(dataFileName);
                //Is the file decompression password correct
                try (ZipInputStream zipInputStream = new ZipInputStream(inputStream, password.toCharArray())) {
                    while (zipInputStream.getNextEntry() != null) {
                        BufferedReader bufferedReader = new BufferedReader(new InputStreamReader(zipInputStream, StandardCharsets.UTF_8));
                        bufferedReader.readLine();
                    }
                    dataFileEntity.setUnzipState(true);
                } catch (Exception e) {
                    dataFileEntity.setUnzipState(false);
                }
```
