### ISSUE TITLE
setRunInThread() is not preserving folder structure

### ISSUE THREAD

**Issue by BXXD101** [srikanth-lingala/zip4j#425]
When using with thread it will not zip sub folders and files.

**Comment by srikanth-lingala** [comment]
Works fine for me. This is the code I used, and the output zip file preserved the folder structure.

```
ZipFile zipFile = new ZipFile("Test.zip");
zipFile.setRunInThread(true);
ProgressMonitor progressMonitor = zipFile.getProgressMonitor();
zipFile.addFolder(new File(FOLDER_TO_ADD));

while (progressMonitor.getState().equals(ProgressMonitor.State.BUSY)) {
  Thread.sleep(100);
  System.out.println(progressMonitor.getPercentDone());
}
```

Which version of zip4j are you using?

**Comment by srikanth-lingala** [comment]
Closing this issue as there is no further feedback. Please feel free to reopen if you still face this issue.
