### ISSUE TITLE
Extracting nested zips

### ISSUE THREAD

**Issue by rajgorantla9** [srikanth-lingala/zip4j#427]
Hi,

I have multiple nested zips (upto around 4 levels, one within the other). How can i extract using zip4j. Will zip4j supports nested zip extractions. If not can we expect in the coming versions.

**Comment by srikanth-lingala** [comment]
zip4j supports nested zip files. Take a look at the [tests here](https://github.com/srikanth-lingala/zip4j/blob/9eab02b675d23079fc87fe9a6c0d5503465d2e3e/src/test/java/net/lingala/zip4j/ExtractZipFileIT.java#L725) to see how it works. Basically, you can get an `InputStream` of the nested zip file, and then create a `ZIpInputStream` out of that stream and extract it.
