### ISSUE TITLE
Can't unzip protected file with empty password

### ISSUE THREAD

**Issue by TomoHavvk** [srikanth-lingala/zip4j#429]
Can't unzip protected file with empty password because of this condition:

![Screenshot 2022-05-18 at 16 29 03](https://user-images.githubusercontent.com/8134708/169050276-f610fed7-07e9-462a-898c-4dac241cae4a.png)

https://github.com/srikanth-lingala/zip4j/blob/master/src/main/java/net/lingala/zip4j/crypto/StandardDecrypter.java#L50

Version: **2.10.0**

**Comment by srikanth-lingala** [comment]
Do you have a zip file with empty password? While there is no hard rule defined in the zip specification, it is usually not recommend to have empty password for zip files as a lot of tools out there don't support zip files with empty password. This breaks compatibility between zip files.

**Comment by srikanth-lingala** [comment]
Closing this as there was no further feedback on my comment above.
