### ISSUE TITLE
Integration with Google oss-fuzz fuzzing service

### ISSUE THREAD

**Issue by happy-qop** [srikanth-lingala/zip4j#431]
Hi, I would like to help integrate this project into Google [oss-fuzz](https://github.com/google/oss-fuzz).
It is a fuzzing service Google provided for automatically testing important open-source repositories.
I've submitted an integration [PR](https://github.com/google/oss-fuzz/pull/7748) to oss-fuzz.
The integration contains the scripts and fuzzers for testing this project.
Are you happy to support this integration?
Additionally, can you provide your email? It will be used to notify you when oss-fuzz found bugs of this project.

**Comment by srikanth-lingala** [comment]
Yes, I would be more than happy to support the integration. My email id is srikanth.mailbox (at) gmail (dot) com
