### ISSUE TITLE
ZipParameters lastModifiedTime is ignored

### ISSUE THREAD

**Issue by NichtStudioCode** [srikanth-lingala/zip4j#434]
When adding a folder to a ZipFile using ``ZipFile#addFolder(File, ZipParameters)`` with ``ZipParameters#lastModifiedFileTime`` configured to some value such as ``1``, this value is ignored.

I believe that the reason for this behavior can be found [here](https://github.com/srikanth-lingala/zip4j/blob/f88f0fb3e6a02705ec9ff445fe169964c90de1d3/src/main/java/net/lingala/zip4j/tasks/AbstractAddFileToZipTask.java#L203), as the ``lastModifiedFileTime`` just gets set to ``epochToExtendedDosTime((fileToAdd.lastModified()))``.

**Comment by srikanth-lingala** [comment]
Issue fixed. I will include the fix in the next release.
