### ISSUE TITLE
ExtractFile Failed with NullPointExcetion

### ISSUE THREAD

**Issue by LonelyTangzz** [srikanth-lingala/zip4j#435]
Recently, I was doing a dependency upgrade of an old project, and planned to upgrade the original Zip4j@1.3.2 to 2.7.0, but when I did the unit test of the decompression part after the upgrade, I couldn't get the fileAttributeView normally, resulting in a null pointer exception.
```
    private static void applyWindowsFileAttributes(Path file, byte[] fileAttributes) {
        if (fileAttributes[0] != 0) {
            DosFileAttributeView fileAttributeView = (DosFileAttributeView)Files.getFileAttributeView(file, DosFileAttributeView.class, LinkOption.NOFOLLOW_LINKS);//here can't get fileAttributeView

            try {
                fileAttributeView.setReadOnly(BitUtils.isBitSet(fileAttributes[0], 0));
                fileAttributeView.setHidden(BitUtils.isBitSet(fileAttributes[0], 1));
                fileAttributeView.setSystem(BitUtils.isBitSet(fileAttributes[0], 2));
                fileAttributeView.setArchive(BitUtils.isBitSet(fileAttributes[0], 5));
            } catch (IOException var4) {
            }

        }
    }
```
I did breakpoint debugging, this path of file is non-empty, which is strange, and the folder access permission is also granted. Does the author know what happened?

**Comment by srikanth-lingala** [comment]
Do you have a stacktrace for me?

**Comment by LonelyTangzz** [comment]
![begin](https://user-images.githubusercontent.com/48684478/172359721-27547d9a-7d70-434f-a968-90ddc5b9dba9.png)
![after status](https://user-images.githubusercontent.com/48684478/172359732-38a35292-d784-4965-b250-8f21072028f4.png)
