### ISSUE TITLE
Unzip with rlc (zip) file from Rhapsody results in directory name being concatenated with filename. ON LINUX

### ISSUE THREAD

**Issue by DragonSky** [srikanth-lingala/zip4j#440]
I'm trying to unzip an .rlc file (configuration export) from Rhaposody integration engine.  In zip4j 2.10.0 on Linux I get the result of the scheme directory being extracted as files with the the directory name concatenated with the filename.  
Reverting to zip4j v2.8.0 results in the expected behaviour.

Sorry, don't know what Rhapsody is using to zip up it's rlc export files, it's written in Java though.  I can log a request and see if I find out if you'd like.

as below:
![image](https://user-images.githubusercontent.com/929052/175169259-8057a452-1e92-4e80-ab80-5825e6405b5c.png)

![image](https://user-images.githubusercontent.com/929052/175168552-e8d1c59a-ddf7-4384-bc4b-4818756645c3.png)
If there is a directory that has sub directories everything seems to work ok.

Details of the file:
![image](https://user-images.githubusercontent.com/929052/175168911-7fd38168-98e7-4029-a546-f0cb03a81002.png)
![image](https://user-images.githubusercontent.com/929052/175168946-4d68a2b5-d1a4-40b6-ace3-44469b573248.png)

This only occurs on Linux, everything plays fine on windows 10.
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.9"

Happy to provide any further information required.

[tracking.zip](https://github.com/srikanth-lingala/zip4j/files/8962348/tracking.zip)

**Comment by srikanth-lingala** [comment]
I fixed the issue. I will include it in the next minor release which should be out in a couple of days.

**Comment by DragonSky** [comment]
Many thanks.  Love your work.

**Comment by DragonSky** [comment]
Many thanks for this... works as advertised.
