### ISSUE TITLE
addFolder cannot add files or folders under the target folder when run Windows with JDK1.7

### ISSUE THREAD

**Issue by ecool2011** [srikanth-lingala/zip4j#442]
As title, 

we use addFolder method to add one folder under windows os and with JDK1.7, the zip file only include the files and folder in the root files.
e.g:
c:\temp\1.xls
c:\temp\2\2.xls

if addFolder(new File("c:\\\\temp") , then the zip file only  include :
c:\temp\1.xls
c:\temp\2

no 2.xls.

but for 2.9.0 version, it works well.

I just checkedthe source code, the problem is FileUtils.isFileRegularOrDirectoryOrSymlink() will return false when check the file under c:\temp\2 folder.

**Comment by srikanth-lingala** [comment]
I fixed this in v2.11.1 released today.
