### ISSUE TITLE
When i use the zipFile.createSplitZipFile(files, zipParameters, true, 1024 * 70) this line actually split the original zip file into multiple based on size i.e. 70kb.But the content inside the all zip files are same.the content is not splitting up. could you please resolve this issue? or is there any other way call the function?

### ISSUE THREAD

**Issue by srikanthvadde** [srikanth-lingala/zip4j#451]
@srikanthvadde This issue is unrelated to the one this thread is about. Please open a new issue with the problem you are facing, and include as many details as possible like zip4j version, your complete code snippet, os and version, and anything else that you think might be useful. BTW, if you are already not on the latest version of zip4j, try with the latest version before opening this issue.

_Originally posted by @srikanth-lingala in https://github.com/srikanth-lingala/zip4j/issues/120#issuecomment-1184144935_

**Comment by srikanthvadde** [comment]
@srikanthvadde This issue is unrelated to the one this thread is about. Please open a new issue with the problem you are facing, and include as many details as possible like zip4j version, your complete code snippet, os and version, and anything else that you think might be useful. BTW, if you are already not on the latest version of zip4j, try with the latest version before opening this issue.

os: windows(10.0.19904)
version: latest from maven (2.11.x)
pl: java
framework: camel

sample code:
       ```
ZipParameters zipParameters = new ZipParameters();
        zipParameters.setEncryptFiles(true);
        zipParameters.setEncryptionMethod(EncryptionMethod.AES);
        ZipFile zipFile = new ZipFile("compressed.zip","password".toCharArray());
        List<File> files = new ArrayList<>();

        // int splitLength = 1024*70; //70kb

        for (data) {
          //create the csv file with data using apache common csv library
         // add the csv file to files like below
           files.add(file)//csv files 
        }

        zipFile.createSplitZipFile(files, zipParameters, true, 1024 * 70);
```

**Comment by srikanth-lingala** [comment]
How do you know that the content inside all the split zip files is the same? The content length will be the same because of the split length. What happens when you try to extract the zip file?

**Comment by srikanthvadde** [comment]
Hi 
I am actually using sample data of 100k records to create the each csv file. Hence when i check each zip file contents all files have same data with same size but the zip file is splitting up and size reduces.

Attaching some screenshots for reference: please go through on order wise.
![s-1](https://user-images.githubusercontent.com/31717083/178942346-4e32a3e2-2501-4ecc-bce5-f58501ca3d52.PNG
![s-2](https://user-images.githubusercontent.com/31717083/178942315-b3af1e33-14a2-4ed0-aeca-391b4e05bba0.PNG)
![s-3](https://user-images.githubusercontent.com/31717083/178942324-8616651b-b0f8-4817-839a-719e6043480a.PNG)
![s-4](https://user-images.githubusercontent.com/31717083/178942327-1caebb44-5e44-44cd-8145-97e7c322cb09.PNG)
![s-5](https://user-images.githubusercontent.com/31717083/178942933-ebbe6314-ab72-4e1f-b650-e15a1f5d778a.PNG)

**Comment by srikanth-lingala** [comment]
I believe your understanding of a split zip file is different than the way it is actually supposed to work. Each part of a split zip file is NOT a zip file by itself. Each part is just that, a part of the complete zip file. You cannot just extract one part of a split zip file. When you extract a split zip file, you are extracting content from all the split zip files. In your case, the csv files that you see are the entries in both compressed.zip and compressed.z01. Hope this makes it clear.
