### ISSUE TITLE
split zip files can not extract single file correctly

### ISSUE THREAD

**Issue by lzxshare** [srikanth-lingala/zip4j#459]
because i have many files，i split the zip file,like this:
 
    ZipParameters zipParameters = new ZipParameters();
    zipParameters.setEncryptFiles(true);
    zipParameters.setCompressionLevel(CompressionLevel.FAST);
    zipParameters.setIncludeRootFolder(false);
    zipParameters.setSymbolicLinkAction(ZipParameters.SymbolicLinkAction.INCLUDE_LINK_AND_LINKED_FILE);
    zipParameters.setEncryptionMethod(EncryptionMethod.ZIP_STANDARD);  
    
    ZipFile zipFile = new ZipFile(packOutputFile, keyword.toCharArray());
    zipFile.setRunInThread(true);
    zipFile.createSplitZipFile(backFileList, defaultZipParameters, true, SPLIT_SIZE);

    some files has the same file name，but from different path：
   
    A/B/C/fileName.txt
    A/F/G/fileName.txt
    A/B/C/P/fileName.txt
    E/B/C/fileName.txt
    ....

   i want to extract single file,like A/B/C/P/fileName.txt,and i use this api code:

   FileHeader fileHeader = zipFile.getFileHeader("fileName.txt");
   zipFile.extractFile(fileHeader, parentFile.getAbsolutePath(), mergeName);

   but i got a not correct file.i also use the full path to get FileHeader:

  FileHeader fileHeader = zipFile.getFileHeader("A/B/C/P/fileName.tx");
  zipFile.extractFile(fileHeader, parentFile.getAbsolutePath(), mergeName);
  
  but they returns null,i also debug the source code，and i found Zip FileHeader only show file names,debug info  like this:
  
 ![image](https://user-images.githubusercontent.com/39763177/181213165-7166f80b-5527-4b24-b532-db2e8372445d.png)

  note: the parameters passed "backFileList"  all is the files， not contains folder

  and here is output zip file,the encryption password is 111111,you can input password to unzip the test file.
  
  could you give me some helpful ideas？this question has puzzled me for a long time, and i want to solve it as soon as 
  possible.
  thank you very much.
   
[1658803896900.zip](https://github.com/srikanth-lingala/zip4j/files/9197021/1658803896900.zip)

**Comment by srikanth-lingala** [comment]
`zipFile.createSplitZipFile` works at a file level and does not preserve the folder. To preserve folder structure, you have to use `zipFile.createSplitZipFileFromFolder`.
