### ISSUE TITLE
Replacing the file in the zip makes the position of the file move to the bottom of the list

### ISSUE THREAD

**Issue by AozoraDev** [srikanth-lingala/zip4j#470]
Hey hay!
So, I used `.addFile()` to replace a file into a zip.

But after the process is complete and I refresh the FileHeaders list, the file position moves to the bottom.
![IMG_20220826_164400](https://user-images.githubusercontent.com/61007475/186863411-8602e231-80b3-4aa1-aba0-e58bf520d578.JPG)

**Comment by srikanth-lingala** [comment]
Yeah, when an entry in a zip file is replaced, it basically removes that entry from that position in the zip file, and appends it to the end of the zip file. Zip4j cannot override in the existing location of the entry because the size of the entry might change.

**Comment by AozoraDev** [comment]
Oh okay. Thanks!
