### ISSUE TITLE
some time I am getting file not found exception

### ISSUE THREAD

**Issue by Abhijeet41** [srikanth-lingala/zip4j#477]
Hi I am using this library to to zip folder but in first attempt I am getting file not found exception after going to app setting and uncheck storage permission and check again then it will generate zip file for me how to fix this issue even I am using latest version of this library.
please help

**Comment by Abhijeet41** [comment]
library issue

**Comment by Abhijeet41** [comment]
hey guys any one face this issue?

**Comment by srikanth-lingala** [comment]
Do you still need any support with this issue? If yes, please provide more details like which version of zip4j you are using, your code snippet, etc.

**Comment by Abhijeet41** [comment]
Hi this dependecy  I usedimplementation 'net.lingala.zip4j:zip4j:2.9.0'
TargetSdkVersion=28
CompileSdkVersion=28
MinSdkVersion=22

**Comment by srikanth-lingala** [comment]
Try to use the latest version of zip4j to see if that fixes the issue. 
There is not a lot I could help with the information in the issue.

**Comment by srikanth-lingala** [comment]
Closing this issue as there is no further feedback. If you still face this issue, please feel free to reopen, but please provide some additional details for me to look into. With the data above, I really cannot do much.
