### ISSUE TITLE
add constructor for streams please

### ISSUE THREAD

**Issue by Tedgh** [srikanth-lingala/zip4j#480]
I have a project with samba files... I found no way to use this nice lib because of the File Constructor only

**Comment by srikanth-lingala** [comment]
`ZipFile` api, as the name suggests is for use with files. When using streams, you have to use zip4j's `ZipInputStream`/`ZipOutputStream`. I cannot merge these two, i.e., I cannot make ZipFile deal with streams, because as mentioned earlier, ZipFile deals with files.
