### ISSUE TITLE
0 KB size ZIP file is created with net.lingala.zip4j:zip4j:2.11.2 in Android

### ISSUE THREAD

**Issue by NagarjunaSudi** [srikanth-lingala/zip4j#482]
Hi,

I have used net.lingala.zip4j:zip4j:2.11.2 gradle dependency in android project to create a zip file. The created Zip file will contain a folder, folder with in the main folder. The final folder will contain a TXT file.

Zip file instance created using below approach.

new ZipFile(mFileName,password.toCharArray());

Once I copied the logs, Observed 0 KB zip file created. When I try to extract the 0 KB ZIP file. It is giving error "The archive is either in unknown format or damaged"

I have used below code to create the ZIP file from files.

The issue is not always. It is observed randomly.

ZipParameters zipParameters = new ZipParameters();
zipParameters.setEncryptFiles(true);
zipParameters.setEncryptionMethod(EncryptionMethod.ZIP_STANDARD);
ZipFile zipFile = null;
try {
zipFile = new ZipFile(mFileName,password.toCharArray());
zipFile.addFiles(filesToAdd,zipParameters);
}

Thanks IN advance for your answer.

**Comment by NagarjunaSudi** [comment]
Hi, Can you please provide update on above. Thanks.

**Comment by NagarjunaSudi** [comment]
Hi Team,

We had major issue due to 0KB zip file created. Please provide the solution for above. Thanks

**Comment by NagarjunaSudi** [comment]
Hi zip4j Team,

Can you please provide update on above. We are blocked for the release.

Thanks in advance.

**Comment by srikanth-lingala** [comment]
Which version of Android are you using? Are you able to reproduce this scenario? I know you mentioned that this happens randomly, but it would greatly help if you can reproduce this issue. 

My best guess at the moment is that zip4j starts to create the zip file, and before it can write contents to the zip file, there is some kind of exception. Do you log the exceptions? Did you see any exceptions in your logs?

**Comment by srikanth-lingala** [comment]
Closing this issue as there was no further feedback
