### ISSUE TITLE
Copyright owner name in LICENSE.

### ISSUE THREAD

**Issue by utaani** [srikanth-lingala/zip4j#490]
I want to use your software in an Android app, but the copyright notation in the LICENSE file is still the [yyyy] notation of the Apache License 2.0 template, so I can't display the copyright correctly in the app. 

Could you correct the copyright notation in the LICENSE file? Or is it okay to write that [name of copyright owner] is the author?

**Comment by srikanth-lingala** [comment]
I don't think that this is intended to be modified in the LICENSE. A lot of licenses, including those hosted by apache projects haven't changed it. However, I added a NOTICE file with your requested information. I think this is where this information is supposed to go.

References:
https://github.com/apache/kafka/blob/trunk/LICENSE#L190
https://github.com/apache/spark/blob/master/LICENSE#L189
https://github.com/spring-projects/spring-boot/blob/main/LICENSE.txt#L190
