### ISSUE TITLE
zip4j 2.10.0 vulnerability

### ISSUE THREAD

**Issue by KanchanDukare25** [srikanth-lingala/zip4j#491]
Currently I am using zip4j 2.10.0 jar for my application and I am using jdk 1.8 but for that jar there is vulnerability and latest version 2.11.4 using jdk 11 . So how to resolve this issue

**Comment by srikanth-lingala** [comment]
What do you think zip4j 2.11.4 is using JDK 11? Source and [target java versions](https://github.com/srikanth-lingala/zip4j/blob/master/pom.xml#L33) for zip4j is Java 1.7. It should be compatible with JDK 1.8

**Comment by KanchanDukare25** [comment]
Resolved
