### ISSUE TITLE
Is there some way to use addStream() and createSplitZipFile...() together?

### ISSUE THREAD

**Issue by DarkQrow** [srikanth-lingala/zip4j#497]
I noticed there is no method "createSplitZipFile" for Streams, but maybe i missed something. And if it is really no way to use Streams and splitZip, why? Is it header problem?

**Comment by srikanth-lingala** [comment]
I added this feature. I will include this in the next release

**Comment by NanyangTaiji** [comment]
Create a large zip file and then split it.
