### ISSUE TITLE
Direct coverage when a file with the same name exists in the archive.

### ISSUE THREAD

**Issue by isMeiying** [srikanth-lingala/zip4j#50]
When adding a file to compression, a file with the same name exists in the archive. an override option should be provided.

**Comment by srikanth-lingala** [comment]
Will include this feature in the next release

**Comment by isMeiying** [comment]
> 将在下一版本中包含此功能

If it is a folder, it is best to cover it as well. Thank you for your work.

**Comment by isMeiying** [comment]
![image](https://user-images.githubusercontent.com/13428030/63632068-785d8400-c662-11e9-9dfe-a6fc530bf51b.png)

Compression will crash when a file with the same name exists in the zip!

**Comment by LeeYoung624** [comment]
Hey @isMeiying 

> Compression will crash when a file with the same name exists in the zip!

Could you please provide your test code and test files? This exception seems not likely caused by same name files. More detail information could help to find out what's going on here.

**Comment by srikanth-lingala** [comment]
`ZipParameters.overrideExistingFilesInZip` feature added in v2.1.3 released today.

Regarding the ZipException, I was unable to reproduce that error both on windows and a mac. As LeeYoung pointed out, please provide more info (code, zip sample, etc) for us to investigate, and please open a new issue if you have those details. Thanks.
