### ISSUE TITLE
RemoveFileFromZipFile.javaThis will remove all files in the compressed file

### ISSUE THREAD

**Issue by billqs** [srikanth-lingala/zip4j#51]
RemoveFileFromZipFile.javaThis will remove all files in the compressed file, not the specified file

**Comment by srikanth-lingala** [comment]
Please post the code you used and attach a zip file if possible. Zip4j has tests to make sure that it deletes only the file it is asked to delete. Either there is a problem with your code or the zip file or there is a bug in zip4j. Your issue description does not really help me to investigate the issue and I will need more details to look into it.

**Comment by billqs** [comment]
[compression.zip](https://github.com/srikanth-lingala/zip4j/files/3523877/compression.zip)

[RemoveFileFromZipFile.zip](https://github.com/srikanth-lingala/zip4j/files/3523883/RemoveFileFromZipFile.zip)
The compression. Zip file contains two TXT files. The program I wrote requires that only a.txt be deleted, but another TXT document will be deleted at the same time

**Comment by srikanth-lingala** [comment]
This is the code you have used:

```
public RemoveFileFromZipFile(String path,String name) {
		
	try {
		// Initiate ZipFile object with the path/name of the zip file.
		ZipFile zipFile = new ZipFile(path);
		
		// Note: If this zip file is a split file then this method throws an exception as
		// Zip Format Specification does not allow updating split zip files
		
		// Please make sure that this zip file has more than one file to completely test
		// this example
		
		// Removal of a file from a zip file can be done in two ways:
		// 1. Specify the name of the relative file to the removed
		zipFile.removeFile(name);
		
		// 2. With the FileHeader
		if (zipFile.getFileHeaders() != null && zipFile.getFileHeaders().size() > 0) {
			zipFile.removeFile((FileHeader)zipFile.getFileHeaders().get(0));
		} else {
			System.out.println("This cannot be demonstrated as zip file does not have any files left");
		}
		
	} catch (ZipException e) {
		e.printStackTrace();
	}
	
}
```

This was an example from Zip4jExamples package. As the comments describe, this example demonstrates the two ways you can remove a file from a zip file. You have to you only one of them. You have to either use `ZipFile.removeFile(String)` where string is the name of the file you have to delete or use `ZipFile.removeFile(FileHeader)` if you have a `FileHeader` that you want to remove. Please use one of it only and not both. The intention of this example was to only show the two possible ways. I tried the below example and it only deletes the one file I ask it to delete:

```
ZipFile zipFile = new ZipFile("compression.zip");
zipFile.removeFile("a.txt");
``` 

I am closing the issue as this is not an issue with zip4j but rather an issue with the code you are using. Please reopen if you still have the issue with the code I suggested above.

**Comment by billqs** [comment]
Ok,thank you very much!
