### ISSUE TITLE
java.io.IOException: CRC (MAC) check failed for xxx.xlsx

### ISSUE THREAD

**Issue by lintao0701** [srikanth-lingala/zip4j#556]
<img width="1013" alt="image" src="https://github.com/user-attachments/assets/20cdeaef-393c-41b0-9c40-c04eaf6ca968">
<img width="402" alt="image" src="https://github.com/user-attachments/assets/4cdc686d-424d-4e72-9f43-8486fcccd61b">
<img width="872" alt="image" src="https://github.com/user-attachments/assets/ff47ab9c-5e74-42bc-a1f0-98c6c6ae416d">
<img width="928" alt="image" src="https://github.com/user-attachments/assets/a0567ca4-f969-47c5-a3fb-62b16d947b92">

**Comment by srikanth-lingala** [comment]
Please use the latest version of Zip4j. v1.3.1 is quite old and a lot of bugs have been fixed in v2.x

**Comment by lintao0701** [comment]
ok
