### ISSUE TITLE
Unused method decrementBytesWrittenForThisEntry

### ISSUE THREAD

**Issue by LeeYoung624** [srikanth-lingala/zip4j#56]
It looks like that the method [decrementBytesWrittenForThisEntry](https://github.com/srikanth-lingala/zip4j/blob/master/src/main/java/net/lingala/zip4j/io/outputstream/CipherOutputStream.java#L70-L72) is not used by any methods.
Is this a deprecated method? If so, maybe it should be deleted,or a @Deprecated annotation should be added.

**Comment by srikanth-lingala** [comment]
Thanks for pointing it out. I have removed the method.
