### ISSUE TITLE
ZipFile.getFileHeaders() states that it will throw an Exception in case of a non-existing file, but doesn't

### ISSUE THREAD

**Issue by repolevedavaj** [srikanth-lingala/zip4j#57]
The method ZipFile.getFileHeaders() states in the Javadoc that it will throw an Exception in case of a non-existing file, but doesn't. Either the Javadoc should be changed accordingly or the method should really throw an Exception.

**Comment by srikanth-lingala** [comment]
Fixed in v2.1.3 released today
