### ISSUE TITLE
Adding a Stream to a password-protected zip file requires manually setting entryCRC on ZipParameters

### ISSUE THREAD

**Issue by daelfdude** [srikanth-lingala/zip4j#59]
Maybe there is no other choice.  But I had to dig pretty hard to discover that when I use net.lingala.zip4j.ZipFile.addStream(InputStream, ZipParameters), unless I do the following set of steps, I am unable to extract/open the file from within the password-protected zip file using the expected password.

1. Write the inputStream to a file
1. Use net.lingala.zip4j.util.CrcUtil.computeFileCrc(File, ProgressMonitor) to calculate the CRC value
1. Take the result of the previous step and pass it to ZipParameters.setEntryCRC()

**Comment by srikanth-lingala** [comment]
I am not sure if I get your point. From what I understood, I tried the below code, and I am able to add stream to an already existing password-protected zip file without having to calculate crc from this code. Basically what I do here is:

1. Create a password protected zip file
2. Add a stream to this zip file (this stream also has a password)
3. Assert zip contents and Extract contents to make sure extraction is fine

```
@Test
  public void zipTest() throws IOException {
    File file = new File("/Users/srikanth/Downloads/test.zip");
    char[] password = "password".toCharArray();
    ZipFile zipFile = new ZipFile(file, password);
    ZipParameters zipParameters = createZipParameters();
    zipFile.addFile(TestUtils.getTestFileFromResources("sample.pdf"), zipParameters);

    addFileAsStreamToZip(TestUtils.getTestFileFromResources("sample_text1.txt"), file, password, zipParameters);

    extractZipFile(file, password);
  }

  private void addFileAsStreamToZip(File fileToAdd, File outputZipFile, char[] password, ZipParameters zipParameters) throws IOException {
    ZipFile zipFile = new ZipFile(outputZipFile, password);

    try(InputStream inputStream = new FileInputStream(fileToAdd)) {
      zipParameters.setFileNameInZip(fileToAdd.getName());
      zipFile.addStream(inputStream, zipParameters);
    }
  }

  private void extractZipFile(File zipFileToExtract, char[] password) throws ZipException {
    ZipFile zipFile = new ZipFile(zipFileToExtract, password);
    assertThat(zipFile.getFileHeaders()).hasSize(2);
    zipFile.extractAll(zipFileToExtract.getParent());
  }

  private ZipParameters createZipParameters() {
    ZipParameters zipParameters = new ZipParameters();
    zipParameters.setEncryptFiles(true);
    zipParameters.setEncryptionMethod(EncryptionMethod.AES);
    return zipParameters;
  }
```

As you can see I did not have to call `CrcUtil.computeFileCrc()` to add a stream, and I am able to the extract the zip file without any issues.

**Comment by srikanth-lingala** [comment]
Closing issue as there is no further feedback. If you think there is still an issue, please reopen or create a new issue with more details. Thanks.
