### ISSUE TITLE
Add character set on ZipInputStream class?

### ISSUE THREAD

**Issue by jacktang** [srikanth-lingala/zip4j#64]
Hello,

How about add character set on `ZipInputStream` like `java.util.zip.ZipInputStream` so that we can handle other character set rather than only UTF8?

**Comment by LeeYoung624** [comment]
I'm a little confused. Please feel free let me know if I'm wrong.
`ZipInputStream` can read zipped file by `read` method, and it's stored as raw byte array `byte[]`. It can transformed into other charset by `new String(buffer, CHARSET)`. Sample code :
```
public static void main(String[] args) throws Exception {
    FileInputStream fis = new FileInputStream("/root/test.zip");
    ZipInputStream zis = new ZipInputStream(fis);
    byte[] readBuffer = new byte[1024];
    while(zis.getNextEntry() != null) {
      while(zis.read(readBuffer) != -1) {
        System.out.println(readBuffer);
        System.out.println(new String(readBuffer, StandardCharsets.UTF_8));
      }
    }
}
```
Why do we need a method to set the charset for `ZipInputStream`?

**Comment by srikanth-lingala** [comment]
@LeeYoung624 I think what Jack meant was the Charset to be used for filename and file comment for each LocalFileHeader.

@jacktang According to zip specification, only two charsets are supported in a zip format - cp437 and utf8. This makes it easy for zip files to be handled among different tools/libraries/applications without knowing the source charset explicitly (zip headers do not store the charset, but only a flag wether it is utf8 or not). Zip4j was designed to support the default zip format expectations. 

However, there have been a lot of requests on this topic (most of them were for ZipFile api). I will analyse this and if feasible, will add this feature.

**Comment by jacktang** [comment]
@srikanth-lingala yes, the filename and comment depends on the correct character set. And appreciate your time! 🍺

**Comment by srikanth-lingala** [comment]
Feature added in v2.2.1 released today
