### ISSUE TITLE
Add a file as a stream, with the file name repeated, not overwritten

### ISSUE THREAD

**Issue by l54808821** [srikanth-lingala/zip4j#70]
ZipParameters zipParameters = new ZipParameters();
        zipParameters.setFileNameInZip("data/result.csv");
        ZipFile zipFile = new ZipFile("D:\\浏览器下载路径\\jmeterTemplate.zip");
        List<FileHeader> fileHeaders = zipFile.getFileHeaders();
        for (FileHeader fileHeader : fileHeaders) {
            new ZipFile("D:\\浏览器下载路径\\aaa.zip").addStream(zipFile.getInputStream(fileHeader), zipParameters);
            System.out.println(fileHeader.getFileName());
        }

![image](https://user-images.githubusercontent.com/49773498/65675395-b6463180-e080-11e9-999e-8483708700be.png)

**Comment by LeeYoung624** [comment]
I think you are adding files via `addStream` and set different files to the same name by ZipParameters. I don't know why would you do this.
There is a `remove if file exist` detect in `addFile`, and a override flag `overrideExistingFilesInZip` in ZipParameters. Maybe you can try this.

@srikanth-lingala Maybe we can adding the `remove if file exist` in ZipOutputStream? 
Besides, I think we should take the `fileNameInZip` into account when checking the existing file in zip.

**Comment by srikanth-lingala** [comment]
Fixed in v2.2.1
