### ISSUE TITLE
Corrupted archive with large files

### ISSUE THREAD

**Issue by johnybillson** [srikanth-lingala/zip4j#75]
As the title says, i'm experiencing trouble when trying to zip large files (over 10 GB) with compression method 'STORE'.

The process seems to work fine, no exception occurs, but the zip created cannot be exctracted using anything else than zip4j library. For exemple when trying to extract the zip with winrar, i get the error : 'Checksum error... the file is corrupt'

I have tried changing some of the ZipParameters, unsuccessfully.
The library works fine with smaller archives.
I am running on windows (7 and 10) 64 bits

I am going to turn to another library in the meantime, but a fix would be welcome, since zip4j is one of the fastest, and simple to use (nice job !)

**Comment by sa-pm17** [comment]
I have tested another not bad lib [zip4jvm](https://github.com/oleg-cherednik/zip4jvm). Version from *dev* branch works pretty well with huge files and archives. I also checked the compatibility testest there.

**Comment by srikanth-lingala** [comment]
@johnybillson With which version of zip4j have you tried? There was a bug fix done for a [similar issue][1] in the latest release v2.2.1.

[1]: https://github.com/srikanth-lingala/zip4j/issues/71

**Comment by johnybillson** [comment]
> 
> 
> @johnybillson With which version of zip4j have you tried? There was a bug fix done for a [similar issue](https://github.com/srikanth-lingala/zip4j/issues/71) in the latest release v2.2.1.


I feel stupid for not thinking about that before..
I was using 2.1.4, i just tried with 2.2.1 and it works fine.

Thank you for the reply and sorry for the mistake^^
You can close the issue

**Comment by johnybillson** [comment]
Just for information, the issue concerned the files over 4 GB, and you fixed it.
Is there a new maximum size ?
Will it work with folders of several TeraBytes for example ?

Thanks

**Comment by srikanth-lingala** [comment]
The maximum i have tested is with an archive size of 25GB. I haven't tested with terrabytes, although i don't see any reason why it should not work. Zip file format (zip64 to be more specific) supports file size of upto 16 exabytes. If you get a chance to test it with huge file sizes, I would love to hear how it went.

**Comment by oleg-cherednik** [comment]
According to Zip specification, standard zip has maximum **dword** (i.e. 4 bytes or 0xFFFF_FFFF) length of each entry. For Zip64 - this is **qword** (i.e. 8 bytes or 0xFFFF_FFFF_FFFF_FFFF) ). All values are usnigned.
