### ISSUE TITLE
Unsupported features for Android API levels lower than 19, which cause crashes

### ISSUE THREAD

**Issue by d-u-a-l** [srikanth-lingala/zip4j#78]
Latest release uses
`java.nio.charset.StandardCharsets`
which available in Android starting with API level 19 (Kitkat). When I use library, no warnings about it not supporting older versions of Android (Jelly Bean, for example) were issued by Android Studio. You should change minSdk to 19 or make a workaround for API levels lower than 19

**Comment by nicolabeghin** [comment]
Following, any plan for a hotfix? Thanks a lot!

**Comment by nicolabeghin** [comment]
@srikanth-lingala pushed PR #79, please take a look if it makes sense for you, thanks!

**Comment by srikanth-lingala** [comment]
Fixed in v2.2.2 released today
