### ISSUE TITLE
Improvement / new functionality (About executor and task)

### ISSUE THREAD

**Issue by ColinViatte** [srikanth-lingala/zip4j#80]
![Capture](https://user-images.githubusercontent.com/51704546/66301445-73dde980-e8f7-11e9-984d-e30ec323c707.PNG)
I need to modify the executor because I want to use a ThreadFactory and change the threads to demon (setDemon (true))
A new setExecutor method would be very convenient

**Comment by srikanth-lingala** [comment]
Do you intend to ask to expose the executor or the runnable/thread (which is currently a lambda in your screenshot)?

**Comment by srikanth-lingala** [comment]
Closing this issue as there is no further feedback
