### ISSUE TITLE
How to add multiple files and folders at once?

### ISSUE THREAD

**Issue by ghost** [srikanth-lingala/zip4j#84]
What should I do to compress multiple files and multiple folders into the root directory? Single compression seems to be very slow, can you compress multiple files and multiple folders at once?

`like this?`
```
ZipFile().addFolders()
```

Also, how to delete the folder inside the archive, the api seems to only provide the delete file.

**Comment by srikanth-lingala** [comment]
To answer the two questions:

- **How to add multiple files and folders at once?**
  You can achieve this by a for loop as shown below. This is probably not the most "neat" way, but this is the only way with the current version

```
for (File folder : folders) {
    ZipFile.addFolder(folder); //same for files
}
```

- **How to delete a folder inside an archive?**
  ZipFile does not have an api to delete a folder inside an archive. A workaround for this would be:

Considering that the folder name relative to the root of the zip file is `/somefolder/folder2`, and you want to delete this folder, then :
```
String folderToDelete = "somefolder/folder2";
for (FileHeader fileHeader : zipFile.getFileHeaders()) {
  if (fileHeader.getFileName.startsWith()) {
     ZipFile.deleteFile(fileHeader);
  }
}
```

Both the code samples above should work but are not tested by me. I wrote the code here directly, so there might be some syntax errors. But I think you get the idea.

Both of these points are good candidates for new features. The first one might be slightly complicated from an api perspective, but I will consider adding them in one of the next releases.

**Comment by isMeiying** [comment]
> To answer the two questions:
> 
> * **How to add multiple files and folders at once?**
>   You can achieve this by a for loop as shown below. This is probably not the most "neat" way, but this is the only way with the current version
> 
> ```
> for (File folder : folders) {
>     ZipFile.addFolder(folder); //same for files
> }
> ```
> 
> * **How to delete a folder inside an archive?**
>   ZipFile does not have an api to delete a folder inside an archive. A workaround for this would be:
>   Considering that the folder name relative to the root of the zip file is `/somefolder/folder2`, and you want to delete this folder, then :
> 
> ```
> String folderToDelete = "somefolder/folder2";
> for (FileHeader fileHeader : zipFile.getFileHeaders()) {
>   if (fileHeader.getFileName.startsWith()) {
>      ZipFile.deleteFile(fileHeader);
>   }
> }
> ```
> 
> Both the code samples above should work but are not tested by me. I wrote the code here directly, so there might be some syntax errors. But I think you get the idea.
> 
> Both of these points are good candidates for new features. The first one might be slightly complicated from an api perspective, but I will consider adding them in one of the next releases.

I added a folder with the same name in zip, it is very slow, how should I speed it up?

**Comment by LeeYoung624** [comment]
I tested with adding the same folder to a zip file more than once. It only takes slight more time when the folder already exists in zip file.

When adding a file to a archive which containes a file with same name, zip4j will by default override the same name file(so are the folders). That means the zip4j will firstly remove the existing file in the archive, then add the new file. That's why adding a file to a archive which containes a file with same name takes more time.
And the removing file procedure is implemented by removing file by file, which means it may take more time if the folder contains a lot of files. I think that's why you take a lot more time when adding a folder with the same folder existing in the zip.

If you do not want to override the same name file in zip, you can do it like this
```
ZipFile zipFile = new ZipFile("/home/zipfile.zip");
ZipParameters parameters = new ZipParameters();
parameters.setOverrideExistingFilesInZip(false);
zipFile.addFolder(new File("/folder/to/add"), parameters);
```

**Comment by sa-pm17** [comment]
I use this one - [zip4jvm](https://github.com/oleg-cherednik/zip4jvm). You could try it as an alternative.

**Comment by srikanth-lingala** [comment]
@sa-pm17 Please stop marketing your library on this forum. I have seen your similar messages spamming in other issues as well. I am now going to delete your comment.  BTW, zip4jvm, including the name, looks like a rip-off of zip4j, with some minor modifications, which I have nothing against (although it would have been nice if there was a credit somewhere), but such marketing spamming messages is what drives me crazy.

**Comment by srikanth-lingala** [comment]
I see multiple ideas for new features here in zip4j:

- In ' ZipFile.addFiles()' , if the file is a directory, then add all files in that directory to the zip. This way you can achieve the requirement mentioned in this issue.

- Delete a folder inside an archive

- Delete multiple files inside an archive at once, which is more efficient than deleting files in a loop, as the zip file has to be recreated with each deletion.

I will include these features in one of the next release (hopefully in the next release if time permits)

**Comment by isMeiying** [comment]
> I see multiple ideas for new features here in zip4j:
> 
> * In ' ZipFile.addFiles()' , if the file is a directory, then add all files in that directory to the zip. This way you can achieve the requirement mentioned in this issue.
> * Delete a folder inside an archive
> * Delete multiple files inside an archive at once, which is more efficient than deleting files in a loop, as the zip file has to be recreated with each deletion.
> 
> I will include these features in one of the next release (hopefully in the next release if time permits)

Hey bro, this is great! I waiting for your release!

**Comment by markgbrown** [comment]
I may have a related request.  We are trying to zip up multiple files in multiple different folder locations, retaining the folder hierarchy, and utilizing the split zip functionality to keep zip sizes under 4GB.  I don't currently see a way to accomplish this.  Is there a workaround?

**Comment by srikanth-lingala** [comment]
@markgbrown Your requirement is to create a zip file with:

1. Multiple files from different folder locations
2. Retain the folder hierarchy
3. Split zip to keep size under 4GB

Unfortunately, a combination of all 3 is not possible at the moment. You can choose any 2 of the 3, but unfortunately, not all 3 together.

**Comment by markgbrown** [comment]
@srikanth-lingala I have implemented a solution that works for us for this scenario.  It allows the files in the zip to retain the same folder hierarchy as the input files.  If you are interested in the solution, I can send you the files that changed and you can decide whether it makes sense to incorporate into the library.  I've never had the chance to contribute to open source before, so let me know what works best.

**Comment by srikanth-lingala** [comment]
@markgbrown Sure, please send me a patch or a PR and I will have a look into it. Just to be clear, when I said `it is not possible at the moment`, I meant it is not possible with the current version of zip4j. When I implement the change in this issue, depending on the complexity and feasibility, I will consider integrating your change as well.

**Comment by markgbrown** [comment]
Here's a pull request for you to look at.  Feel free to use any or none of it as you feel appropriate.
#116

**Comment by 18905059768** [comment]
我觉得添加文件或文件夹能否别拆开，在程序内部进行判断，因为当我想获取一个ProgressMonitor进度监听器的时候，并不能够同时监听两个进程的任务

**Comment by oO0oO0oO0o0o00** [comment]
> To answer the two questions:
> 
> * **How to add multiple files and folders at once?**
>   You can achieve this by a for loop as shown below. This is probably not the most "neat" way, but this is the only way with the current version
> 
> ```
> for (File folder : folders) {
>     ZipFile.addFolder(folder); //same for files
> }
> ```
> 
> * **How to delete a folder inside an archive?**
>   ZipFile does not have an api to delete a folder inside an archive. A workaround for this would be:
>   Considering that the folder name relative to the root of the zip file is `/somefolder/folder2`, and you want to delete this folder, then :
> 
> ```
> String folderToDelete = "somefolder/folder2";
> for (FileHeader fileHeader : zipFile.getFileHeaders()) {
>   if (fileHeader.getFileName.startsWith()) {
>      ZipFile.deleteFile(fileHeader);
>   }
> }
> ```
> 
> Both the code samples above should work but are not tested by me. I wrote the code here directly, so there might be some syntax errors. But I think you get the idea.
> 
> Both of these points are good candidates for new features. The first one might be slightly complicated from an api perspective, but I will consider adding them in one of the next releases.

Is it doing the follow:
```
open -> add a folder -> close -> open -> add a folder -> close -> ...
```

**Comment by srikanth-lingala** [comment]
These two features have been added in the branch `delete-multiples-and-folders`:

- Delete a folder inside an archive
- Delete multiple files inside an archive at once

I will merge it to master and include it in the next release.

Working on the third feature:

- In ' ZipFile.addFiles()' , if the file is a directory, then add all files in that directory to the zip.

**Comment by srikanth-lingala** [comment]
The last feature 
 
* In ' ZipFile.addFiles()' , if the file is a directory, then add all files in that directory to the zip.
 
is a bit complicated and tricky to implement. This will also break backward compatibility. It might be that there are users of zip4j adding files to a zip which is a directory and not expecting the whole directory to be added. If this change is now done, it might break their logic. And also there are some complicated questions of what the rootDirectory of the file (which is a folder) should be because the root directory of this file can be different than the other files being added.

The other two features:

* Delete a folder inside an archive
* Delete multiple files inside an archive at once

 have long been implemented and released
