### ISSUE TITLE
Encription option doesn't work.

### ISSUE THREAD

**Issue by Kejam** [srikanth-lingala/zip4j#95]
I wrote a method that compresses directory to zip and set a password to the zip. I used examples in readme.md but I couldn't implement. And wrote one test that checks it. 

How can I set the password to zip?

Code below: 

`final ZipParameters zipParameters = new ZipParameters();
        zipParameters.setCompressionMethod(CompressionMethod.STORE);
        zipParameters.setEncryptFiles(true);
        zipParameters.setEncryptionMethod(EncryptionMethod.AES);
        zipParameters.setAesKeyStrength(AesKeyStrength.KEY_STRENGTH_256);
        final ZipFile zipFile = new ZipFile(nameZip, password.toCharArray());
        ProgressMonitor progressMonitor = zipFile.getProgressMonitor();
        try {
            zipFile.addFolder(sourceFolder, zipParameters);
            while (!progressMonitor.getState().equals(ProgressMonitor.State.READY)) {
                System.out.println("Percentage done: " + progressMonitor.getPercentDone());
                System.out.println("Current file: " + progressMonitor.getFileName());
                System.out.println("Current task: " + progressMonitor.getCurrentTask());
                Thread.sleep(100);
            }`

Test:

`@Test
    void compressBackup() throws IOException {
        final String name = "/target/test.zip";
        final String path = "/target/s3/";
        if (Files.notExists(Paths.get(path))) {
            Files.createDirectory(Paths.get(path));
        }
        final boolean resultCompress = archiver.compressBackup(new File(name), new File(path), "password");
        assertTrue(resultCompress);
        final boolean resultDelete = archiver.deleteTempDirectory(path);
        assertTrue(resultDelete);
        final ZipFile zipFile = new ZipFile(new File(name));
        assertTrue(zipFile.isEncrypted());
    }`

**Comment by srikanth-lingala** [comment]
Your code works perfectly fine for me. Here's what I tried:

```
@Test
public void testZip4j() throws IOException, InterruptedException {
  final ZipParameters zipParameters = new ZipParameters();
  zipParameters.setCompressionMethod(CompressionMethod.STORE);
  zipParameters.setEncryptFiles(true);
  zipParameters.setEncryptionMethod(EncryptionMethod.AES);
  zipParameters.setAesKeyStrength(AesKeyStrength.KEY_STRENGTH_256);

  ZipFile zipFile = new ZipFile("test.zip", "password".toCharArray());

  ProgressMonitor progressMonitor = zipFile.getProgressMonitor();
  zipFile.addFolder(new File("/Users/srikanth/tmp/myfolder"), zipParameters);

  while (!progressMonitor.getState().equals(ProgressMonitor.State.READY)) {
    System.out.println("Percentage done: " + progressMonitor.getPercentDone());
    System.out.println("Current file: " + progressMonitor.getFileName());
    System.out.println("Current task: " + progressMonitor.getCurrentTask());
    Thread.sleep(100);
  }

  zipFile = new ZipFile("test.zip");
  Assertions.assertThat(zipFile.isEncrypted()).isTrue();
}
```

One a side note: If you want to use ProgressMonitor, you have to set `ZipFile.setRunInThread(true)` before you start adding files to zip. Only then will you able to track the progress in a while loop. In your example, this line should be before `zipFile.addFolder(sourceFolder, zipParameters);`

**Comment by Kejam** [comment]
I found the solution, everything was ok but I wrote the incorrect test. If the directory is empty lib can't create any archive as an archive.  He creates "test.zip" as a simple file that is associated with notepad.
