### ISSUE TITLE
substitution of setRootFolderInZip?

### ISSUE THREAD

**Issue by tRavAsty** [srikanth-lingala/zip4j#97]
Hi there,
  we are upgrading our zip4j dependency from 1.3.2 to 2.1.0, although we were able to substitue several constructors and functions (such as Zip4jConstants.COMP_STORE to CompressionMethod.STORE, etc), we cannot find the substitution of ZipParameters::setRootFolderInZip function, can you give us any idea about how should we upgrade it to zip4j version 2?

**Comment by srikanth-lingala** [comment]
Looks like this feature was missed during the migration. I will add it back.

**Comment by srikanth-lingala** [comment]
I have added a feature `ZipParameters.setRootFolderNameInZip()`. Will include it in the next release.

**Comment by srikanth-lingala** [comment]
Featured added in v2.2.4 released today
