### ISSUE TITLE
Can I specify input in Stream in ZipFile?

### ISSUE THREAD

**Issue by Sentaroh** [srikanth-lingala/zip4j#98]
Hi,
Android10 ScopedStorage will not be able to use File except for some. It is necessary to specify ZipFile's inpiut and output in Stream.
Are there any plans to make Stream available in ZipFile?
The following is an image.
Uri inTreeUri=intent.getData();
InputStream is=context.getContentResolver().openInputStream(inTreeUri)
OutputStream is=context.getContentResolver().openInputStream(outTreeUri)

ZipFile zf=new ZipFile(is, os);
...................

**Comment by srikanth-lingala** [comment]
`ZipFile`, as the name suggests is to work with files and not streams. 
In your use case you have to use [`ZipInputStream`][1] and [`ZipOutputStream`][2] which work directly with the streams. There are some examples in ReadMe for these streams.

[1]: https://github.com/srikanth-lingala/zip4j/blob/master/src/main/java/net/lingala/zip4j/io/inputstream/ZipInputStream.java
[2]: https://github.com/srikanth-lingala/zip4j/blob/master/src/main/java/net/lingala/zip4j/io/outputstream/ZipOutputStream.java
